import type { ToolProfile } from '@/lib/tools/types';

export const activepieces: ToolProfile = {
  slug: 'activepieces',
  name: 'ActivePieces',
  tagline: '开源的 Zapier 替代方案',
  summary: 'ActivePieces 是一款开源的 Zapier 替代方案，提供可视化工作流设计和 100+ 预置集成，支持自托管，适合中小企业和开发者。',
  vendor: 'ActivePieces',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '开源', '可视化编排', '自部署', '轻量级'],
  homepageUrl: 'https://activepieces.com',
  githubUrl: 'https://github.com/activepieces/activepieces',
  docsUrl: 'https://www.activepieces.com/docs',
  lastReleaseDate: "2026-03-12T14:08:22Z",
  latestVersion: "0.79.3",
  lastCommitDate: "2026-03-23T08:10:29Z",
  githubStars: 21375,
  primaryLanguage: "TypeScript",
  pricing: '免费开源，云服务付费',
  license: 'MIT',
  focus: '可视化工作流、轻量级、自托管',
  deployment: 'Docker 部署，支持 npm 安装',
  modelSupport: ['AI 片段', '支持集成 LLM'],
  connectivity: ['100+ 预置集成', 'REST API', 'Webhook'],
  scenarios: ['市场营销自动化', '数据同步', '通知推送', '表单处理'],
  gfwStatus: '直连可用',
  pitfalls: ['社区规模较小', '集成数量待扩展'],
  benchmark: { successRate: 82, avgDurationMin: 3.2, retries: 1.3 },
  community: { stars: '8.5k', release: 'v0.25.0', trend: '快速增长' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.5, stability: 7.8, docs: 8.0 },
};
