import type { ToolProfile } from '@/lib/tools/types';

export const actiona: ToolProfile = {
  slug: 'actiona',
  name: 'Actiona',
  tagline: '跨平台自动化工具，800 stars',
  summary: 'Actiona 是一个跨平台自动化工具，支持鼠标、键盘和窗口操作。适合桌面自动化、 GUI测试、 任务自动化等场景。',
  vendor: 'Actiona Project',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://actiona.tools',
  githubUrl: 'https://github.com/Jmgr/actiona',
  docsUrl: 'https://wiki.actiona.tools',
  githubStars: 800,
  primaryLanguage: 'C++',
  pricing: '免费开源',
  license: 'GPL-3.0',
  focus: '跨平台自动化工具',
  deployment: 'Desktop Application',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['桌面自动化', 'GUI测试', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '社区规模较小', '功能有限'],
  benchmark: { successRate: 72, avgDurationMin: 1.0, retries: 2.0 },
  community: { stars: '800', release: 'v3.10.2', trend: '稳定' },
  rating: { security: 7.0, speed: 7.5, flexibility: 7.0, stability: 7.0, docs: 6.5 },
};
