import type { ToolProfile } from '@/lib/tools/types';

export const actiona: ToolProfile = {
  slug: 'actiona',
  name: 'Actiona',
  tagline: '跨平台开源自动化工具',
  summary: 'Actiona（原 Actionaz）是一款跨平台的开源自动化工具，支持 Linux 和 Windows，提供可视化流程编辑和脚本自动化能力。',
  vendor: 'Jonathan Mace',
  sourceType: '开源',
  region: '海外',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '跨平台', '开源', '可视化编排', 'Linux', 'Windows'],
  homepageUrl: 'https://actiona.tools',
  githubUrl: 'https://github.com/Jmgr/actiona',
  docsUrl: 'https://actiona.tools/docs',
  lastReleaseDate: "2025-04-13T21:13:29Z",
  latestVersion: "v3.11.1",
  lastCommitDate: "2026-03-22T09:50:01Z",
  githubStars: 669,
  primaryLanguage: "C++",
  pricing: '免费开源',
  license: 'GPL-3.0',
  focus: '跨平台桌面自动化、可视化流程编排',
  deployment: '本地桌面应用，Linux/Windows 原生支持',
  modelSupport: ['不支持 AI 模型', '规则驱动自动化'],
  connectivity: ['本地系统调用', '网络请求', '数据库连接'],
  scenarios: ['系统管理自动化', '批量文件处理', '定时任务', '数据同步'],
  gfwStatus: '直连可用',
  pitfalls: ['无 AI 能力需手动编排', 'macOS 支持有限'],
  benchmark: { successRate: 82, avgDurationMin: 4.5, retries: 1.2 },
  community: { stars: '1.1k', release: 'v11.2.0', trend: '稳定维护' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 8.2, docs: 7.0 },
};
