import type { ToolProfile } from '@/lib/tools/types';

export const adoptAi: ToolProfile = {
  slug: 'adopt-ai',
  name: 'Adopt AI',
  tagline: '用 AI 代理实现自动化',
  summary: 'Adopt AI 是一个企业级 AI 代理自动化平台。提供 API 发现和动作生成、端到端工作流执行、生产控制和可观测性、灵活的企业部署。支持云端、VPC 或完全本地部署，满足企业安全要求。',
  vendor: 'Adopt',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: '应用平台 / 工作流平台',
  tags: ['云服务', '企业流程', '工作流编排', 'API 集成', '安全合规', '部署'],
  homepageUrl: 'https://www.adopt.ai/',
  githubUrl: null,
  docsUrl: null,
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业定价',
  license: '专有',
  focus: 'API 发现、工作流执行、企业控制、灵活部署',
  deployment: '云端、VPC 或本地部署',
  modelSupport: ['多模型支持', 'AI 代理', '企业级 AI'],
  connectivity: ['API 集成', '工作流引擎', '审批流程', '可观测性'],
  scenarios: ['企业自动化', '工作流管理', 'API 集成', '安全合规'],
  gfwStatus: '需要代理',
  pitfalls: ['企业级定价', '需要销售对接'],
  benchmark: { successRate: 92, avgDurationMin: 5.0, retries: 1.0 },
  community: { stars: null, release: 'v1.0.0', trend: '商业运营' },
  rating: { security: 9.5, speed: 8.5, flexibility: 9.0, stability: 9.0, docs: 8.0 },
};
