import type { ToolProfile } from '@/lib/tools/types';

export const agentProtocol: ToolProfile = {
  slug: 'agent-protocol',
  name: 'Agent Protocol',
  tagline: 'AI Agent 通信协议标准',
  summary: 'Agent Protocol 是一款开放式的 AI Agent 通信协议标准，提供统一的任务接口和评估基准，适合构建标准化的 Agent 系统。',
  vendor: 'AI Engineers Foundation',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '协议标准', '开发工具'],
  homepageUrl: 'https://agentprotocol.ai',
  githubUrl: 'https://github.com/AI-Engineers-Foundation/agent-protocol',
  docsUrl: 'https://docs.agentprotocol.ai',
  githubStars: 1455,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '协议标准化、任务接口、评估基准',
  deployment: '多语言 SDK 支持',
  modelSupport: ['模型无关', '支持任意 LLM'],
  connectivity: ['REST API', '标准协议接口'],
  scenarios: ['Agent 系统开发', '基准测试', '跨平台集成'],
  gfwStatus: '直连可用',
  pitfalls: ['协议仍在演进中', '采用率有待提升'],
  benchmark: { successRate: 75, avgDurationMin: 4.0, retries: 1.5 },
  community: { stars: '1.8k', release: 'v1.2.0', trend: '稳定维护' },
  rating: { security: 7.8, speed: 7.5, flexibility: 8.0, stability: 7.4, docs: 7.2 },
};
