import type { ToolProfile } from '@/lib/tools/types';

export const agentS: ToolProfile = {
  slug: 'agent-s',
  name: 'Agent-S',
  tagline: '桌面GUI自动化Agent，2.8k stars',
  summary: 'Agent-S 是一个桌面GUI自动化Agent，能够通过视觉理解自动操作桌面应用。支持多模型、 适合桌面自动化、 GUI测试等场景。',
  vendor: 'simonmysun',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/simular-ai/agent-s',
  githubUrl: 'https://github.com/simular-ai/agent-s',
  docsUrl: 'https://github.com/simular-ai/agent-s#readme',
  githubStars: 10488,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '桌面GUI自动化',
  deployment: 'Python Runtime, Desktop',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['桌面自动化', 'GUI测试', '任务自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限桌面场景', '需要桌面环境', '复杂GUI支持有限'],
  benchmark: { successRate: 72, avgDurationMin: 5.5, retries: 2.8 },
  community: { stars: '2.8k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.0, speed: 6.5, flexibility: 7.5, stability: 6.5, docs: 6.5 },
};
