import type { ToolProfile } from '@/lib/tools/types';

export const agentevals: ToolProfile = {
  slug: 'agentevals',
  name: 'AgentEvals',
  tagline: 'Agent 评估工具集',
  summary: 'AgentEvals 是 LangChain 推出的 Agent 评估工具集，提供标准化的评估指标和测试框架，适合评估和优化 Agent 系统性能。',
  vendor: 'LangChain',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['开源', '开发工具', '评估测试', 'LangChain 生态'],
  homepageUrl: 'https://github.com/langchain-ai/agent-evals',
  githubUrl: 'https://github.com/langchain-ai/agent-evals',
  docsUrl: 'https://github.com/langchain-ai/agent-evals',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2024-12-04T16:03:34Z",
  githubStars: 15,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'Agent 评估、测试框架、性能分析',
  deployment: 'Python 包，pip 安装',
  modelSupport: ['模型无关', '支持任意 Agent'],
  connectivity: ['本地评估', 'CI/CD 集成'],
  scenarios: ['Agent 测试', '性能评估', '质量保证', '回归测试'],
  gfwStatus: '直连可用',
  pitfalls: ['功能相对基础', '需自行设计评估指标'],
  benchmark: { successRate: 80, avgDurationMin: 5.0, retries: 1.3 },
  community: { stars: '0.8k', release: 'v0.2.0', trend: '稳定维护' },
  rating: { security: 8.0, speed: 7.5, flexibility: 7.5, stability: 7.8, docs: 7.2 },
};
