import type { ToolProfile } from '@/lib/tools/types';

export const agentLlm: ToolProfile = {
  slug: 'agent-llm',
  name: 'Agent-LLM',
  tagline: '多模型支持的 Agent 框架',
  summary: 'Agent-LLM 是一款支持多模型的 Agent 框架，提供插件系统、工具调用、任务编排能力，适合构建灵活的 AI 应用。',
  vendor: 'Josh-XT',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['Agent 协作', '开源', '多模态', '开发工具', '任务自动化'],
  homepageUrl: null,
  githubUrl: 'https://github.com/Josh-XT/Agent-LLM',
  docsUrl: null,
  githubStars: 4800,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'MIT',
  focus: '多模型支持、插件系统、任务编排',
  deployment: 'Docker 部署，支持本地运行',
  modelSupport: ['GPT-4', 'Claude', 'Gemini', 'Llama', '支持 40+ 模型'],
  connectivity: ['REST API', '插件系统', 'Web 界面'],
  scenarios: ['任务自动化', '智能客服', '数据分析', '内容生成'],
  gfwStatus: '需要代理',
  pitfalls: ['配置复杂度较高', '部分模型需代理访问'],
  benchmark: { successRate: 74, avgDurationMin: 7.0, retries: 1.8 },
  community: { stars: '4.8k', release: 'v3.5.0', trend: '稳定维护' },
  rating: { security: 7.5, speed: 7.2, flexibility: 8.5, stability: 7.2, docs: 6.8 },
};
