import type { ToolProfile } from '@/lib/tools/types';

export const agentgpt: ToolProfile = {
  slug: 'agentgpt',
  name: 'AgentGPT',
  tagline: '浏览器中的自主 AI Agent 平台',
  summary: 'AgentGPT 是一款在浏览器中运行的自主 AI Agent 平台，用户可以配置 AI 目标，Agent 自动拆解任务并执行，适合快速验证 Agent 能力。',
  vendor: 'Reworkd',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['Agent 协作', '任务自动化', '开源', '浏览器应用', '个人助手'],
  homepageUrl: 'https://agentgpt.reworkd.ai',
  githubUrl: 'https://github.com/reworkd/AgentGPT',
  docsUrl: 'https://docs.reworkd.ai',
  githubStars: 35868,
  primaryLanguage: "TypeScript",
  pricing: '免费开源，云服务付费',
  license: 'GPL-3.0',
  focus: '目标驱动任务拆解、自主执行、浏览器交互',
  deployment: 'Web 应用，支持自部署',
  modelSupport: ['GPT-4', 'GPT-3.5', '支持自定义模型'],
  connectivity: ['REST API', 'WebSocket', '浏览器扩展'],
  scenarios: ['任务自动化', '信息搜集', '数据分析', '报告生成'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖 OpenAI API 需代理访问', '复杂任务执行稳定性待提升'],
  benchmark: { successRate: 72, avgDurationMin: 8.5, retries: 2.1 },
  community: { stars: '32.1k', release: 'v2.5.0', trend: '活跃增长' },
  rating: { security: 7.2, speed: 7.0, flexibility: 8.5, stability: 6.8, docs: 7.8 },
};
