import type { ToolProfile } from '@/lib/tools/types';

export const agentscope: ToolProfile = {
  slug: 'agentscope',
  name: 'AgentScope',
  tagline: '阿里开源的多 Agent 协作平台',
  summary: 'AgentScope 是阿里巴巴推出的开源多 Agent 协作平台，提供可视化编排、多模型支持、分布式执行能力，适合企业级 Agent 应用开发。',
  vendor: '阿里巴巴 ModelScope',
  sourceType: '开源',
  region: '国内',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '企业流程', '多模态', '可视化编排'],
  homepageUrl: 'https://modelscope.cn',
  githubUrl: 'https://github.com/modelscope/agentscope',
  docsUrl: 'https://agentscope.io',
  githubStars: 18398,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '多 Agent 编排、可视化开发、分布式执行',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['通义千问', 'GPT-4', 'Claude', '支持 ModelScope 模型'],
  connectivity: ['REST API', 'gRPC', '消息队列'],
  scenarios: ['企业流程自动化', '智能客服', '数据分析', '多模态交互'],
  gfwStatus: '直连可用',
  pitfalls: ['部分功能依赖阿里生态', '国际化文档待完善'],
  benchmark: { successRate: 78, avgDurationMin: 7.5, retries: 1.6 },
  community: { stars: '6.8k', release: 'v0.10.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.6, flexibility: 8.2, stability: 7.8, docs: 7.4 },
};
