import type { ToolProfile } from '@/lib/tools/types';

export const agenttuning: ToolProfile = {
  slug: 'agenttuning',
  name: 'AgentTuning',
  tagline: 'Agent 微调优化工具',
  summary: 'AgentTuning 是清华大学推出的 Agent 微调工具，提供自动化的模型微调和优化能力，适合需要定制化 Agent 行为的场景。',
  vendor: 'THUDM',
  sourceType: '开源',
  region: '国内',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '模型微调', '开发工具', '研究'],
  homepageUrl: null,
  githubUrl: 'https://github.com/THUDM/AgentTuning',
  docsUrl: null,
  githubStars: 1484,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Agent 微调、行为优化、定制化',
  deployment: 'Python 包，pip 安装',
  modelSupport: ['GLM', 'Llama', '支持主流开源模型'],
  connectivity: ['本地训练', 'PyTorch 集成'],
  scenarios: ['Agent 行为定制', '研究实验', '垂直领域优化'],
  gfwStatus: '直连可用',
  pitfalls: ['需要 ML 知识', '训练资源消耗大'],
  benchmark: { successRate: 75, avgDurationMin: 30.0, retries: 1.5 },
  community: { stars: '1.5k', release: 'v0.2.0', trend: '稳定维护' },
  rating: { security: 7.8, speed: 6.5, flexibility: 8.0, stability: 7.2, docs: 7.0 },
};
