import type { ToolProfile } from '@/lib/tools/types';

export const agentsflex: ToolProfile = {
  slug: 'agentsflex',
  name: 'AgentsFlex',
  tagline: 'Java 生态的 Agent 开发框架',
  summary: 'AgentsFlex 是一款面向 Java 开发者的 Agent 开发框架，提供类似 LangChain 的能力但使用 Java 编写，适合 Java 企业集成 AI 能力。',
  vendor: 'AgentsFlex 团队',
  sourceType: '开源',
  region: '国内',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', 'Java', '企业流程', '开发工具'],
  homepageUrl: 'https://agentsflex.com',
  githubUrl: 'https://github.com/agents-flex/agents-flex',
  docsUrl: 'https://agentsflex.com/docs',
  githubStars: 1335,
  primaryLanguage: "Java",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Java Agent 开发、企业集成、工作流编排',
  deployment: 'Maven 依赖，Java 应用集成',
  modelSupport: ['GPT-4', 'Claude', '支持国内大模型'],
  connectivity: ['REST API', 'Java 原生接口', 'Spring 集成'],
  scenarios: ['Java 企业应用', '工作流自动化', '智能客服', '业务集成'],
  gfwStatus: '直连可用',
  pitfalls: ['社区规模较小', '文档以中文为主'],
  benchmark: { successRate: 75, avgDurationMin: 6.5, retries: 1.6 },
  community: { stars: '1.2k', release: 'v0.8.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.5, flexibility: 7.8, stability: 7.6, docs: 7.2 },
};
