import type { ToolProfile } from '@/lib/tools/types';

export const agently: ToolProfile = {
  slug: 'agently',
  name: 'Agently',
  tagline: '轻量级 Agent 应用开发框架',
  summary: 'Agently 是一款轻量级的 Agent 应用开发框架，提供模块化设计和插件系统，适合快速构建定制化的 AI 应用。',
  vendor: 'Maplemx',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '开发工具', '轻量级'],
  homepageUrl: null,
  githubUrl: 'https://github.com/Maplemx/Agently',
  docsUrl: null,
  githubStars: 1,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '模块化设计、插件系统、快速开发',
  deployment: 'Python 包，pip 安装',
  modelSupport: ['GPT-4', '支持多种模型'],
  connectivity: ['REST API', '插件接口'],
  scenarios: ['Agent 应用开发', '原型验证', '定制 AI 助手'],
  gfwStatus: '直连可用',
  pitfalls: ['社区规模小', '文档不完善'],
  benchmark: { successRate: 70, avgDurationMin: 5.5, retries: 1.8 },
  community: { stars: '1.2k', release: 'v0.5.0', trend: '缓慢增长' },
  rating: { security: 7.2, speed: 7.4, flexibility: 7.8, stability: 6.8, docs: 6.0 },
};
