import type { ToolProfile } from '@/lib/tools/types';

export const agentsThudm: ToolProfile = {
  slug: 'agents-thudm',
  name: 'Agents',
  tagline: '清华开源的 Agent 开发框架',
  summary: 'Agents 是清华大学开源的 Agent 开发框架，提供简洁的 API 和模块化设计，适合快速构建单 Agent 和多 Agent 应用。',
  vendor: 'THUDM',
  sourceType: '开源',
  region: '国内',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '开发工具', '多模态'],
  homepageUrl: 'https://agents.thudm.ai',
  githubUrl: null,
  docsUrl: 'https://docs.agents.thudm.ai',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Agent 开发、模块化设计、多 Agent 协作',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GLM', 'GPT-4', '支持多种模型'],
  connectivity: ['REST API', '本地调用'],
  scenarios: ['Agent 开发', '教学演示', '原型验证', '研究实验'],
  gfwStatus: '直连可用',
  pitfalls: ['社区规模较小', '文档以中文为主'],
  benchmark: { successRate: 76, avgDurationMin: 5.5, retries: 1.5 },
  community: { stars: '3.2k', release: 'v0.3.0', trend: '稳定维护' },
  rating: { security: 7.8, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 7.4 },
};
