import type { ToolProfile } from '@/lib/tools/types';

export const agentverse: ToolProfile = {
  slug: 'agentverse',
  name: 'AgentVerse',
  tagline: '多 Agent 协作与仿真平台',
  summary: 'AgentVerse 是一款多 Agent 协作与仿真平台，支持 Agent 组队、任务分配、环境仿真，适合研究和开发多 Agent 系统。',
  vendor: 'OpenBMB',
  sourceType: '开源',
  region: '国内',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '多模态', '开发工具', '研究'],
  homepageUrl: null,
  githubUrl: 'https://github.com/openbmb/agentverse',
  docsUrl: null,
  githubStars: 4971,
  primaryLanguage: "JavaScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '多 Agent 组队、任务仿真、环境模拟',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'Claude', '支持多种模型'],
  connectivity: ['本地仿真环境', 'REST API'],
  scenarios: ['多 Agent 研究', '任务仿真', '游戏 AI', '社会模拟'],
  gfwStatus: '直连可用',
  pitfalls: ['研究导向功能较学术', '生产应用需工程化'],
  benchmark: { successRate: 73, avgDurationMin: 7.5, retries: 1.8 },
  community: { stars: '4.5k', release: 'v0.11.0', trend: '稳定维护' },
  rating: { security: 7.5, speed: 7.0, flexibility: 8.0, stability: 7.2, docs: 7.0 },
};
