import type { ToolProfile } from '@/lib/tools/types';

export const aider: ToolProfile = {
  slug: 'aider',
  name: 'Aider',
  tagline: 'AI配对编程，30.5k stars',
  summary: 'Aider 是一个终端AI配对编程工具，能够通过命令行与AI进行交互式编程。支持多模型、Git集成、代码重构、调试等功能，适合代码生成、重构、调试等场景。',
  vendor: 'Paul Gauthier',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://aider.chat',
  githubUrl: 'https://github.com/paul-gauthier/aider',
  docsUrl: 'https://aider.chat/docs',
  githubStars: 42243,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '终端AI配对编程',
  deployment: 'Python Runtime, 命令行',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码生成', '代码重构', '调试', 'Git集成'],
  gfwStatus: '需要代理',
  pitfalls: ['需要终端环境', '学习曲线', '依赖模型能力'],
  benchmark: { successRate: 82, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '30.5k', release: 'v0.60.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 9.0 },
};
