import type { ToolProfile } from '@/lib/tools/types';

export const andi: ToolProfile = {
  slug: 'andi',
  name: 'Andi',
  tagline: '下一代 AI 搜索引擎',
  summary: 'Andi 是一款下一代 AI 搜索引擎，提供可视化搜索结果、智能总结、无广告搜索体验，适合追求高效搜索的用户。',
  vendor: 'Andi Search',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI 搜索', '信息搜集', '商业软件', '个人助手'],
  homepageUrl: 'https://andi.so',
  githubUrl: null,
  docsUrl: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费',
  license: '商业许可',
  focus: '可视化搜索、智能总结、无广告',
  deployment: 'Web 应用 + 浏览器扩展',
  modelSupport: ['GPT-4', '自研模型'],
  connectivity: ['Web 界面', '浏览器扩展'],
  scenarios: ['日常搜索', '信息搜集', '研究学习'],
  gfwStatus: '需要代理',
  pitfalls: ['功能相对简单', '搜索结果依赖外部源'],
  benchmark: { successRate: 80, avgDurationMin: 4.0, retries: 1.5 },
  community: { stars: null, release: '持续更新', trend: '稳定维护' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 8.0, docs: 7.0 },
};
