import type { ToolProfile } from '@/lib/tools/types';

export const anthropicComputerUse: ToolProfile = {
  slug: 'anthropic-computer-use',
  name: 'Anthropic Computer Use',
  tagline: '模型原生桌面操作能力',
  summary: '交互能力强，适合复杂 GUI 自动化原型验证。',
  vendor: 'Anthropic',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面控制', '闭源', '云服务', '运营自动化', '企业流程'],
  homepageUrl: 'https://www.anthropic.com',
  githubUrl: null,
  docsUrl: 'https://docs.anthropic.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按 API 计费',
  license: '商业闭源',
  focus: '视觉理解、界面操作、跨应用流程',
  deployment: '主要依赖云端能力，私有化路径受限。',
  modelSupport: ['Claude 3.5', 'Claude Sonnet 系列'],
  connectivity: ['Anthropic API', '云端推理'],
  scenarios: ['GUI 自动化', '客服流程自动化', '跨应用表单处理'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 88, avgDurationMin: 6.9, retries: 1.2 },
  community: { stars: '官方能力集成', release: '2026-Q1 更新', trend: '企业试点增长快' },
  rating: { security: 8.4, speed: 8.9, flexibility: 8.1, stability: 8.2, docs: 8.0 },
};
