import type { ToolProfile } from '@/lib/tools/types';

export const anythingllm: ToolProfile = {
  slug: 'anythingllm',
  name: 'AnythingLLM',
  tagline: '全功能的 AI 知识库管理平台',
  summary: 'AnythingLLM 是一款全功能的 AI 知识库管理平台，支持多模型、RAG、用户管理，适合构建企业级知识问答系统。',
  vendor: 'Mintplex Labs',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['RAG', '开源', '知识库', '企业流程', '多模态'],
  homepageUrl: 'https://anythingllm.com',
  githubUrl: 'https://github.com/Mintplex-Labs/anything-llm',
  docsUrl: 'https://docs.anythingllm.com',
  lastReleaseDate: "2026-03-18T16:57:50Z",
  latestVersion: "v1.11.2",
  lastCommitDate: "2026-03-21T04:02:30Z",
  githubStars: 56616,
  primaryLanguage: "JavaScript",
  pricing: '免费开源，云服务付费',
  license: 'MIT',
  focus: '知识库管理、RAG、多用户协作',
  deployment: 'Docker 部署，支持桌面应用',
  modelSupport: ['GPT-4', 'Claude', 'Llama', '支持 50+ 模型'],
  connectivity: ['REST API', '向量数据库', '文档存储'],
  scenarios: ['企业知识库', '团队文档问答', '智能客服', '培训系统'],
  gfwStatus: '直连可用',
  pitfalls: ['大规模部署需优化', '向量数据库需单独配置'],
  benchmark: { successRate: 82, avgDurationMin: 4.5, retries: 1.4 },
  community: { stars: '28.5k', release: 'v1.6.0', trend: '快速增长' },
  rating: { security: 8.2, speed: 7.8, flexibility: 8.8, stability: 8.0, docs: 8.2 },
};
