import type { ToolProfile } from '@/lib/tools/types';

export const arcSearch: ToolProfile = {
  slug: 'arc-search',
  name: 'Arc Search',
  tagline: 'Arc 浏览器的 AI 搜索功能',
  summary: 'Arc Search 是 Arc 浏览器内置的 AI 搜索功能，提供智能搜索、网页总结、个性化推荐能力，适合追求浏览体验的用户。',
  vendor: 'The Browser Company',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI 搜索', '浏览器集成', '商业软件', '个人助手'],
  homepageUrl: 'https://arc.net/search',
  githubUrl: null,
  docsUrl: null,
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费',
  license: '商业许可',
  focus: '智能搜索、网页总结、个性化',
  deployment: 'Arc 浏览器内置',
  modelSupport: ['自研模型'],
  connectivity: ['浏览器内置'],
  scenarios: ['日常搜索', '网页阅读', '信息搜集'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限 Arc 浏览器', '功能相对基础'],
  benchmark: { successRate: 82, avgDurationMin: 3.8, retries: 1.4 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.5, flexibility: 7.8, stability: 8.5, docs: 7.5 },
};
