import type { ToolProfile } from '@/lib/tools/types';

export const askcodi: ToolProfile = {
  slug: 'askcodi',
  name: 'AskCodi',
  tagline: '代码问答 AI 助手',
  summary: 'AskCodi 是一款代码问答 AI 助手，支持自然语言提问生成代码片段，提供代码解释、调试建议能力。',
  vendor: 'AskCodi',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '代码问答', '商业软件', '开发工具', '多语言'],
  homepageUrl: 'https://askcodi.com',
  githubUrl: null,
  docsUrl: 'https://docs.askcodi.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业许可',
  focus: '代码问答、代码生成、调试建议',
  deployment: 'VS Code/JetBrains 插件 + Web',
  modelSupport: ['GPT-4', '自研代码模型'],
  connectivity: ['IDE 插件', 'Web 界面'],
  scenarios: ['代码查询', '学习编程', '快速开发', '问题解决'],
  gfwStatus: '需要代理',
  pitfalls: ['答案需人工验证', '复杂问题支持有限'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: null, release: '持续更新', trend: '稳定维护' },
  rating: { security: 8.0, speed: 8.2, flexibility: 8.0, stability: 8.0, docs: 7.8 },
};
