import type { ToolProfile } from '@/lib/tools/types';

export const automationAnywhere: ToolProfile = {
  slug: 'automation-anywhere',
  name: 'Automation Anywhere',
  tagline: '智能自动化平台领导者',
  summary: 'Automation Anywhere 是一款智能自动化平台，结合 RPA 和 AI 能力，提供云原生架构和 Bot 商店，适合中大型企业自动化需求。',
  vendor: 'Automation Anywhere Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', 'AI', '商业软件', '云原生'],
  homepageUrl: 'https://automationanywhere.com',
  githubUrl: null,
  docsUrl: 'https://docs.automationanywhere.com',
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业定价，按 Bot 数量计费',
  license: '商业许可',
  focus: '智能自动化、云 RPA、Bot 管理',
  deployment: '云原生部署，支持混合云',
  modelSupport: ['自研 AI', 'IQ Bot 智能识别'],
  connectivity: ['企业系统 connector', '云 API', 'Bot 商店'],
  scenarios: ['订单处理', '发票自动化', '数据录入', '客户服务'],
  gfwStatus: '需要代理',
  pitfalls: ['云端依赖度高', '定制开发成本高'],
  benchmark: { successRate: 88, avgDurationMin: 4.0, retries: 1.1 },
  community: { stars: null, release: 'v38.0', trend: '市场主流厂商' },
  rating: { security: 9.2, speed: 8.2, flexibility: 8.8, stability: 9.0, docs: 8.8 },
};
