import type { ToolProfile } from '@/lib/tools/types';

export const autogpt: ToolProfile = {
  slug: 'autogpt',
  name: 'AutoGPT',
  tagline: '自主任务Agent鼻祖，171.0k stars',
  summary: 'AutoGPT 是自主任务Agent的开创性项目，能够自动分解目标、规划任务、执行操作。作为Agent领域的里程碑项目，它推动了整个AI Agent生态系统的发展。',
  vendor: 'Significant Gravitas',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://autogpt.net',
  githubUrl: 'https://github.com/Significant-Gravitas/AutoGPT',
  docsUrl: 'https://docs.agpt.co',
  lastReleaseDate: "2026-03-20T04:00:40Z",
  latestVersion: "autogpt-platform-beta-v0.6.52",
  lastCommitDate: "2026-03-23T10:10:30Z",
  githubStars: 182742,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '自主任务执行Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型', '互联网访问'],
  scenarios: ['任务自动化', '研究助手', '内容生成', '数据分析'],
  gfwStatus: '需要代理',
  pitfalls: ['成本较高', '需要人工引导', '稳定性波动'],
  benchmark: { successRate: 75, avgDurationMin: 5.0, retries: 3.0 },
  community: { stars: '171.0k', release: 'v0.5.0', trend: '稳定' },
  rating: { security: 7.0, speed: 6.5, flexibility: 9.0, stability: 7.0, docs: 8.5 },
};
