import type { ToolProfile } from '@/lib/tools/types';

export const autohotkey: ToolProfile = {
  slug: 'autohotkey',
  name: 'AutoHotkey',
  tagline: 'Windows自动化脚本语言，9.8k stars',
  summary: 'AutoHotkey 是一个Windows自动化脚本语言，能够通过脚本控制鼠标、键盘和窗口。适合桌面自动化、 热键绑定、 任务自动化等场景。',
  vendor: 'AutoHotkey Foundation',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://www.autohotkey.com',
  githubUrl: 'https://github.com/AutoHotkey/AutoHotkey',
  docsUrl: 'https://www.autohotkey.com/docs',
  githubStars: 12109,
  primaryLanguage: "C++",
  pricing: '免费开源',
  license: 'GPL-2.0',
  focus: 'Windows自动化脚本',
  deployment: 'Windows Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['桌面自动化', '热键绑定', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '仅限Windows', '需要脚本知识'],
  benchmark: { successRate: 90, avgDurationMin: 0.2, retries: 1.0 },
  community: { stars: '9.8k', release: 'v2.0.10', trend: '活跃' },
  rating: { security: 7.5, speed: 9.0, flexibility: 8.5, stability: 8.5, docs: 8.5 },
};
