import type { ToolProfile } from '@/lib/tools/types';

export const autoglm: ToolProfile = {
  slug: 'autoglm',
  name: 'AutoGLM',
  tagline: '智谱系多工具自主执行代理',
  summary: '围绕国产模型生态构建的任务执行代理能力。',
  vendor: '智谱 AI',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '闭源', '云服务', '企业流程', '运营自动化'],
  homepageUrl: 'https://www.zhipuai.cn',
  githubUrl: null,
  docsUrl: 'https://open.bigmodel.cn/dev/howuse/agent',
  githubStars: null,
  primaryLanguage: null,
  pricing: 'API 按量计费',
  license: '商业闭源',
  focus: '中文任务自动化、工具调用、业务执行',
  deployment: '云端优先，企业接入通过 API 网关治理。',
  modelSupport: ['GLM-4', 'GLM-4-Plus'],
  connectivity: ['智谱云服务'],
  scenarios: ['企业办公自动化', '客服流程', '数据处理'],
  gfwStatus: '直连可用',
  pitfalls: ['生态成熟度仍在完善', '复杂多 Agent 场景能力边界需验证', '跨平台可移植性较弱'],
  benchmark: { successRate: 78, avgDurationMin: 7.1, retries: 2.0 },
  community: { stars: '官方平台', release: '持续更新', trend: '政企试点增加' },
  rating: { security: 8.1, speed: 8.0, flexibility: 7.6, stability: 7.8, docs: 7.5 },
};
