import type { ToolProfile } from '@/lib/tools/types';

export const autogenStudio: ToolProfile = {
  slug: 'autogen-studio',
  name: 'AutoGen Studio',
  tagline: '微软 AutoGen 的可视化界面',
  summary: 'AutoGen Studio 是微软 AutoGen 项目的可视化界面版本，提供拖拽式 Agent 编排和调试能力，降低多 Agent 系统开发门槛。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '可视化编排', '开发工具', '企业流程'],
  homepageUrl: null,
  githubUrl: 'https://github.com/microsoft/autogen',
  docsUrl: 'https://microsoft.github.io/autogen',
  githubStars: 56016,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '可视化 Agent 编排、调试、部署',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'GPT-3.5', '支持 Azure OpenAI'],
  connectivity: ['REST API', 'WebSocket', '本地界面'],
  scenarios: ['多 Agent 系统开发', '原型验证', '教学演示'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖 AutoGen 核心库', '功能仍在完善中'],
  benchmark: { successRate: 76, avgDurationMin: 6.8, retries: 1.6 },
  community: { stars: '3.2k', release: 'v0.3.0', trend: '稳定增长' },
  rating: { security: 7.8, speed: 7.4, flexibility: 8.2, stability: 7.5, docs: 7.6 },
};
