import type { ToolProfile } from '@/lib/tools/types';

export const autogluon: ToolProfile = {
  slug: 'autogluon',
  name: 'AutoGluon',
  tagline: '亚马逊 AutoML 框架',
  summary: 'AutoGluon 是亚马逊推出的 AutoML 框架，提供自动化模型训练和调优能力，支持表格、文本、图像等多模态数据，适合快速构建 ML 应用。',
  vendor: 'AWS',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['AutoML', '开源', '数据自动化', 'AWS', '机器学习'],
  homepageUrl: 'https://autogluon.aws',
  githubUrl: 'https://github.com/autogluon/autogluon',
  docsUrl: 'https://autogluon.readthedocs.io',
  githubStars: 10129,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'AutoML、模型调优、多模态学习',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['自研 AutoML', '支持主流 ML 框架'],
  connectivity: ['本地训练', 'AWS 集成', 'SageMaker 兼容'],
  scenarios: ['数据科学', '模型训练', '预测分析', '分类回归'],
  gfwStatus: '直连可用',
  pitfalls: ['训练资源消耗大', 'AWS 深度绑定'],
  benchmark: { successRate: 85, avgDurationMin: 15.0, retries: 1.3 },
  community: { stars: '8.5k', release: 'v1.0.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 7.5, flexibility: 8.5, stability: 8.2, docs: 8.0 },
};
