import type { ToolProfile } from '@/lib/tools/types';

export const autogen: ToolProfile = {
  slug: 'autogen',
  name: 'AutoGen',
  tagline: '微软系多 Agent 对话协作框架',
  summary: '通过多角色会话和工具调用驱动复杂任务自动化。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['多角色协作', '工作流编排', '开源', '代码生成', '研发提效'],
  homepageUrl: 'https://github.com/microsoft/autogen',
  githubUrl: 'https://github.com/microsoft/autogen',
  docsUrl: 'https://microsoft.github.io/autogen/',
  githubStars: 56044,
  primaryLanguage: "Python",
  pricing: '开源免费',
  license: 'MIT',
  focus: '多 Agent 会话、任务协作、工具编排',
  deployment: '开发环境接入快，生产需要治理提示词和成本。',
  modelSupport: ['OpenAI', 'Azure OpenAI', 'Anthropic', '本地 LLM'],
  connectivity: ['本地运行', '云 API'],
  scenarios: ['多角色问题求解', '代码审阅自动化', '研究型任务'],
  gfwStatus: '需要代理',
  pitfalls: ['角色设计不当会造成对话冗长', '模型调用成本上升快', '需要严格的终止条件'],
  benchmark: { successRate: 82, avgDurationMin: 8.9, retries: 1.7 },
  community: { stars: '39.8k', release: '0.4.x', trend: '学术与企业用户都在增长' },
  rating: { security: 7.8, speed: 7.6, flexibility: 9.0, stability: 7.8, docs: 8.0 },
};
