import type { ToolProfile } from '@/lib/tools/types';

export const awesomeOpenclaw: ToolProfile = {
  slug: 'awesome-openclaw',
  name: 'Awesome OpenClaw',
  tagline: 'OpenClaw 资源精选列表',
  summary: 'Awesome OpenClaw 是一个精心策划的 OpenClaw 资源列表，包含工具、技能、教程和文章。OpenClaw（原名 Moltbot / Clawdbot）是一个开源自托管 AI 代理，支持 WhatsApp、Telegram、Discord 等 50+ 集成平台。',
  vendor: 'SamurAIGPT',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '社区生态', '开发工具', '文档工具', 'AI', '研究'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/SamurAIGPT/awesome-openclaw',
  docsUrl: 'https://github.com/SamurAIGPT/awesome-openclaw#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-03-22T03:41:53Z",
  githubStars: 817,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '资源聚合、工具推荐、教程指南、社区项目',
  deployment: 'GitHub 仓库，可在线浏览',
  modelSupport: ['OpenClaw', '多平台集成'],
  connectivity: ['GitHub 集成', '社区贡献', '持续更新'],
  scenarios: ['资源发现', '学习参考', '工具选型', '社区贡献'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 GitHub 账户', '内容持续更新需关注'],
  benchmark: { successRate: 95, avgDurationMin: 1.0, retries: 1.0 },
  community: { stars: '817', release: 'v1.0.0', trend: '活跃维护' },
  rating: { security: 8.5, speed: 8.0, flexibility: 9.0, stability: 9.0, docs: 8.5 },
};
