import type { ToolProfile } from '@/lib/tools/types';

export const azureclaw: ToolProfile = {
  slug: 'azureclaw',
  name: 'Azure AI Claw',
  tagline: 'Microsoft Azure 云上 Claw 服务',
  summary: '企业级 SLA 保障的 Azure OpenClaw 云服务。',
  vendor: 'Microsoft',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://azureclaw.azure.com',
  githubUrl: null,
  docsUrl: 'https://docs.microsoft.com/azureclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按使用计费',
  license: '商业闭源',
  focus: '企业级 SLA 保障、Azure 生态集成、企业 Agent 平台',
  deployment: 'Azure 托管',
  modelSupport: ['GPT-4o', 'Claude', 'Llama', 'Azure OpenAI'],
  connectivity: ['Azure 服务', 'API 访问', 'Microsoft 365 集成'],
  scenarios: ['企业流程自动化', 'Microsoft 生态集成', '合规场景'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 86, avgDurationMin: 5.5, retries: 1.2 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业试点增长快' },
  rating: { security: 9.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};
