import type { ToolProfile } from '@/lib/tools/types';

export const babyagi: ToolProfile = {
  slug: 'babyagi',
  name: 'BabyAGI',
  tagline: '任务驱动Agent，21.3k stars',
  summary: 'BabyAGI 是一个任务驱动的自主Agent，能够根据目标自动生成、执行和管理工作任务。作为早期Agent项目，它展示了AI自主任务执行的可能性。',
  vendor: 'Yohei Nakajima',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://github.com/yoheinakajima/babyagi',
  githubUrl: 'https://github.com/yoheinakajima/babyagi',
  docsUrl: 'https://github.com/yoheinakajima/babyagi#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-01-31T05:05:45Z",
  githubStars: 22206,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '任务驱动自主Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['任务自动化', '研究助手', '内容生成', '项目管理'],
  gfwStatus: '需要代理',
  pitfalls: ['成本较高', '需要人工引导', '稳定性波动'],
  benchmark: { successRate: 75, avgDurationMin: 4.5, retries: 2.5 },
  community: { stars: '21.3k', release: 'v0.0.1', trend: '稳定' },
  rating: { security: 7.0, speed: 7.0, flexibility: 8.5, stability: 7.0, docs: 7.5 },
};
