import type { ToolProfile } from '@/lib/tools/types';

export const baichuanclaw: ToolProfile = {
  slug: 'baichuanclaw',
  name: 'BaichuanClaw',
  tagline: '百川智能企业助手 Claw 服务',
  summary: '基于百川大模型、中文优化的 OpenClaw 云服务。',
  vendor: '百川智能',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://baichuanclaw.baichuan-ai.com',
  githubUrl: null,
  docsUrl: 'https://platform.baichuan-ai.com/docs/baichuanclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: 'API 计费',
  license: '商业闭源',
  focus: '百川大模型、中文优化、企业助手',
  deployment: '百川云托管',
  modelSupport: ['Baichuan 系列', '百川大模型'],
  connectivity: ['百川云服务', 'API 访问'],
  scenarios: ['中文业务流程', '企业问答', '自动化助手'],
  gfwStatus: '直连可用',
  pitfalls: ['生态成熟度仍在完善', '复杂多 Agent 场景能力边界需验证', '跨平台可移植性较弱'],
  benchmark: { successRate: 80, avgDurationMin: 6.8, retries: 1.7 },
  community: { stars: '官方服务', release: '持续更新', trend: '中文场景采用增长' },
  rating: { security: 7.8, speed: 8.0, flexibility: 7.2, stability: 7.5, docs: 7.0 },
};
