import type { ToolProfile } from '@/lib/tools/types';

export const baiduComateAgent: ToolProfile = {
  slug: 'baidu-comate-agent',
  name: 'Baidu Comate Agent',
  tagline: '百度系研发智能体与企业开发助手',
  summary: '偏研发协同与企业开发流程增强。',
  vendor: '百度',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '闭源', '云服务', '研发提效', '企业流程'],
  homepageUrl: 'https://comate.baidu.com',
  githubUrl: null,
  docsUrl: 'https://comate.baidu.com/zh/help',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业订阅',
  license: '商业闭源',
  focus: '代码生成、研发提效、流程接入',
  deployment: 'SaaS 为主，企业版支持定制化部署。',
  modelSupport: ['文心大模型', '企业私有模型'],
  connectivity: ['云服务', '企业内网接入'],
  scenarios: ['代码补全', '研发规范检查', '知识库问答'],
  gfwStatus: '直连可用',
  pitfalls: ['通用 Agent 能力不如专注框架', '平台锁定风险', '跨云迁移成本偏高'],
  benchmark: { successRate: 76, avgDurationMin: 6.5, retries: 2.2 },
  community: { stars: '商业产品', release: '月更', trend: '企业客户增长稳定' },
  rating: { security: 8.3, speed: 8.1, flexibility: 7.1, stability: 8.4, docs: 7.4 },
};
