import type { ToolProfile } from '@/lib/tools/types';

export const bardeen: ToolProfile = {
  slug: 'bardeen',
  name: 'Bardeen',
  tagline: '浏览器端的 AI 自动化助手',
  summary: 'Bardeen 是一款运行在浏览器端的 AI 自动化工具，提供网页数据提取、跨应用集成能力，适合个人和团队快速构建浏览器自动化流程。',
  vendor: 'Bardeen AI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '浏览器自动化', 'AI', '商业软件', '数据提取'],
  homepageUrl: 'https://bardeen.ai',
  githubUrl: null,
  docsUrl: 'https://docs.bardeen.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Pro $10/月',
  license: '商业许可',
  focus: '浏览器自动化、数据提取、AI 辅助',
  deployment: '浏览器扩展，云同步',
  modelSupport: ['自研 AI', '支持集成 LLM'],
  connectivity: ['浏览器扩展', 'REST API', 'Webhook'],
  scenarios: ['数据采集', 'Lead 生成', '市场调研', '简历筛选'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限浏览器场景', '高级功能需付费'],
  benchmark: { successRate: 83, avgDurationMin: 3.2, retries: 1.4 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.0, speed: 8.2, flexibility: 8.5, stability: 8.0, docs: 7.8 },
};
