import type { ToolProfile } from '@/lib/tools/types';

export const bedrockclaw: ToolProfile = {
  slug: 'bedrockclaw',
  name: 'AWS Bedrock Claw',
  tagline: 'Amazon 托管的 Claw 服务',
  summary: '与 AWS 生态深度集成的 OpenClaw 云服务。',
  vendor: 'Amazon',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://bedrockclaw.aws.amazon.com',
  githubUrl: null,
  docsUrl: 'https://docs.aws.amazon.com/bedrockclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按 Token+推理计费',
  license: '商业闭源',
  focus: 'AWS 生态集成、企业级 SLA 保障、托管服务',
  deployment: 'AWS 托管',
  modelSupport: ['Claude', 'Llama', 'Titan', 'Bedrock 模型'],
  connectivity: ['AWS 服务', 'API 访问', 'VPC 集成'],
  scenarios: ['企业流程自动化', 'AWS 生态集成', '合规场景'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 85, avgDurationMin: 6.0, retries: 1.2 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业试点增长快' },
  rating: { security: 9.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};
