import type { ToolProfile } from '@/lib/tools/types';

export const bito: ToolProfile = {
  slug: 'bito',
  name: 'Bito AI',
  tagline: 'IDE 集成 AI 代码助手',
  summary: 'Bito AI 是一款 IDE 集成的 AI 代码助手，提供代码生成、解释、测试、调试能力，支持多种语言和 IDE。',
  vendor: 'Bito',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', 'IDE 集成', '商业软件', '开发工具', '多语言'],
  homepageUrl: 'https://bito.ai',
  githubUrl: null,
  docsUrl: 'https://docs.bito.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费订阅',
  license: '商业许可',
  focus: '代码生成、解释、测试、调试',
  deployment: 'VS Code/JetBrains 插件',
  modelSupport: ['GPT-4', '多模型支持'],
  connectivity: ['IDE 插件', '本地项目'],
  scenarios: ['日常开发', '代码理解', '测试生成', '调试'],
  gfwStatus: '需要代理',
  pitfalls: ['部分功能需联网', '高级功能需付费'],
  benchmark: { successRate: 84, avgDurationMin: 3.5, retries: 1.4 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.2, speed: 8.2, flexibility: 8.5, stability: 8.2, docs: 8.0 },
};
