import type { ToolProfile } from '@/lib/tools/types';

export const bluePrism: ToolProfile = {
  slug: 'blue-prism',
  name: 'Blue Prism',
  tagline: '企业级 RPA 软件',
  summary: 'Blue Prism 是一款企业级 RPA 软件，以安全性和可扩展性著称，提供可视化流程设计和集中化管理，适合金融、政府等合规要求高的行业。',
  vendor: 'SS&C Technologies',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', '商业软件', '安全合规'],
  homepageUrl: 'https://blueprism.com',
  githubUrl: null,
  docsUrl: 'https://docs.blueprism.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业定价，按用户和 Bot 计费',
  license: '商业许可',
  focus: '企业 RPA、安全合规、集中管理',
  deployment: '企业级部署，支持私有云',
  modelSupport: ['自研 AI', '支持第三方集成'],
  connectivity: ['企业系统 connector', 'API 集成', '数据库连接'],
  scenarios: ['金融流程', '合规审计', '数据处理', '后台自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['价格昂贵', '学习曲线陡峭'],
  benchmark: { successRate: 89, avgDurationMin: 3.8, retries: 1.0 },
  community: { stars: null, release: 'v6.10', trend: '企业市场稳定' },
  rating: { security: 9.8, speed: 8.0, flexibility: 8.2, stability: 9.2, docs: 8.5 },
};
