import type { ToolProfile } from '@/lib/tools/types';

export const braveLeo: ToolProfile = {
  slug: 'brave-leo',
  name: 'Brave Leo',
  tagline: 'Brave 浏览器的 AI 助手',
  summary: 'Brave Leo 是 Brave 浏览器内置的 AI 助手，提供网页总结、对话搜索、隐私保护搜索能力，适合注重隐私的用户。',
  vendor: 'Brave Software',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI 搜索', '浏览器集成', '商业软件', '个人助手', '隐私保护'],
  homepageUrl: 'https://brave.com/leo',
  githubUrl: null,
  docsUrl: 'https://support.brave.com/hc/leo',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/高级版 $15/月',
  license: '商业许可',
  focus: '网页总结、对话搜索、隐私保护',
  deployment: 'Brave 浏览器内置',
  modelSupport: ['Claude', '自研模型'],
  connectivity: ['浏览器内置', '本地处理'],
  scenarios: ['网页阅读', '信息搜集', '隐私搜索', '日常助手'],
  gfwStatus: '需要代理',
  pitfalls: ['需使用 Brave 浏览器', '高级功能需付费'],
  benchmark: { successRate: 84, avgDurationMin: 3.5, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 9.0, speed: 8.5, flexibility: 8.0, stability: 8.8, docs: 8.0 },
};
