import type { ToolProfile } from '@/lib/tools/types';

export const browseruse: ToolProfile = {
  slug: 'browseruse',
  name: 'BrowserUse',
  tagline: 'AI浏览器自动化，52.3k stars',
  summary: 'BrowserUse 是一个AI驱动的浏览器自动化工具，能够通过自然语言指令控制浏览器完成各种任务。支持多模型、多浏览器，适合网页自动化、数据采集、表单填写等场景。',
  vendor: 'BrowserUse',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://browseruse.com',
  githubUrl: 'https://github.com/gregpr07/browser-use',
  docsUrl: 'https://docs.browseruse.com',
  githubStars: 52300,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI浏览器自动化',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', 'Gemini Pro'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['网页自动化', '数据采集', '表单填写', '测试自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限浏览器场景', '无桌面/Shell能力', '需要浏览器驱动'],
  benchmark: { successRate: 85, avgDurationMin: 2.5, retries: 1.8 },
  community: { stars: '52.3k', release: 'v0.1.40', trend: '快速增长' },
  rating: { security: 7.5, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 8.5 },
};
