import type { ToolProfile } from '@/lib/tools/types';

export const camel: ToolProfile = {
  slug: 'camel',
  name: 'Camel',
  tagline: '多 Agent 通信协作框架',
  summary: 'Camel 是一款专注于多 Agent 通信协作的开源框架，提供角色模拟、任务分解、自主对话能力，适合研究多 Agent 交互模式。',
  vendor: 'Camel AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '开发工具', '研究'],
  homepageUrl: 'https://camel-ai.org',
  githubUrl: 'https://github.com/camel-ai/camel',
  docsUrl: 'https://docs.camel-ai.org',
  githubStars: 16458,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '多 Agent 通信、角色模拟、任务协作',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'Claude', '支持多种开源模型'],
  connectivity: ['REST API', '消息队列', '本地通信'],
  scenarios: ['多 Agent 研究', '任务分解', '角色模拟', '对话系统'],
  gfwStatus: '直连可用',
  pitfalls: ['研究导向功能较学术', '生产环境需额外工程化'],
  benchmark: { successRate: 74, avgDurationMin: 8.0, retries: 1.8 },
  community: { stars: '6.8k', release: 'v0.2.0', trend: '稳定增长' },
  rating: { security: 7.5, speed: 7.2, flexibility: 8.2, stability: 7.2, docs: 7.6 },
};
