import type { ToolProfile } from '@/lib/tools/types';

export const characterAI: ToolProfile = {
  slug: 'character-ai',
  name: 'Character.AI',
  tagline: 'AI 角色对话平台',
  summary: 'Character.AI 是一款 AI 角色对话平台，提供海量角色创建和对话能力，支持自定义角色，适合娱乐和教育场景。',
  vendor: 'Character.AI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['对话 AI', '个人助手', '商业软件', '娱乐', '教育'],
  homepageUrl: 'https://character.ai',
  githubUrl: null,
  docsUrl: null,
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费 $10/月',
  license: '商业许可',
  focus: '角色对话、角色创建、娱乐互动',
  deployment: 'Web 应用 + 移动 App',
  modelSupport: ['自研角色模型'],
  connectivity: ['Web 界面', '移动 App'],
  scenarios: ['娱乐对话', '角色扮演', '教育学习', '语言练习'],
  gfwStatus: '需要代理',
  pitfalls: ['内容需审核', '高级功能需付费'],
  benchmark: { successRate: 85, avgDurationMin: 3.0, retries: 1.2 },
  community: { stars: null, release: '持续更新', trend: '快速增长' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.5, stability: 8.5, docs: 7.5 },
};
