import type { ToolProfile } from '@/lib/tools/types';

export const chatgpt: ToolProfile = {
  slug: 'chatgpt',
  name: 'ChatGPT',
  tagline: 'OpenAI 的 AI 助手',
  summary: 'ChatGPT 是 OpenAI 推出的 AI 助手，提供对话、代码生成、文件分析、联网搜索能力，是目前最主流的通用 AI 助手。',
  vendor: 'OpenAI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['对话 AI', '个人助手', '商业软件', '代码生成', '多模态'],
  homepageUrl: 'https://chatgpt.com',
  githubUrl: null,
  docsUrl: 'https://platform.openai.com/docs',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Plus $20/月',
  license: '商业许可',
  focus: '对话 AI、代码生成、文件分析、联网搜索',
  deployment: 'Web 应用 + 移动 App + API',
  modelSupport: ['GPT-4o', 'GPT-4', 'GPT-3.5'],
  connectivity: ['Web 界面', '移动 App', 'REST API'],
  scenarios: ['日常助手', '代码开发', '文档分析', '内容创作'],
  gfwStatus: '需要代理',
  pitfalls: ['需科学上网', '使用限额'],
  benchmark: { successRate: 93, avgDurationMin: 2.8, retries: 1.0 },
  community: { stars: null, release: '持续更新', trend: '市场领导者' },
  rating: { security: 9.0, speed: 9.2, flexibility: 9.5, stability: 9.2, docs: 9.0 },
};
