import type { ToolProfile } from '@/lib/tools/types';

export const claudeAI: ToolProfile = {
  slug: 'claude-ai',
  name: 'Claude.ai',
  tagline: 'Anthropic 的 AI 助手平台',
  summary: 'Claude.ai 是 Anthropic 推出的 AI 助手平台，提供 Claude 模型的对话、文件分析、代码生成能力，注重安全性和有用性的平衡。',
  vendor: 'Anthropic',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['对话 AI', '个人助手', '商业软件', '代码生成', '文件分析'],
  homepageUrl: 'https://claude.ai',
  githubUrl: null,
  docsUrl: 'https://docs.anthropic.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Pro $20/月',
  license: '商业许可',
  focus: '对话 AI、文件分析、代码生成',
  deployment: 'Web 应用 + API',
  modelSupport: ['Claude 3.5', 'Claude 3', 'Claude 2'],
  connectivity: ['Web 界面', 'REST API'],
  scenarios: ['日常助手', '文档分析', '代码生成', '写作辅助'],
  gfwStatus: '需要代理',
  pitfalls: ['需科学上网', '使用次数限制'],
  benchmark: { successRate: 92, avgDurationMin: 3.0, retries: 1.0 },
  community: { stars: null, release: '持续更新', trend: '快速增长' },
  rating: { security: 9.2, speed: 9.0, flexibility: 9.2, stability: 9.0, docs: 8.8 },
};
