import type { ToolProfile } from '@/lib/tools/types';

export const claw0: ToolProfile = {
  slug: 'claw0',
  name: 'Claw0',
  tagline: '从零开始学习 OpenClaw',
  summary: 'Claw0 是一个从零开始构建 Claw-AI 代理的学习项目。提供完整的教程和示例代码，帮助开发者理解 OpenClaw 的核心概念和实现原理。包含会话管理、工作空间配置等实用功能。',
  vendor: 'shareAI-lab',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '教育', '开发工具', 'AI', '研究'],
  homepageUrl: 'https://github.com/shareAI-lab/claw0',
  githubUrl: 'https://github.com/shareAI-lab/claw0',
  docsUrl: 'https://github.com/shareAI-lab/claw0#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-03-18T10:58:44Z",
  githubStars: 1260,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'OpenClaw 学习、从零构建、教程资源、会话管理',
  deployment: '本地部署，支持多语言文档',
  modelSupport: ['OpenClaw', 'Claw-AI Agent'],
  connectivity: ['本地运行', '会话管理', '工作空间配置'],
  scenarios: ['OpenClaw 学习', 'AI 代理构建', '开发教程', '实践项目'],
  gfwStatus: '需要代理',
  pitfalls: ['需要基础编程知识', '学习曲线中等'],
  benchmark: { successRate: 90, avgDurationMin: 5.0, retries: 1.0 },
  community: { stars: '1.2k', release: 'v1.0.0', trend: '活跃开发' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};
