import type { ToolProfile } from '@/lib/tools/types';

export const clawsecure: ToolProfile = {
  slug: 'clawsecure',
  name: 'ClawSecure',
  tagline: 'OpenClaw 安全扫描器与完整性验证',
  summary: 'ClawSecure 是免费的 OpenClaw 安全扫描器，提供 3 层审计协议和 OWASP ASI 10/10 覆盖。已审计 2,890+ 代理，为 2.2M+ 代理提供疫苗保护。作为代理技能和工作流的完整性层，ClawSecure 确保您交互的代理正是他们所声称的身份。',
  vendor: 'ClawSecure',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['安全审计', '开源', '漏洞检测', '合规', '安全', '测试自动化', '质量保障'],
  homepageUrl: 'https://www.clawsecure.ai/',
  githubUrl: 'https://github.com/ClawSecure/clawsecure-openclaw-security',
  docsUrl: 'https://github.com/ClawSecure/clawsecure-openclaw-security#readme',
  githubStars: 17,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: 'OpenClaw 安全扫描、3 层审计协议、代理完整性验证、恶意软件检测',
  deployment: '本地部署，支持云扫描',
  modelSupport: ['OpenClaw', 'AI 代理安全', '完整性验证'],
  connectivity: ['安全扫描 API', 'Registry 集成', 'Marketplace', '24/7 监控'],
  scenarios: ['代理安全扫描', '技能验证', '漏洞检测', '供应链安全审计', '合规检查'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 OpenClaw 知识', '扫描结果需人工分析'],
  benchmark: { successRate: 95, avgDurationMin: 3.0, retries: 1.0 },
  community: { stars: '17', release: 'v1.0.0', trend: '活跃开发' },
  rating: { security: 10.0, speed: 8.5, flexibility: 8.5, stability: 8.5, docs: 8.0 },
};
