import type { ToolProfile } from '@/lib/tools/types';

export const clawdata: ToolProfile = {
  slug: 'clawdata',
  name: 'ClawData',
  tagline: '数据处理和 ETL 流水线 Claw 发行版',
  summary: 'ClawData 是 OpenClaw 的数据处理专用发行版，提供 ETL 流水线、数据清洗、数据同步能力，适合数据工程团队构建自动化数据管道。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['数据自动化', '开源', 'ETL', '数据管道', '企业流程'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawdata',
  docsUrl: 'https://docs.openclaw.ai/clawdata',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'ETL 流水线、数据清洗、数据同步',
  deployment: 'Docker 部署，支持 Airflow 集成',
  modelSupport: ['支持 Pandas AI', '集成 LLM 数据处理'],
  connectivity: ['数据库连接', '对象存储', '消息队列'],
  scenarios: ['数据迁移', '数据清洗', '报表生成', '数据同步'],
  gfwStatus: '直连可用',
  pitfalls: ['大数据量需优化', '需要数据工程知识'],
  benchmark: { successRate: 83, avgDurationMin: 8.0, retries: 1.4 },
  community: { stars: '0.72k', release: 'v0.5.0', trend: '稳定增长' },
  rating: { security: 8.2, speed: 7.8, flexibility: 8.5, stability: 8.0, docs: 7.5 },
};
