import type { ToolProfile } from '@/lib/tools/types';

export const clawwork: ToolProfile = {
  slug: 'clawwork',
  name: 'ClawWork',
  tagline: 'OpenClaw 作为你的 AI 同事',
  summary: 'ClawWork 是 HKUDS 开发的 OpenClaw 应用，将 OpenClaw 作为 AI 同事来协助工作。根据 GitHub 仓库信息，该项目已经获得了 7.5k stars，展示了其在 AI 辅助工作场景中的受欢迎程度。',
  vendor: 'HKUDS',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', 'AI 增强', '工作流自动化'],
  homepageUrl: 'https://github.com/HKUDS/ClawWork',
  githubUrl: 'https://github.com/HKUDS/ClawWork',
  docsUrl: 'https://github.com/HKUDS/ClawWork#readme',
  githubStars: 7517,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI 同事、工作自动化、OpenClaw 应用',
  deployment: '本地部署，支持 Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', 'OpenClaw 模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API'],
  scenarios: ['工作自动化', 'AI 辅助办公', '任务管理', '智能协作'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 OpenClaw 基础', '配置复杂度中等'],
  benchmark: { successRate: 85, avgDurationMin: 4.0, retries: 1.5 },
  community: { stars: '7.5k', release: 'v1.0.0', trend: '快速增长' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.5, stability: 8.0, docs: 7.5 },
};
