import type { ToolProfile } from '@/lib/tools/types';

export const clawjs: ToolProfile = {
  slug: 'clawjs',
  name: 'ClawJS',
  tagline: 'JavaScript/Node.js版，前端/后端通用',
  summary: 'ClawJS 是用 JavaScript/Node.js 实现的 Claw 桌面自动化框架，提供完整的桌面控制能力。支持浏览器环境、Node.js 服务端和客户端，适合全栈应用开发。',
  vendor: 'OpenClaw Community',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', 'JavaScript', 'TypeScript'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: null,
  docsUrl: 'https://docs.openclaw.ai/clawjs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: 'JavaScript桌面自动化框架',
  deployment: 'Node.js Runtime, 浏览器',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地 JS 模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API', '浏览器集成'],
  scenarios: ['全栈应用自动化', '浏览器自动化', 'Node.js 服务端'],
  gfwStatus: '需要代理',
  pitfalls: ['浏览器环境限制', '性能略低于原生', '依赖 Node.js'],
  benchmark: { successRate: 81, avgDurationMin: 3.2, retries: 2.2 },
  community: { stars: '650', release: 'v2.0.0', trend: '活跃' },
  rating: { security: 7.2, speed: 7.8, flexibility: 8.5, stability: 7.5, docs: 8.0 },
};
