import type { ToolProfile } from '@/lib/tools/types';

export const clawops: ToolProfile = {
  slug: 'clawops',
  name: 'ClawOps',
  tagline: '运维自动化的 Claw 发行版',
  summary: 'ClawOps 是 OpenClaw 的运维专用发行版，集成常用运维工具和监控能力，适合 DevOps 团队构建自动化运维体系。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['Shell 执行', '开源', '运维自动化', 'DevOps', '监控'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawops',
  docsUrl: 'https://docs.openclaw.ai/clawops',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '运维自动化、监控告警、CI/CD 集成',
  deployment: 'Docker 部署，支持 Ansible 集成',
  modelSupport: ['GPT-4', 'Claude', '支持本地模型'],
  connectivity: ['SSH', 'Kubernetes API', 'Prometheus', 'Grafana'],
  scenarios: ['运维自动化', '故障排查', '资源管理', '安全审计'],
  gfwStatus: '需要代理',
  pitfalls: ['需要运维知识', '生产环境需额外加固'],
  benchmark: { successRate: 85, avgDurationMin: 4.5, retries: 1.3 },
  community: { stars: '0.95k', release: 'v0.6.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.5, flexibility: 8.2, stability: 8.5, docs: 7.8 },
};
