import type { ToolProfile } from '@/lib/tools/types';

export const clawqueue: ToolProfile = {
  slug: 'clawqueue',
  name: 'ClawQueue',
  tagline: '异步任务队列服务',
  summary: 'ClawQueue 是 OpenClaw 生态的异步任务队列服务，提供任务调度、优先级管理、重试机制，适合构建高可靠的异步处理系统。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['任务队列', '开源', '异步处理', '分布式', '企业流程'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawqueue',
  docsUrl: 'https://docs.openclaw.ai/clawqueue',
  githubStars: 310,
  primaryLanguage: 'Go',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '任务队列、调度管理、重试机制',
  deployment: 'Docker 部署，支持集群',
  modelSupport: ['队列服务'],
  connectivity: ['Redis', '消息队列', 'REST API'],
  scenarios: ['异步任务', '批量处理', '削峰填谷'],
  gfwStatus: '直连可用',
  pitfalls: ['需配置 Redis', '持久化需额外配置'],
  benchmark: { successRate: 94, avgDurationMin: 0.5, retries: 0.5 },
  community: { stars: '0.31k', release: 'v0.4.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 9.5, flexibility: 8.5, stability: 9.2, docs: 7.5 },
};
