import type { ToolProfile } from '@/lib/tools/types';

export const clawhub: ToolProfile = {
  slug: 'clawhub',
  name: 'ClawHub',
  tagline: 'Claw 插件市场平台',
  summary: 'ClawHub 是 OpenClaw 生态的插件市场平台，提供插件发布、安装、管理能力，支持社区贡献和共享，适合扩展 Claw 功能边界。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['插件平台', '开源', '开发工具', '社区生态'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawhub',
  docsUrl: 'https://docs.openclaw.ai/clawhub',
  lastReleaseDate: "2026-01-07T19:07:32Z",
  latestVersion: "v0.1.0",
  lastCommitDate: "2026-03-23T09:07:13Z",
  githubStars: 6666,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: '插件市场、插件管理、社区共享',
  deployment: 'Web 平台，支持自部署',
  modelSupport: ['插件无关'],
  connectivity: ['REST API', 'CLI 工具', 'Web 界面'],
  scenarios: ['插件分发', '功能扩展', '社区贡献'],
  gfwStatus: '需要代理',
  pitfalls: ['插件质量需审核', '依赖管理需规范'],
  benchmark: { successRate: 88, avgDurationMin: 2.0, retries: 1.1 },
  community: { stars: '0.42k', release: 'v0.5.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 8.5, flexibility: 9.0, stability: 8.2, docs: 7.8 },
};
