import type { ToolProfile } from '@/lib/tools/types';

export const clawmetry: ToolProfile = {
  slug: 'clawmetry',
  name: 'Clawmetry',
  tagline: '实时观测 OpenClaw AI 代理',
  summary: 'Clawmetry 是一个开源、永久免费的实时观测仪表板，专为 OpenClaw AI 代理设计。让您的 OpenClaw 代理生成子代理、消耗令牌、调用工具时，您可以实时了解它们实际在做什么。已有 81k+ 安装，183 GitHub Stars，覆盖 107+ 国家。',
  vendor: 'vivekchand',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '监控', '可观测性', 'OpenTelemetry', '监控告警', '开发者工具'],
  homepageUrl: 'https://clawmetry.com/',
  githubUrl: 'https://github.com/vivekchand/clawmetry',
  docsUrl: 'https://github.com/vivekchand/clawmetry#readme',
  lastReleaseDate: "2026-03-22T22:59:04Z",
  latestVersion: "v0.12.72",
  lastCommitDate: "2026-03-23T09:13:05Z",
  githubStars: 183,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '实时观测、代理监控、OpenTelemetry 集成、成本优化',
  deployment: '本地部署，支持云服务',
  modelSupport: ['OpenClaw', 'Ollama', '多模型支持'],
  connectivity: ['OpenTelemetry', '实时数据流', '云端集成'],
  scenarios: ['代理行为监控', '性能分析', '成本优化', '调试诊断'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 OpenTelemetry 配置', '初次设置需要时间'],
  benchmark: { successRate: 92, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '183', release: 'v0.12.63', trend: '活跃开发' },
  rating: { security: 8.5, speed: 9.0, flexibility: 8.5, stability: 8.5, docs: 8.0 },
};
