import type { ToolProfile } from '@/lib/tools/types';

export const clawapi: ToolProfile = {
  slug: 'clawapi',
  name: 'ClawAPI',
  tagline: 'Claw REST API 网关',
  summary: 'ClawAPI 是 OpenClaw 生态的 REST API 网关，提供统一的 HTTP 接口、认证授权、限流熔断能力，适合企业集成 Claw 服务。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['API 服务', '开源', '网关', '企业流程', 'REST'],
  homepageUrl: 'https://clawapi.app/',
  githubUrl: 'https://github.com/Gogo6969/clawapi',
  docsUrl: 'https://github.com/Gogo6969/clawapi#readme',
  githubStars: 29,
  primaryLanguage: "Swift",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'REST API、认证授权、限流熔断',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['API 网关'],
  connectivity: ['HTTP/HTTPS', 'OAuth2', 'JWT'],
  scenarios: ['API 网关', '服务集成', '企业对接'],
  gfwStatus: '直连可用',
  pitfalls: ['需配置反向代理', '证书管理需自行处理'],
  benchmark: { successRate: 95, avgDurationMin: 0.5, retries: 0.5 },
  community: { stars: '0.29k', release: 'v0.4.0', trend: '稳定增长' },
  rating: { security: 9.0, speed: 9.5, flexibility: 8.5, stability: 9.2, docs: 7.5 },
};
