import type { ToolProfile } from '@/lib/tools/types';

export const clawml: ToolProfile = {
  slug: 'clawml',
  name: 'ClawML',
  tagline: '机器学习流水线 Claw 发行版',
  summary: 'ClawML 是 OpenClaw 的机器学习专用发行版，集成 ML 流水线管理和自动化训练能力，适合数据科学团队构建自动化 ML 流程。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['机器学习', '开源', '数据自动化', 'MLOps', 'Python'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawml',
  docsUrl: 'https://docs.openclaw.ai/clawml',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'ML 流水线、自动训练、模型部署',
  deployment: 'Docker 部署，支持 Jupyter 集成',
  modelSupport: ['PyTorch', 'TensorFlow', 'Scikit-learn'],
  connectivity: ['MLflow', 'Kubernetes', 'S3/OSS'],
  scenarios: ['自动训练', '模型评估', '特征工程', '模型部署'],
  gfwStatus: '直连可用',
  pitfalls: ['需要 ML 知识', '资源消耗较大'],
  benchmark: { successRate: 80, avgDurationMin: 20.0, retries: 1.5 },
  community: { stars: '0.68k', release: 'v0.4.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.5, flexibility: 8.5, stability: 7.8, docs: 7.5 },
};
