import type { ToolProfile } from '@/lib/tools/types';

export const clawsecure: ToolProfile = {
  slug: 'clawsecure',
  name: 'ClawSecure',
  tagline: '安全审计 Claw 发行版',
  summary: 'ClawSecure 是 OpenClaw 的安全专用发行版，提供安全扫描、漏洞检测、合规审计能力，适合安全团队构建自动化安全运维体系。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['安全审计', '开源', '漏洞检测', '合规', '企业流程'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: null,
  docsUrl: 'https://docs.openclaw.ai/clawsecure',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'GPL-3.0',
  focus: '安全扫描、漏洞检测、合规审计',
  deployment: 'Docker 部署，支持本地运行',
  modelSupport: ['威胁检测 AI', '日志分析 LLM'],
  connectivity: ['安全工具集成', 'SIEM 系统', '告警通道'],
  scenarios: ['漏洞扫描', '合规审计', '威胁检测', '事件响应'],
  gfwStatus: '直连可用',
  pitfalls: ['需要安全知识', '误报需人工确认'],
  benchmark: { successRate: 82, avgDurationMin: 15.0, retries: 1.5 },
  community: { stars: '0.52k', release: 'v0.5.0', trend: '稳定增长' },
  rating: { security: 9.5, speed: 7.5, flexibility: 8.0, stability: 8.2, docs: 7.5 },
};
