import type { ToolProfile } from '@/lib/tools/types';

export const clawpro: ToolProfile = {
  slug: 'clawpro',
  name: 'ClawPro',
  tagline: '专业版Claw，企业级功能',
  summary: 'ClawPro 是 OpenClaw 的专业版本，提供企业级功能和支持。包含高级编排能力、分布式部署、监控告警、企业级安全特性，适合大型企业和商业场景。',
  vendor: 'OpenClaw Inc',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '闭源', '云服务', '企业流程'],
  homepageUrl: 'https://clawpro.ai',
  githubUrl: null,
  docsUrl: 'https://docs.clawpro.ai',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业许可',
  focus: '企业级桌面自动化框架',
  deployment: '云服务, 私有云, 混合云',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '企业模型'],
  connectivity: ['云API', '私有部署', '企业系统集成'],
  scenarios: ['企业自动化', '大规模部署', '商业应用'],
  gfwStatus: '需要代理',
  pitfalls: ['商业许可费用', '闭源限制', '依赖云服务'],
  benchmark: { successRate: 88, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: 'N/A', release: '2024-01', trend: '商业增长' },
  rating: { security: 9.0, speed: 8.5, flexibility: 8.0, stability: 9.0, docs: 9.0 },
};
