import type { ToolProfile } from '@/lib/tools/types';

export const clawtrace: ToolProfile = {
  slug: 'clawtrace',
  name: 'ClawTrace',
  tagline: '链路追踪服务',
  summary: 'ClawTrace 是 OpenClaw 生态的链路追踪服务，提供分布式追踪、调用链分析、性能诊断能力，基于 OpenTelemetry 标准。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['链路追踪', '开源', '可观测性', 'OpenTelemetry', '运维自动化'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: null,
  docsUrl: 'https://docs.openclaw.ai/clawtrace',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '分布式追踪、调用链分析、性能诊断',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['追踪服务'],
  connectivity: ['OpenTelemetry', 'Jaeger', 'Zipkin'],
  scenarios: ['性能诊断', '故障定位', '调用链分析'],
  gfwStatus: '直连可用',
  pitfalls: ['侵入性需评估', '数据量需控制'],
  benchmark: { successRate: 92, avgDurationMin: 1.2, retries: 0.6 },
  community: { stars: '0.17k', release: 'v0.2.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 9.0, flexibility: 8.5, stability: 8.8, docs: 7.2 },
};
