import type { ToolProfile } from '@/lib/tools/types';

export const clawsync: ToolProfile = {
  slug: 'clawsync',
  name: 'ClawSync',
  tagline: '状态同步服务',
  summary: 'ClawSync 是 OpenClaw 生态的状态同步服务，提供实时数据同步、冲突解决、离线缓存能力，适合分布式场景的状态一致性保障。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['数据同步', '开源', '分布式', '实时', '企业流程'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 329937,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '实时同步、冲突解决、离线缓存',
  deployment: 'Docker 部署，支持边缘节点',
  modelSupport: ['同步服务'],
  connectivity: ['WebSocket', 'CRDT', 'P2P'],
  scenarios: ['数据同步', '协作编辑', '边缘计算'],
  gfwStatus: '直连可用',
  pitfalls: ['网络要求较高', '冲突策略需配置'],
  benchmark: { successRate: 92, avgDurationMin: 0.8, retries: 0.6 },
  community: { stars: '0.28k', release: 'v0.2.0', trend: '稳定增长' },
  rating: { security: 8.8, speed: 9.2, flexibility: 8.5, stability: 9.0, docs: 7.0 },
};
