import type { ToolProfile } from '@/lib/tools/types';

export const clawjava: ToolProfile = {
  slug: 'clawjava',
  name: 'ClawJava',
  tagline: 'Java企业版Claw，企业级部署',
  summary: 'ClawJava 是用 Java 实现的企业级 Claw 桌面自动化框架，提供完整的桌面控制能力和企业级特性。支持 Spring Boot 集成、分布式部署、高可用架构，适合大型企业应用。',
  vendor: 'OpenClaw Community',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', 'Java'],
  homepageUrl: 'https://clawrunr.io',
  githubUrl: 'https://github.com/jobrunr/javaclaw',
  docsUrl: 'https://docs.clawrunr.io',
  githubStars: 169,
  primaryLanguage: "Java",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Java企业级桌面自动化框架',
  deployment: 'JVM, Spring Boot, Kubernetes',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地 Java 模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API', '企业系统集成'],
  scenarios: ['企业应用自动化', '大型系统集成', '分布式部署'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线较陡', '资源占用较高', '配置复杂'],
  benchmark: { successRate: 80, avgDurationMin: 3.5, retries: 2.5 },
  community: { stars: '580', release: 'v3.0.0', trend: '稳定' },
  rating: { security: 8.5, speed: 7.2, flexibility: 8.0, stability: 9.0, docs: 7.8 },
};
