import type { ToolProfile } from '@/lib/tools/types';

export const clawstudio: ToolProfile = {
  slug: 'clawstudio',
  name: 'ClawStudio',
  tagline: 'Claw 可视化开发 IDE',
  summary: 'ClawStudio 是 OpenClaw 生态的可视化开发 IDE，提供拖拽式流程设计、调试、部署能力，降低 Claw 应用开发门槛。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['可视化编排', '开源', '开发工具', 'IDE', '低代码'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 329926,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '可视化开发、拖拽设计、调试部署',
  deployment: '桌面应用，支持 Web 版',
  modelSupport: ['GPT-4', '支持 AI 辅助开发'],
  connectivity: ['本地项目', 'Git 集成', '云端同步'],
  scenarios: ['流程设计', '应用开发', '教学演示'],
  gfwStatus: '需要代理',
  pitfalls: ['大型项目性能需优化', '学习曲线中等'],
  benchmark: { successRate: 82, avgDurationMin: 4.5, retries: 1.3 },
  community: { stars: '0.65k', release: 'v0.8.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.8, flexibility: 8.8, stability: 7.8, docs: 8.0 },
};
