import type { ToolProfile } from '@/lib/tools/types';

export const clawai: ToolProfile = {
  slug: 'clawai',
  name: 'ClawAI',
  tagline: 'AI 增强的 Claw 发行版',
  summary: 'ClawAI 是 OpenClaw 的 AI 增强发行版，集成多模型支持和 RAG 能力，提供更强大的智能决策和知识库集成功能。',
  vendor: 'OpenClaw 社区',
  sourceType: '部分开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', 'AI 增强', 'RAG', '多模态'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: null,
  docsUrl: 'https://docs.openclaw.ai/clawai',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '基础版免费，企业版付费',
  license: 'Apache-2.0',
  focus: '多模型集成、RAG 知识库、智能决策',
  deployment: 'Docker 部署，支持本地运行',
  modelSupport: ['GPT-4', 'Claude', 'DeepSeek', '通义千问'],
  connectivity: ['向量数据库', 'REST API', '本地知识库'],
  scenarios: ['智能客服', '知识问答', '决策支持', '数据分析'],
  gfwStatus: '需要代理',
  pitfalls: ['部分高级功能闭源', '模型调用成本需控制'],
  benchmark: { successRate: 87, avgDurationMin: 5.0, retries: 1.2 },
  community: { stars: '1.5k', release: 'v1.2.0', trend: '快速增长' },
  rating: { security: 8.2, speed: 8.0, flexibility: 9.0, stability: 8.2, docs: 8.0 },
};
