import type { ToolProfile } from '@/lib/tools/types';

export const clawMonitor: ToolProfile = {
  slug: 'claw-monitor',
  name: 'Claw Monitor',
  tagline: 'OpenClaw 终端监控仪表板',
  summary: 'Claw Monitor 是一个终端仪表板，用于实时监控 OpenClaw 代理、cron 作业、Docker 容器和系统资源。支持 Linux/WSL 和 macOS 系统，提供实时状态显示、历史记录查看和会话管理功能。',
  vendor: 'Dan Wahlin',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['监控', 'CLI 工具', '开源', '运维自动化', '日志服务', '可观测性'],
  homepageUrl: 'https://github.com/DanWahlin/claw-monitor',
  githubUrl: 'https://github.com/DanWahlin/claw-monitor',
  docsUrl: 'https://github.com/DanWahlin/claw-monitor#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-03-13T19:29:38Z",
  githubStars: 68,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'OpenClaw 监控、终端仪表板、实时状态显示、会话管理',
  deployment: '本地部署，支持 Linux/WSL/macOS',
  modelSupport: ['OpenClaw', 'Claude Code', 'Codex', 'Copilot CLI'],
  connectivity: ['本地运行', 'Docker 集成', 'Cron 作业监控', '系统资源监控'],
  scenarios: ['OpenClaw 代理监控', '定时任务管理', 'Docker 容器监控', '系统资源监控'],
  gfwStatus: '需要代理',
  pitfalls: ['仅支持 Linux/WSL/macOS', '需要终端环境'],
  benchmark: { successRate: 88, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '68', release: 'beta', trend: '活跃开发' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 7.5, docs: 7.0 },
};
