import type { ToolProfile } from '@/lib/tools/types';

export const clawgo: ToolProfile = {
  slug: 'clawgo',
  name: 'ClawGo',
  tagline: 'Go语言Claw实现，高性能Agent框架',
  summary: 'ClawGo 是用 Go 语言实现的 Claw 桌面自动化框架，提供高性能、低内存占用的桌面控制能力。适合云原生环境和高并发场景，支持 Docker 和 Kubernetes 部署。',
  vendor: 'OpenClaw Community',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', 'Go'],
  homepageUrl: 'https://github.com/openclaw/clawgo',
  githubUrl: 'https://github.com/openclaw/clawgo',
  docsUrl: 'https://docs.openclaw.org/clawgo',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-01-05T10:44:42Z",
  githubStars: 72,
  primaryLanguage: "Go",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'Go语言桌面自动化框架',
  deployment: 'Docker, Kubernetes, 云原生',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地 Go 模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API'],
  scenarios: ['云原生自动化', '高并发场景', '微服务集成'],
  gfwStatus: '需要代理',
  pitfalls: ['Go 平台支持有限', '文档相对较少', '社区规模较小'],
  benchmark: { successRate: 82, avgDurationMin: 2.8, retries: 2 },
  community: { stars: '920', release: 'v1.1.0', trend: '稳定' },
  rating: { security: 7.8, speed: 9.0, flexibility: 7.5, stability: 8.5, docs: 7.0 },
};
