import type { ToolProfile } from '@/lib/tools/types';

export const clawDashboard: ToolProfile = {
  slug: 'claw-dashboard',
  name: 'Claw Dashboard',
  tagline: 'OpenClaw 实时监控终端仪表板',
  summary: 'Claw Dashboard 是一个美观的实时终端仪表板，用于监控 OpenClaw 实例。灵感来自现代系统监控工具如 btop、htop 和 mactop。提供实时状态监控、插件系统和可配置的 widget 组件。',
  vendor: 'Kevin Smith',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['监控', 'CLI 工具', '开源', '运维自动化', '日志服务', '可观测性'],
  homepageUrl: 'https://github.com/spleck/claw-dashboard',
  githubUrl: 'https://github.com/spleck/claw-dashboard',
  docsUrl: 'https://github.com/spleck/claw-dashboard#readme',
  githubStars: 112,
  primaryLanguage: "JavaScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'OpenClaw 监控、终端仪表板、实时状态显示、插件系统',
  deployment: '本地部署，支持 npm 安装',
  modelSupport: ['OpenClaw', '多实例监控'],
  connectivity: ['本地运行', '插件扩展', 'Widget 配置'],
  scenarios: ['OpenClaw 实例监控', '系统资源监控', '实时状态显示', '多实例管理'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 Node.js 环境', '插件配置需要学习'],
  benchmark: { successRate: 90, avgDurationMin: 2.5, retries: 1.0 },
  community: { stars: '112', release: 'v1.0.0', trend: '活跃开发' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.5, stability: 8.0, docs: 7.5 },
};
