import type { ToolProfile } from '@/lib/tools/types';

export const clawflows: ToolProfile = {
  slug: 'clawflows',
  name: 'ClawFlows',
  tagline: 'Claw 工作流编排引擎',
  summary: 'ClawFlows 是 OpenClaw 生态中的工作流编排引擎，提供可视化流程设计和分布式执行能力，适合复杂业务场景的自动化编排。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['工作流编排', '开源', '可视化编排', '分布式', '企业流程'],
  homepageUrl: 'https://clawflows.com/',
  githubUrl: 'https://github.com/Cluka-399/clawflows-registry',
  docsUrl: 'https://clawflows.com/#automations',
  githubStars: 9,
  primaryLanguage: "HTML",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '工作流编排、可视化设计、分布式执行',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['GPT-4', 'Claude', '支持多模型路由'],
  connectivity: ['REST API', '消息队列', 'WebSocket'],
  scenarios: ['复杂流程编排', '跨系统自动化', '审批流程', '数据管道'],
  gfwStatus: '需要代理',
  pitfalls: ['配置复杂度较高', '分布式部署需运维能力'],
  benchmark: { successRate: 84, avgDurationMin: 6.0, retries: 1.3 },
  community: { stars: '1.2k', release: 'v0.8.0', trend: '稳定增长' },
  rating: { security: 8.2, speed: 8.0, flexibility: 8.8, stability: 8.0, docs: 7.8 },
};
