import type { ToolProfile } from '@/lib/tools/types';

export const clawbridge: ToolProfile = {
  slug: 'clawbridge',
  name: 'ClawBridge',
  tagline: '多 Agent 桥接器',
  summary: 'ClawBridge 是 OpenClaw 生态的多 Agent 桥接器，提供 Agent 间通信、协议转换、服务发现能力，适合构建多 Agent 协作系统。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['Agent 协作', '开源', '连接器', '多模态', '企业流程'],
  homepageUrl: 'https://github.com/dreamwing/clawbridge',
  githubUrl: 'https://github.com/dreamwing/clawbridge',
  docsUrl: 'https://github.com/dreamwing/clawbridge#readme',
  githubStars: 208,
  primaryLanguage: "JavaScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'Agent 互联、协议转换、服务发现',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['多 Agent 协议'],
  connectivity: ['gRPC', 'REST API', '消息队列'],
  scenarios: ['多 Agent 协作', '服务集成', '分布式系统'],
  gfwStatus: '直连可用',
  pitfalls: ['配置复杂度较高', '需要分布式知识'],
  benchmark: { successRate: 88, avgDurationMin: 2.5, retries: 1.2 },
  community: { stars: '0.34k', release: 'v0.3.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 9.0, flexibility: 8.8, stability: 8.5, docs: 7.2 },
};
