import type { ToolProfile } from '@/lib/tools/types';

export const clawcache: ToolProfile = {
  slug: 'clawcache',
  name: 'ClawCache',
  tagline: '结果缓存层服务',
  summary: 'ClawCache 是 OpenClaw 生态的结果缓存层服务，提供智能缓存、过期策略、预热刷新能力，适合提升 Agent 响应速度和降低 API 成本。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['缓存服务', '开源', '性能优化', '分布式', '企业流程'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawcache',
  docsUrl: 'https://docs.openclaw.ai/clawcache',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '智能缓存、过期策略、性能优化',
  deployment: 'Docker 部署，支持集群',
  modelSupport: ['缓存服务'],
  connectivity: ['Redis', '内存缓存', '分布式缓存'],
  scenarios: ['API 缓存', '结果复用', '性能优化'],
  gfwStatus: '直连可用',
  pitfalls: ['缓存策略需调优', '内存管理需注意'],
  benchmark: { successRate: 96, avgDurationMin: 0.2, retries: 0.3 },
  community: { stars: '0.25k', release: 'v0.3.0', trend: '稳定增长' },
  rating: { security: 8.2, speed: 9.8, flexibility: 8.0, stability: 9.0, docs: 7.2 },
};
