import type { ToolProfile } from '@/lib/tools/types';

export const clawbot: ToolProfile = {
  slug: 'clawbot',
  name: 'ClawBot',
  tagline: 'RPA 机器人 Claw 发行版',
  summary: 'ClawBot 是 OpenClaw 的 RPA 专用发行版，提供机器人管理、任务调度、执行监控能力，适合企业构建 RPA 自动化中心。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['RPA', '开源', '机器人', '企业流程', '任务调度'],
  homepageUrl: 'https://github.com/xianyu110/clawbot',
  githubUrl: 'https://github.com/xianyu110/clawbot',
  docsUrl: 'https://github.com/xianyu110/clawbot#readme',
  githubStars: 868,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'RPA 机器人、任务调度、执行监控',
  deployment: 'Docker 部署，支持分布式',
  modelSupport: ['GPT-4', '支持任务理解'],
  connectivity: ['REST API', '消息队列', '机器人节点'],
  scenarios: ['RPA 自动化', '批量任务', '定时调度', '分布式执行'],
  gfwStatus: '需要代理',
  pitfalls: ['分布式部署复杂', '需要运维能力'],
  benchmark: { successRate: 84, avgDurationMin: 5.5, retries: 1.3 },
  community: { stars: '0.38k', release: 'v0.3.0', trend: '稳定增长' },
  rating: { security: 8.2, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 7.2 },
};
