import type { ToolProfile } from '@/lib/tools/types';

export const clawsio: ToolProfile = {
  slug: 'clawsio',
  name: 'Claws.io',
  tagline: '60 秒内部署您的 AI 代理',
  summary: 'Claws.io 是一个快速部署 OpenClaw 代理的云平台。无需 VPS 设置、无需复杂配置、无需 API 密钥管理。支持 340+ 模型，可连接任意消息传递平台。提供分步配置指南，让用户能够快速部署并获得结果。',
  vendor: 'Claws.io',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '部署', 'AI 平台', '低代码', 'API 集成', '开发者工具'],
  homepageUrl: 'https://www.claws.io/',
  githubUrl: null,
  docsUrl: 'https://www.claws.io/support',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费 + 付费套餐',
  license: '专有',
  focus: '快速部署、340+ 模型支持、消息平台集成、配置管理',
  deployment: '云服务，无需本地部署',
  modelSupport: ['OpenClaw 26.3.7', '340+ 模型', '多模型切换'],
  connectivity: ['消息平台集成', 'API 管理', '云端部署'],
  scenarios: ['AI 代理部署', '模型测试', '消息机器人', '自动化助手'],
  gfwStatus: '需要代理',
  pitfalls: ['需要注册账户', '付费功能限制'],
  benchmark: { successRate: 92, avgDurationMin: 1.0, retries: 1.0 },
  community: { stars: null, release: 'v26.3.7', trend: '稳定运营' },
  rating: { security: 8.5, speed: 9.5, flexibility: 8.5, stability: 9.0, docs: 8.0 },
};
