import type { ToolProfile } from '@/lib/tools/types';

export const clawmetrics: ToolProfile = {
  slug: 'clawmetrics',
  name: 'ClawMetrics',
  tagline: '指标采集服务',
  summary: 'ClawMetrics 是 OpenClaw 生态的指标采集服务，提供性能指标、业务指标、自定义指标的采集和展示能力，集成 Prometheus 生态。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['指标监控', '开源', '可观测性', 'Prometheus', '运维自动化'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 330625,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '指标采集、监控展示、告警集成',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['指标服务'],
  connectivity: ['Prometheus', 'Grafana', 'REST API'],
  scenarios: ['性能监控', '业务分析', '容量规划'],
  gfwStatus: '直连可用',
  pitfalls: ['指标设计需规范', '存储需配置'],
  benchmark: { successRate: 94, avgDurationMin: 0.8, retries: 0.5 },
  community: { stars: '0.19k', release: 'v0.2.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 9.2, flexibility: 8.5, stability: 9.0, docs: 7.2 },
};
