import type { ToolProfile } from '@/lib/tools/types';

export const clawlite: ToolProfile = {
  slug: 'clawlite',
  name: 'ClawLite',
  tagline: '超轻量Claw，嵌入式友好',
  summary: 'ClawLite 是 OpenClaw 的超轻量版本，专为嵌入式设备和资源受限环境设计。内存占用极低，适合 IoT 设备、边缘计算和嵌入式系统。',
  vendor: 'OpenClaw Community',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/eobarretooo/ClawLite',
  githubUrl: 'https://github.com/eobarretooo/ClawLite',
  docsUrl: 'https://github.com/eobarretooo/ClawLite#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-03-23T09:04:59Z",
  githubStars: 31,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '超轻量桌面自动化框架',
  deployment: '嵌入式设备, IoT, 边缘计算',
  modelSupport: ['GPT-4o', 'Claude 3.5', '本地 LLM'],
  connectivity: ['本地运行', '边缘网关'],
  scenarios: ['IoT 自动化', '嵌入式系统', '边缘计算'],
  gfwStatus: '需要代理',
  pitfalls: ['功能极度精简', '不支持复杂任务', '扩展性有限'],
  benchmark: { successRate: 75, avgDurationMin: 5.0, retries: 3.0 },
  community: { stars: '380', release: 'v0.2.0', trend: '稳定' },
  rating: { security: 7.5, speed: 8.0, flexibility: 5.5, stability: 7.0, docs: 6.0 },
};
