import type { ToolProfile } from '@/lib/tools/types';

export const clawrs: ToolProfile = {
  slug: 'clawrs',
  name: 'ClawRS',
  tagline: 'Rust语言Claw实现，内存安全Agent',
  summary: 'ClawRS 是用 Rust 语言实现的 Claw 桌面自动化框架，提供内存安全、零成本抽象的桌面控制能力。适合对安全性和性能要求高的场景，支持 Windows、Linux 和 macOS。',
  vendor: 'OpenClaw Community',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', 'Rust'],
  homepageUrl: 'https://github.com/openclaw/clawrs',
  githubUrl: 'https://github.com/openclaw/clawrs',
  docsUrl: 'https://docs.openclaw.org/clawrs',
  githubStars: 780,
  primaryLanguage: 'Rust',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Rust语言桌面自动化框架',
  deployment: '本地部署, Docker, Rust Binary',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地 Rust 模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API'],
  scenarios: ['安全敏感场景', '嵌入式系统', '高性能自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线陡峭', '平台支持有限', '生态相对年轻'],
  benchmark: { successRate: 84, avgDurationMin: 2.5, retries: 1.8 },
  community: { stars: '780', release: 'v0.9.0', trend: '上升' },
  rating: { security: 9.5, speed: 8.8, flexibility: 7.2, stability: 9.0, docs: 6.5 },
};
