import type { ToolProfile } from '@/lib/tools/types';

export const clawops: ToolProfile = {
  slug: 'clawops',
  name: 'ClawOps',
  tagline: 'OpenClaw Made Easy',
  summary: 'ClawOps 是一个让 OpenClaw 变得简单的平台，提供 Pro 和 Launch 两种服务。Pro 版本每月$4.99，提供增强的 OpenClaw 体验。帮助用户轻松实现 60% 的常规任务完成速度提升。',
  vendor: 'HopIT',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', 'OpenClaw 服务', '订阅服务', '任务自动化', 'AI 平台', '低代码'],
  homepageUrl: 'https://clawops.co/',
  githubUrl: null,
  docsUrl: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: 'Pro $4.99/月',
  license: '专有',
  focus: 'OpenClaw 简化、任务自动化、Pro 服务、Launch 平台',
  deployment: '云服务，无需本地部署',
  modelSupport: ['OpenClaw', '多模型支持'],
  connectivity: ['云端 API', 'Portal 集成', 'Pro/Launch 双模式'],
  scenarios: ['常规任务自动化', 'AI 代理部署', '工作流程优化', '企业自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['需要订阅 Pro 服务', '功能依赖云端'],
  benchmark: { successRate: 90, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: null, release: 'v1.0.0', trend: '商业运营' },
  rating: { security: 8.5, speed: 9.0, flexibility: 8.0, stability: 8.5, docs: 7.5 },
};
