import type { ToolProfile } from '@/lib/tools/types';

export const clawcli: ToolProfile = {
  slug: 'clawcli',
  name: 'ClawCLI',
  tagline: 'Claw 命令行工具集',
  summary: 'ClawCLI 是 OpenClaw 生态的命令行工具集，提供项目管理、流程执行、插件安装等能力，适合开发者快速操作 Claw 项目。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['CLI 工具', '开源', '开发工具', '命令行'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 329937,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: '命令行操作、项目管理、快速执行',
  deployment: 'npm 包，支持全局安装',
  modelSupport: ['CLI 工具'],
  connectivity: ['本地文件系统', 'REST API'],
  scenarios: ['项目开发', '流程执行', '批量操作'],
  gfwStatus: '需要代理',
  pitfalls: ['需要命令行基础', '功能相对基础'],
  benchmark: { successRate: 90, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '0.38k', release: 'v0.6.0', trend: '稳定增长' },
  rating: { security: 8.2, speed: 9.0, flexibility: 8.0, stability: 8.5, docs: 7.8 },
};
