import type { ToolProfile } from '@/lib/tools/types';

export const clawcs: ToolProfile = {
  slug: 'clawcs',
  name: 'ClawCS',
  tagline: 'C# 实现的 Claw 框架',
  summary: 'ClawCS 是 OpenClaw 的 C# 语言实现版本，集成.NET 生态，支持 Shell + Desktop 双重控制，适合 C# 开发者和 Windows 企业环境。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', 'C#', '.NET'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 329926,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: '.NET 桌面自动化、Windows 集成、企业应用',
  deployment: 'NuGet 包，支持.NET 6+',
  modelSupport: ['GPT-4', 'Claude', '支持 Azure OpenAI'],
  connectivity: ['.NET API', 'COM 互操作', 'PowerShell 集成'],
  scenarios: ['Windows 办公自动化', '企业应用集成', '测试自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限 Windows 平台', '.NET 生态依赖'],
  benchmark: { successRate: 82, avgDurationMin: 5.5, retries: 1.4 },
  community: { stars: '0.8k', release: 'v0.5.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 8.2, flexibility: 7.8, stability: 8.0, docs: 7.5 },
};
