import type { ToolProfile } from '@/lib/tools/types';

export const clawdocs: ToolProfile = {
  slug: 'clawdocs',
  name: 'ClawDocs',
  tagline: '文档生成服务',
  summary: 'ClawDocs 是 OpenClaw 生态的文档生成服务，提供自动文档生成、版本管理、在线查阅能力，支持 Markdown 和 API 文档自动生成。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['文档工具', '开源', '开发工具', '自动化', '知识管理'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawdocs',
  docsUrl: 'https://docs.openclaw.ai/clawdocs',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '文档生成、版本管理、在线查阅',
  deployment: 'Docker 部署，支持静态托管',
  modelSupport: ['AI 文档生成'],
  connectivity: ['Git 集成', 'REST API', 'Web 界面'],
  scenarios: ['API 文档', '项目文档', '知识库'],
  gfwStatus: '直连可用',
  pitfalls: ['文档结构需规划', '自定义模板需开发'],
  benchmark: { successRate: 90, avgDurationMin: 2.0, retries: 0.8 },
  community: { stars: '0.18k', release: 'v0.3.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.2, stability: 8.5, docs: 8.5 },
};
