import type { ToolProfile } from '@/lib/tools/types';

export const clawmonitor: ToolProfile = {
  slug: 'clawmonitor',
  name: 'ClawMonitor',
  tagline: '系统监控和告警 Claw 发行版',
  summary: 'ClawMonitor 是 OpenClaw 的监控专用发行版，集成 Prometheus、Grafana 等监控工具，提供智能告警和故障诊断能力。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['监控告警', '开源', '运维自动化', 'DevOps', '数据分析'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: null,
  docsUrl: 'https://docs.openclaw.ai/clawmonitor',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '系统监控、智能告警、故障诊断',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['异常检测 AI', '日志分析 LLM'],
  connectivity: ['Prometheus', 'Grafana', '告警通道'],
  scenarios: ['系统监控', '应用监控', '日志分析', '故障诊断'],
  gfwStatus: '直连可用',
  pitfalls: ['监控数据量大', '告警规则需调优'],
  benchmark: { successRate: 85, avgDurationMin: 3.0, retries: 1.2 },
  community: { stars: '0.45k', release: 'v0.4.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.5, flexibility: 8.0, stability: 8.5, docs: 7.5 },
};
