import type { ToolProfile } from '@/lib/tools/types';

export const clawlog: ToolProfile = {
  slug: 'clawlog',
  name: 'ClawLog',
  tagline: '统一日志服务',
  summary: 'ClawLog 是 OpenClaw 生态的统一日志服务，提供日志采集、存储、查询、分析能力，支持结构化日志和链路追踪。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['日志服务', '开源', '可观测性', '企业流程', '运维自动化'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 329926,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '日志采集、存储查询、分析告警',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['日志分析 AI'],
  connectivity: ['Fluentd', 'Elasticsearch', 'Loki'],
  scenarios: ['日志管理', '故障排查', '安全审计'],
  gfwStatus: '直连可用',
  pitfalls: ['日志量大需优化', '存储成本需控制'],
  benchmark: { successRate: 93, avgDurationMin: 1.0, retries: 0.5 },
  community: { stars: '0.22k', release: 'v0.3.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 9.0, flexibility: 8.5, stability: 9.0, docs: 7.5 },
};
