import type { ToolProfile } from '@/lib/tools/types';

export const clawsec: ToolProfile = {
  slug: 'clawsec',
  name: 'ClawSec',
  tagline: 'OpenClaw 安全技能套件',
  summary: 'ClawSec 是 prompt-security 开发的完整安全技能套件，专为 OpenClaw 和 NanoClaw 代理（及其变体）设计。提供漂移检测、实时安全建议、自动化审计和技能完整性验证等安全功能，保护 SOUL.md 等技能文件的安全。',
  vendor: 'Prompt Security',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['安全审计', '开源', '漏洞检测', '桌面控制', 'Shell 执行'],
  homepageUrl: 'https://prompt.security/clawsec',
  githubUrl: 'https://github.com/prompt-security/clawsec',
  docsUrl: 'https://github.com/prompt-security/clawsec#readme',
  lastReleaseDate: "2026-03-10T17:28:38Z",
  latestVersion: "clawsec-scanner-v0.0.2",
  lastCommitDate: "2026-03-23T06:23:27Z",
  githubStars: 827,
  primaryLanguage: "JavaScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: '安全技能套件、漂移检测、自动化审计、技能完整性验证',
  deployment: 'pip 安装，支持 OpenClaw/NanoClaw 集成',
  modelSupport: ['OpenClaw', 'NanoClaw', 'SOUL.md'],
  connectivity: ['CVE 数据库', 'GitHub API', '本地技能文件'],
  scenarios: ['技能安全审计', 'CVE 漏洞检测', '漂移检测', '技能完整性验证'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 OpenClaw/NanoClaw 环境', 'CVE 数据需要定期更新'],
  benchmark: { successRate: 90, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '824', release: 'v1.0.0', trend: '活跃更新' },
  rating: { security: 9.5, speed: 8.5, flexibility: 8.0, stability: 8.5, docs: 8.0 },
};
