import type { ToolProfile } from '@/lib/tools/types';

export const clawsdk: ToolProfile = {
  slug: 'clawsdk',
  name: 'ClawSDK',
  tagline: 'Claw 官方多语言 SDK',
  summary: 'ClawSDK 是 OpenClaw 官方提供的多语言 SDK，支持 TypeScript、Python、Go、Java 等语言，适合开发者集成 Claw 能力到自有应用。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['SDK', '开源', '开发工具', '多语言', 'API 集成'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawsdk',
  docsUrl: 'https://docs.openclaw.ai/clawsdk',
  githubStars: 520,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '多语言 SDK、API 封装、开发支持',
  deployment: '各语言包管理器',
  modelSupport: ['SDK 无关'],
  connectivity: ['REST API', 'gRPC', 'WebSocket'],
  scenarios: ['应用集成', '二次开发', '插件开发'],
  gfwStatus: '需要代理',
  pitfalls: ['各语言版本进度不一', '文档需完善'],
  benchmark: { successRate: 92, avgDurationMin: 1.0, retries: 0.8 },
  community: { stars: '0.52k', release: 'v0.10.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 9.0, flexibility: 9.0, stability: 8.8, docs: 8.0 },
};
