import type { ToolProfile } from '@/lib/tools/types';

export const clawtest: ToolProfile = {
  slug: 'clawtest',
  name: 'ClawTest',
  tagline: '自动化测试 Claw 发行版',
  summary: 'ClawTest 是 OpenClaw 的测试专用发行版，集成测试框架和 CI/CD 工具，提供自动化测试生成和执行能力，适合 QA 团队构建自动化测试体系。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['测试自动化', '开源', 'CI/CD', '开发工具', '质量保障'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 329926,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '自动化测试、测试生成、CI/CD 集成',
  deployment: 'Docker 部署，支持 Jenkins/GitHub Actions',
  modelSupport: ['GPT-4', '支持测试用例生成'],
  connectivity: ['测试框架集成', 'CI/CD API', '代码仓库'],
  scenarios: ['单元测试', 'E2E 测试', '回归测试', '性能测试'],
  gfwStatus: '需要代理',
  pitfalls: ['测试用例需人工审核', '复杂场景覆盖有限'],
  benchmark: { successRate: 78, avgDurationMin: 10.0, retries: 1.6 },
  community: { stars: '0.58k', release: 'v0.3.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.5, flexibility: 8.0, stability: 7.8, docs: 7.2 },
};
