import type { ToolProfile } from '@/lib/tools/types';

export const clawsecrets: ToolProfile = {
  slug: 'clawsecrets',
  name: 'ClawSecrets',
  tagline: '密钥管理服务',
  summary: 'ClawSecrets 是 OpenClaw 生态的密钥管理服务，提供密钥存储、访问控制、自动轮转能力，集成 Vault 等密钥管理方案。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['密钥管理', '开源', '安全', '企业流程', '运维自动化'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/clawsecrets',
  docsUrl: 'https://docs.openclaw.ai/clawsecrets',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '密钥存储、访问控制、自动轮转',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['密钥服务'],
  connectivity: ['Vault', 'KMS', 'REST API'],
  scenarios: ['密钥管理', '凭证存储', '安全合规'],
  gfwStatus: '直连可用',
  pitfalls: ['安全配置需谨慎', '备份策略需完善'],
  benchmark: { successRate: 96, avgDurationMin: 0.2, retries: 0.3 },
  community: { stars: '0.13k', release: 'v0.2.0', trend: '稳定增长' },
  rating: { security: 9.8, speed: 9.2, flexibility: 8.5, stability: 9.2, docs: 7.2 },
};
