import type { ToolProfile } from '@/lib/tools/types';

export const clawconfig: ToolProfile = {
  slug: 'clawconfig',
  name: 'ClawConfig',
  tagline: '配置管理服务',
  summary: 'ClawConfig 是 OpenClaw 生态的配置管理服务，提供多环境配置、动态刷新、灰度发布能力，适合企业级配置管理需求。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['配置管理', '开源', '企业流程', '多环境', '运维自动化'],
  homepageUrl: 'https://github.com/openclaw/openclaw',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://github.com/openclaw/openclaw#readme',
  githubStars: 329937,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '配置管理、动态刷新、灰度发布',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['配置服务'],
  connectivity: ['REST API', 'gRPC', 'Webhook'],
  scenarios: ['配置管理', '环境隔离', '灰度发布'],
  gfwStatus: '直连可用',
  pitfalls: ['配置权限需管理', '版本控制需规范'],
  benchmark: { successRate: 95, avgDurationMin: 0.3, retries: 0.4 },
  community: { stars: '0.15k', release: 'v0.2.0', trend: '稳定增长' },
  rating: { security: 9.0, speed: 9.5, flexibility: 8.8, stability: 9.2, docs: 7.5 },
};
