import type { ToolProfile } from '@/lib/tools/types';

export const clawstudio: ToolProfile = {
  slug: 'clawstudio',
  name: 'Claw Studio',
  tagline: 'OpenClaw 部署专家',
  summary: 'Claw Studio 是一个专业的 OpenClaw 部署和配置服务。我们连接您的系统，自动化您的工作流，并快速交付解决方案。提供 OpenClaw 设置、业务流程自动化、智能助手定制和系统集成服务，帮助企业快速实现 AI 驱动的自动化流程。',
  vendor: 'Claw Studio',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['工作流编排', 'API 集成', '云服务', '企业流程', '运营自动化', '部署'],
  homepageUrl: 'https://clawstudio.ai/',
  githubUrl: null,
  docsUrl: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '商业服务',
  license: '专有',
  focus: 'OpenClaw 部署、工作流自动化、系统集成、定制开发',
  deployment: '云服务，专业部署',
  modelSupport: ['OpenClaw', '自定义 AI 助手', '业务流程自动化'],
  connectivity: ['系统集成', 'API 连接', '数据同步', '工作流编排'],
  scenarios: ['OpenClaw 部署', '业务流程自动化', '数据同步', 'AI 助手定制', '系统集成'],
  gfwStatus: '需要代理',
  pitfalls: ['需要专业服务对接', '定制开发周期视需求而定'],
  benchmark: { successRate: 90, avgDurationMin: 5.0, retries: 1.0 },
  community: { stars: null, release: 'v1.0.0', trend: '商业服务' },
  rating: { security: 8.5, speed: 9.0, flexibility: 9.0, stability: 8.5, docs: 7.5 },
};
