import type { ToolProfile } from '@/lib/tools/types';

export const cline: ToolProfile = {
  slug: 'cline',
  name: 'Cline',
  tagline: 'VSCode 自主编程 Agent，18.5k stars',
  summary: 'Cline 是一个 VSCode 自主编程 Agent，能够自主完成代码编写、调试等任务。支持多种模型，适合软件开发自动化。',
  vendor: 'Cline',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://cline.ai',
  githubUrl: 'https://github.com/cline/cline',
  docsUrl: 'https://docs.cline.ai',
  lastReleaseDate: "2026-03-20T23:27:16Z",
  latestVersion: "v3.75.0",
  lastCommitDate: "2026-03-22T22:20:59Z",
  githubStars: 59257,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'VSCode 自主编程 Agent',
  deployment: 'VSCode Extension',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['软件开发', '代码生成', '调试'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖 VSCode', '复杂任务成功率有限', '需要人工引导'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '18.5k', release: 'v2.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};
