import type { ToolProfile } from '@/lib/tools/types';

export const codiumai: ToolProfile = {
  slug: 'codiumai',
  name: 'CodiumAI',
  tagline: 'AI 测试生成工具',
  summary: 'CodiumAI 是一款 AI 驱动的测试生成工具，自动分析代码生成测试用例，支持多种语言和测试框架，适合提升测试覆盖率。',
  vendor: 'CodiumAI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '测试生成', '商业软件', '开发工具', '质量保障'],
  homepageUrl: 'https://codium.ai',
  githubUrl: null,
  docsUrl: 'https://docs.codium.ai',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/团队付费',
  license: '商业许可',
  focus: '测试生成、代码分析、质量提升',
  deployment: 'VS Code/JetBrains 插件',
  modelSupport: ['自研代码模型', '多语言支持'],
  connectivity: ['IDE 插件', 'Git 集成', 'CI/CD 集成'],
  scenarios: ['单元测试', '测试覆盖', '代码审查', 'Bug 预防'],
  gfwStatus: '需要代理',
  pitfalls: ['测试用例需人工审核', '复杂逻辑覆盖有限'],
  benchmark: { successRate: 82, avgDurationMin: 4.0, retries: 1.4 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.0, flexibility: 8.2, stability: 8.2, docs: 8.0 },
};
