import type { ToolProfile } from '@/lib/tools/types';

export const codellama: ToolProfile = {
  slug: 'codellama',
  name: 'CodeLlama',
  tagline: 'Meta 代码模型，17.2k stars',
  summary: 'CodeLlama 是 Meta 开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'Meta',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://about.fb.com/',
  githubUrl: 'https://github.com/facebookresearch/codellama',
  docsUrl: 'https://github.com/facebookresearch/codellama#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'LLaMA',
  focus: 'Meta 代码模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['CodeLlama', '本地模型'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '需要代理',
  pitfalls: ['LLaMA 许可证限制', '资源占用较高', '商业使用受限'],
  benchmark: { successRate: 80, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '17.2k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 7.5, stability: 8.0, docs: 8.0 },
};
