import type { ToolProfile } from '@/lib/tools/types';

export const codegeex: ToolProfile = {
  slug: 'codegeex',
  name: 'CodeGeeX',
  tagline: '清华代码模型，8.5k stars',
  summary: 'CodeGeeX 是清华大学开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合日常开发。',
  vendor: 'THUDM',
  sourceType: '开源',
  region: '国内',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://codegeex.cn',
  githubUrl: 'https://github.com/THUDM/CodeGeeX2',
  docsUrl: 'https://codegeex.cn/docs',
  githubStars: 7596,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '清华代码模型',
  deployment: 'Python Runtime, VSCode Extension',
  modelSupport: ['CodeGeeX2', '本地模型'],
  connectivity: ['本地运行', 'CodeGeeX API'],
  scenarios: ['代码补全', '代码生成', '日常开发'],
  gfwStatus: '直连可用',
  pitfalls: ['模型性能有限', '复杂任务支持有限', '文档较少'],
  benchmark: { successRate: 78, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '8.5k', release: 'v2.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};
