import type { ToolProfile } from '@/lib/tools/types';

export const codesandboxAI: ToolProfile = {
  slug: 'codesandbox-ai',
  name: 'CodeSandbox AI',
  tagline: '云开发环境的 AI 助手',
  summary: 'CodeSandbox AI 是 CodeSandbox 推出的 AI 助手，集成在云开发环境中，提供代码生成、调试、部署一体化能力。',
  vendor: 'CodeSandbox',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '云 IDE', '商业软件', '开发工具', '前端开发'],
  homepageUrl: 'https://codesandbox.io/ai',
  githubUrl: null,
  docsUrl: 'https://codesandbox.io/docs',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费订阅',
  license: '商业许可',
  focus: '云开发、AI 辅助、一键部署',
  deployment: '云服务平台',
  modelSupport: ['GPT-4', 'Claude', '自研模型'],
  connectivity: ['Web IDE', 'Git 集成', '部署平台'],
  scenarios: ['原型开发', '前端开发', '快速迭代', '团队协作'],
  gfwStatus: '需要代理',
  pitfalls: ['云端依赖', '免费额度有限'],
  benchmark: { successRate: 84, avgDurationMin: 4.0, retries: 1.4 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.2, speed: 8.0, flexibility: 8.8, stability: 8.2, docs: 8.0 },
};
