import type { ToolProfile } from '@/lib/tools/types';

// Code Agent 开源产品
export const tabby: ToolProfile = {
  slug: 'tabby',
  name: 'Tabby',
  tagline: '自托管代码助手，22.4k stars',
  summary: 'Tabby 是一个自托管的AI代码助手，提供代码补全、代码生成等功能。支持多种模型，可以本地部署，适合企业内部使用。',
  vendor: 'TabbyML',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://tabbyml.com',
  githubUrl: 'https://github.com/TabbyML/tabby',
  docsUrl: 'https://tabbyml.com/docs',
  githubStars: 22400,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '自托管代码助手',
  deployment: 'Docker, 本地部署',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API'],
  scenarios: ['代码补全', '代码生成', '企业内部使用'],
  gfwStatus: '直连可用',
  pitfalls: ['需要本地部署', '模型配置复杂', '资源占用较高'],
  benchmark: { successRate: 85, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '22.4k', release: 'v0.10.0', trend: '活跃' },
  rating: { security: 8.5, speed: 8.5, flexibility: 8.0, stability: 8.5, docs: 8.5 },
};

export const smoldeveloper: ToolProfile = {
  slug: 'smol-developer',
  name: 'Smol Developer',
  tagline: '极简AI开发，12.4k stars',
  summary: 'Smol Developer 是一个极简的AI开发工具，提供代码生成、项目初始化等功能。支持多种模型，适合快速原型开发。',
  vendor: 'Smol AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://smol.ai',
  githubUrl: 'https://github.com/smol-ai/developer',
  docsUrl: 'https://smol.ai/docs',
  githubStars: 12400,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '极简AI开发',
  deployment: 'Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码生成', '项目初始化', '快速原型'],
  gfwStatus: '需要代理',
  pitfalls: ['功能精简', '复杂项目支持有限', '文档较少'],
  benchmark: { successRate: 80, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '12.4k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 8.0, flexibility: 7.5, stability: 7.5, docs: 7.5 },
};

export const devon: ToolProfile = {
  slug: 'devon',
  name: 'Devon',
  tagline: '开源代码Agent，3.8k stars',
  summary: 'Devon 是一个开源的代码Agent，能够自主完成代码编写、调试等任务。支持多种模型，适合软件开发自动化。',
  vendor: 'Entropy Research',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://github.com/entropy-research/Devon',
  githubUrl: 'https://github.com/entropy-research/Devon',
  docsUrl: 'https://github.com/entropy-research/Devon#readme',
  githubStars: 3800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '开源代码Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['软件开发', '代码生成', '调试'],
  gfwStatus: '需要代理',
  pitfalls: ['能力仍需完善', '复杂任务成功率有限', '需要人工引导'],
  benchmark: { successRate: 78, avgDurationMin: 4.0, retries: 2.0 },
  community: { stars: '3.8k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 7.0 },
};

export const sweep: ToolProfile = {
  slug: 'sweep',
  name: 'Sweep',
  tagline: 'GitHub自动修复，7.5k stars',
  summary: 'Sweep 是一个GitHub自动修复工具，能够自动检测和修复代码问题。支持多种模型，适合代码维护、 Bug修复等场景。',
  vendor: 'Sweep AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://sweep.dev',
  githubUrl: 'https://github.com/sweepai/sweep',
  docsUrl: 'https://sweep.dev/docs',
  githubStars: 7500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'GitHub自动修复',
  deployment: 'GitHub Actions, Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', 'GitHub API'],
  scenarios: ['代码维护', 'Bug修复', '代码审查'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖GitHub', '复杂Bug修复有限', '需要配置'],
  benchmark: { successRate: 75, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '7.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.5, flexibility: 7.5, stability: 7.5, docs: 8.0 },
};

export const cline: ToolProfile = {
  slug: 'cline',
  name: 'Cline',
  tagline: 'VSCode自主编程Agent，18.5k stars',
  summary: 'Cline 是一个VSCode自主编程Agent，能够自主完成代码编写、调试等任务。支持多种模型，适合软件开发自动化。',
  vendor: 'Cline',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://cline.ai',
  githubUrl: 'https://github.com/cline/cline',
  docsUrl: 'https://docs.cline.ai',
  githubStars: 18500,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'VSCode自主编程Agent',
  deployment: 'VSCode Extension',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['软件开发', '代码生成', '调试'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖VSCode', '复杂任务成功率有限', '需要人工引导'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '18.5k', release: 'v2.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};

export const roocode: ToolProfile = {
  slug: 'roo-code',
  name: 'Roo Code',
  tagline: 'VSCode AI助手，4.2k stars',
  summary: 'Roo Code 是一个VSCode AI助手，提供代码补全、代码生成等功能。支持多种模型，适合日常开发。',
  vendor: 'Roo Vet',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://roo.dev',
  githubUrl: 'https://github.com/RooVetGit/Roo-Cline',
  docsUrl: 'https://docs.roo.dev',
  githubStars: 4200,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'VSCode AI助手',
  deployment: 'VSCode Extension',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码补全', '代码生成', '日常开发'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖VSCode', '功能相对简单', '文档较少'],
  benchmark: { successRate: 82, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '4.2k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 7.5 },
};

export const pearai: ToolProfile = {
  slug: 'pearai',
  name: 'PearAI',
  tagline: '开源AI编辑器，2.8k stars',
  summary: 'PearAI 是一个开源的AI编辑器，提供代码补全、代码生成等功能。支持多种模型，适合日常开发。',
  vendor: 'PearAI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://trypear.ai',
  githubUrl: 'https://github.com/trypear/pearai-master',
  docsUrl: 'https://docs.trypear.ai',
  githubStars: 2800,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'AGPL-3.0',
  focus: '开源AI编辑器',
  deployment: 'Electron App',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码补全', '代码生成', '日常开发'],
  gfwStatus: '需要代理',
  pitfalls: ['AGPL许可证', '功能相对简单', '社区规模小'],
  benchmark: { successRate: 80, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '2.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.0, stability: 7.5, docs: 7.5 },
};

export const refact: ToolProfile = {
  slug: 'refact',
  name: 'Refact',
  tagline: '自托管代码补全，1.8k stars',
  summary: 'Refact 是一个自托管的代码补全工具，提供代码补全、代码生成等功能。支持多种模型，适合企业内部使用。',
  vendor: 'SmallCloudAI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://refact.ai',
  githubUrl: 'https://github.com/smallcloudai/refact',
  docsUrl: 'https://refact.ai/docs',
  githubStars: 1800,
  primaryLanguage: 'Rust',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '自托管代码补全',
  deployment: 'Docker, 本地部署',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API'],
  scenarios: ['代码补全', '代码生成', '企业内部使用'],
  gfwStatus: '直连可用',
  pitfalls: ['需要本地部署', '模型配置复杂', '文档较少'],
  benchmark: { successRate: 82, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '1.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 7.5 },
};

export const fauxpilot: ToolProfile = {
  slug: 'fauxpilot',
  name: 'FauxPilot',
  tagline: '本地GitHub Copilot，14.2k stars',
  summary: 'FauxPilot 是一个本地的GitHub Copilot替代品，提供代码补全、代码生成等功能。支持本地模型，适合离线使用。',
  vendor: 'FauxPilot',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/fauxpilot/fauxpilot',
  githubUrl: 'https://github.com/fauxpilot/fauxpilot',
  docsUrl: 'https://github.com/fauxpilot/fauxpilot#readme',
  githubStars: 14200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '本地GitHub Copilot',
  deployment: 'Docker, 本地部署',
  modelSupport: ['本地模型', 'Salesforce CodeGen'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '离线使用'],
  gfwStatus: '直连可用',
  pitfalls: ['需要本地部署', '模型性能有限', '维护不活跃'],
  benchmark: { successRate: 75, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '14.2k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 7.5, flexibility: 7.5, stability: 7.5, docs: 7.0 },
};

export const codegeex: ToolProfile = {
  slug: 'codegeex',
  name: 'CodeGeeX',
  tagline: '清华代码模型，8.5k stars',
  summary: 'CodeGeeX 是清华大学开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合日常开发。',
  vendor: 'THUDM',
  sourceType: '开源',
  region: '国内',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://codegeex.cn',
  githubUrl: 'https://github.com/THUDM/CodeGeeX2',
  docsUrl: 'https://codegeex.cn/docs',
  githubStars: 8500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '清华代码模型',
  deployment: 'Python Runtime, VSCode Extension',
  modelSupport: ['CodeGeeX2', '本地模型'],
  connectivity: ['本地运行', 'CodeGeeX API'],
  scenarios: ['代码补全', '代码生成', '日常开发'],
  gfwStatus: '直连可用',
  pitfalls: ['模型性能有限', '复杂任务支持有限', '文档较少'],
  benchmark: { successRate: 78, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '8.5k', release: 'v2.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};

export const codellama: ToolProfile = {
  slug: 'codellama',
  name: 'CodeLlama',
  tagline: 'Meta代码模型，17.2k stars',
  summary: 'CodeLlama 是Meta开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'Meta',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://about.fb.com/',
  githubUrl: 'https://github.com/facebookresearch/codellama',
  docsUrl: 'https://github.com/facebookresearch/codellama#readme',
  githubStars: 17200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'LLaMA',
  focus: 'Meta代码模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['CodeLlama', '本地模型'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '需要代理',
  pitfalls: ['LLaMA许可证限制', '资源占用较高', '商业使用受限'],
  benchmark: { successRate: 80, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '17.2k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 7.5, stability: 8.0, docs: 8.0 },
};

export const starcoder: ToolProfile = {
  slug: 'starcoder',
  name: 'StarCoder',
  tagline: 'BigCode代码模型，20.1k stars',
  summary: 'StarCoder 是BigCode项目开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'BigCode',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://bigcode-project.github.io',
  githubUrl: 'https://github.com/bigcode-project/starcoder',
  docsUrl: 'https://bigcode-project.github.io/docs',
  githubStars: 20100,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'BigCode',
  focus: 'BigCode代码模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['StarCoder', '本地模型'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '需要代理',
  pitfalls: ['许可证限制', '资源占用较高', '商业使用受限'],
  benchmark: { successRate: 82, avgDurationMin: 1.8, retries: 1.2 },
  community: { stars: '20.1k', release: 'v2.0.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 8.5 },
};

export const deepseekcoder: ToolProfile = {
  slug: 'deepseek-coder',
  name: 'DeepSeek Coder',
  tagline: '深度求索代码模型，15.8k stars',
  summary: 'DeepSeek Coder 是深度求索开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'DeepSeek',
  sourceType: '开源',
  region: '国内',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://deepseek.com',
  githubUrl: 'https://github.com/deepseek-ai/DeepSeek-Coder',
  docsUrl: 'https://deepseek.com/docs',
  githubStars: 15800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '深度求索代码模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['DeepSeek Coder', '本地模型'],
  connectivity: ['本地运行', 'DeepSeek API'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '直连可用',
  pitfalls: ['资源占用较高', '复杂任务支持有限', '文档较少'],
  benchmark: { successRate: 85, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '15.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.5, stability: 8.5, docs: 8.5 },
};

export const wizardcoder: ToolProfile = {
  slug: 'wizardcoder',
  name: 'WizardCoder',
  tagline: '代码生成模型，10.5k stars',
  summary: 'WizardCoder 是一个代码生成模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'NLPC',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/nlpxucan/WizardLM',
  githubUrl: 'https://github.com/nlpxucan/WizardLM',
  docsUrl: 'https://github.com/nlpxucan/WizardLM#readme',
  githubStars: 10500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '代码生成模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['WizardCoder', '本地模型'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '需要代理',
  pitfalls: ['资源占用较高', '复杂任务支持有限', '文档较少'],
  benchmark: { successRate: 78, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '10.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 8.0, flexibility: 7.5, stability: 7.5, docs: 7.5 },
};

export const instructcode: ToolProfile = {
  slug: 'instructcode',
  name: 'InstructCode',
  tagline: '指令代码生成，1.2k stars',
  summary: 'InstructCode 是一个指令驱动的代码生成工具，提供代码生成、代码补全等功能。支持多种模型，适合快速原型开发。',
  vendor: 'InstructLab',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://github.com/instructlab/instructcode',
  githubUrl: 'https://github.com/instructlab/instructcode',
  docsUrl: 'https://github.com/instructlab/instructcode#readme',
  githubStars: 1200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '指令代码生成',
  deployment: 'Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码生成', '快速原型', '项目初始化'],
  gfwStatus: '需要代理',
  pitfalls: ['功能精简', '复杂项目支持有限', '文档较少'],
  benchmark: { successRate: 75, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '1.2k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.5, flexibility: 7.5, stability: 7.5, docs: 7.0 },
};

export const copilotcli: ToolProfile = {
  slug: 'copilot-cli',
  name: 'Copilot CLI',
  tagline: '命令行Copilot，3.5k stars',
  summary: 'Copilot CLI 是GitHub开发的命令行Copilot工具， 提供命令行代码补全、代码生成等功能。适合终端开发场景。',
  vendor: 'GitHub',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://github.com/features/copilot',
  githubUrl: 'https://github.com/github/copilot-cli',
  docsUrl: 'https://docs.github.com/copilot',
  githubStars: 3500,
  primaryLanguage: 'Go',
  pricing: '免费开源',
  license: 'MIT',
  focus: '命令行Copilot',
  deployment: '命令行工具',
  modelSupport: ['GitHub Copilot'],
  connectivity: ['GitHub API'],
  scenarios: ['命令行开发', '代码补全', '代码生成'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖GitHub Copilot', '需要GitHub订阅', '命令行场景有限'],
  benchmark: { successRate: 85, avgDurationMin: 1.0, retries: 0.5 },
  community: { stars: '3.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};

// 导出所有产品
export const codeAgentProducts: ToolProfile[] = [
  tabby,
  smoldeveloper,
  devon,
  sweep,
  cline,
  roocode,
  pearai,
  refact,
  fauxpilot,
  codegeex,
  codellama,
  starcoder,
  deepseekcoder,
  wizardcoder,
  instructcode,
  copilotcli,
];
