import type { ToolProfile } from '@/lib/tools/types';

export const cognosys: ToolProfile = {
  slug: 'cognosys',
  name: 'Cognosys',
  tagline: 'AI Agent 自动化平台',
  summary: 'Cognosys 是一款 AI Agent 自动化平台，提供任务拆解、工具调用、流程编排能力，适合企业构建智能自动化流程。',
  vendor: 'Cognosys AI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI', '企业流程', '商业软件', '工作流自动化', '任务自动化'],
  homepageUrl: 'https://cognosys.ai',
  githubUrl: null,
  docsUrl: 'https://docs.cognosys.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业许可',
  focus: '任务拆解、工具调用、流程编排',
  deployment: '云服务平台',
  modelSupport: ['GPT-4', 'Claude', '多模型路由'],
  connectivity: ['REST API', 'Webhook', '第三方集成'],
  scenarios: ['业务流程自动化', '客户服务', '数据分析', '报告生成'],
  gfwStatus: '需要代理',
  pitfalls: ['配置复杂度较高', '定价不透明'],
  benchmark: { successRate: 82, avgDurationMin: 6.5, retries: 1.6 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.2, speed: 7.8, flexibility: 8.5, stability: 7.8, docs: 7.5 },
};
