import type { ToolProfile } from '@/lib/tools/types';

export const computeruse: ToolProfile = {
  slug: 'computeruse',
  name: 'Computer Use',
  tagline: 'Anthropic官方Computer Use API',
  summary: 'Computer Use 是Anthropic官方提供的Computer Use API，能够通过视觉理解自动操作计算机。支持Claude 3.5、 适合桌面自动化、 任务自动化等场景。',
  vendor: 'Anthropic',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '闭源', '云服务', '自部署'],
  homepageUrl: 'https://www.anthropic.com/claude/computer-use',
  githubUrl: null,
  docsUrl: 'https://docs.anthropic.com/claude/docs/computer-use',
  githubStars: null,
  primaryLanguage: 'API',
  pricing: '按量付费',
  license: '专有',
  focus: 'Computer Use API',
  deployment: 'Cloud API',
  modelSupport: ['Claude 3.5 Sonnet', 'Claude 3.5 Haiku'],
  connectivity: ['Anthropic API'],
  scenarios: ['桌面自动化', '任务自动化', 'GUI测试'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限API调用', '需要Anthropic账户', '费用较高'],
  benchmark: { successRate: 85, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: 'N/A', release: 'N/A', trend: '活跃' },
  rating: { security: 8.5, speed: 8.5, flexibility: 8.0, stability: 8.5, docs: 9.0 },
};
