import type { ToolProfile } from '@/lib/tools/types';

export const continuedev: ToolProfile = {
  slug: 'continue',
  name: 'Continue',
  tagline: 'VSCode AI助手，25.8k stars',
  summary: 'Continue 是一个开源的 VSCode AI 助手，提供代码补全、代码生成、代码解释等功能。支持多种模型，可以本地部署，适合日常开发、代码重构、调试等场景。',
  vendor: 'Continue Dev',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://continue.dev',
  githubUrl: 'https://github.com/continuedev/continue',
  docsUrl: 'https://docs.continue.dev',
  lastReleaseDate: "2026-03-13T19:49:39Z",
  latestVersion: "v1.2.17-vscode",
  lastCommitDate: "2026-03-23T06:23:06Z",
  githubStars: 32000,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'VSCode AI助手',
  deployment: 'VSCode Extension, 本地模型',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码补全', '代码生成', '代码解释', 'VSCode集成'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖VSCode', '本地模型需要配置', '部分功能需要云模型'],
  benchmark: { successRate: 85, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '25.8k', release: 'v0.8.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.5, stability: 8.5, docs: 9.0 },
};
