import type { ToolProfile } from '@/lib/tools/types';

export const copaw: ToolProfile = {
  slug: 'copaw',
  name: 'CoPaw',
  tagline: '阿里云托管 Claw 服务',
  summary: '集成钉钉、支付宝生态的阿里云 OpenClaw 云服务。',
  vendor: '阿里云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://copaw.aliyun.com',
  githubUrl: null,
  docsUrl: 'https://help.aliyun.com/copaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按调用量计费',
  license: '商业闭源',
  focus: '钉钉/支付宝集成、通义大模型、企业场景',
  deployment: '阿里云托管，无需自建',
  modelSupport: ['通义千问', 'Qwen 系列'],
  connectivity: ['阿里云服务', '钉钉集成', '支付宝集成'],
  scenarios: ['企业流程自动化', '钉钉机器人', '支付宝场景'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖阿里云生态', '跨云迁移成本高', '深度定制受限'],
  benchmark: { successRate: 88, avgDurationMin: 5.5, retries: 1.1 },
  community: { stars: '官方服务', release: '持续更新', trend: '阿里企业客户增长快' },
  rating: { security: 8.5, speed: 8.8, flexibility: 7.5, stability: 8.5, docs: 8.2 },
};
