import type { ToolProfile } from '@/lib/tools/types';

export const copilot: ToolProfile = {
  slug: 'copilot',
  name: 'Microsoft Copilot',
  tagline: '微软的 AI 助手',
  summary: 'Microsoft Copilot 是微软推出的 AI 助手，集成 GPT-4 和 DALL-E 3 能力，深度整合 Windows 和 Office 生态。',
  vendor: 'Microsoft',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['对话 AI', '个人助手', '商业软件', '多模态', 'Office 集成'],
  homepageUrl: 'https://copilot.microsoft.com',
  githubUrl: null,
  docsUrl: 'https://support.microsoft.com/copilot',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Pro $20/月',
  license: '商业许可',
  focus: 'GPT-4 对话、Office 集成、图像生成',
  deployment: 'Web 应用 + Windows 集成 + 移动 App',
  modelSupport: ['GPT-4', 'DALL-E 3', '自研模型'],
  connectivity: ['Web 界面', 'Windows 集成', 'Office 集成', '移动 App'],
  scenarios: ['日常助手', 'Office 自动化', '图像生成', 'Windows 操作'],
  gfwStatus: '需要代理',
  pitfalls: ['国内功能受限', '高级功能需付费'],
  benchmark: { successRate: 90, avgDurationMin: 3.2, retries: 1.1 },
  community: { stars: null, release: '持续更新', trend: '快速增长' },
  rating: { security: 9.0, speed: 8.8, flexibility: 9.0, stability: 9.0, docs: 8.8 },
};
