import type { ToolProfile } from '@/lib/tools/types';

export const copilotcli: ToolProfile = {
  slug: 'copilot-cli',
  name: 'Copilot CLI',
  tagline: '命令行 Copilot，3.5k stars',
  summary: 'Copilot CLI 是 GitHub 开发的命令行 Copilot 工具，提供命令行代码补全、代码生成等功能。适合终端开发场景。',
  vendor: 'GitHub',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://github.com/features/copilot',
  githubUrl: 'https://github.com/github/copilot-cli',
  docsUrl: 'https://docs.github.com/copilot',
  githubStars: 9511,
  primaryLanguage: "Shell",
  pricing: '免费开源',
  license: 'MIT',
  focus: '命令行 Copilot',
  deployment: '命令行工具',
  modelSupport: ['GitHub Copilot'],
  connectivity: ['GitHub API'],
  scenarios: ['命令行开发', '代码补全', '代码生成'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖 GitHub Copilot', '需要 GitHub 订阅', '命令行场景有限'],
  benchmark: { successRate: 85, avgDurationMin: 1.0, retries: 0.5 },
  community: { stars: '3.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};
