import type { ToolProfile } from '@/lib/tools/types';

export const coze: ToolProfile = {
  slug: 'coze',
  name: 'Coze',
  tagline: '字节系 Bot 与 Agent 云平台',
  summary: '偏应用侧快速上线，适合运营驱动的 Bot 产品。',
  vendor: '字节跳动',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: '应用平台 / 工作流平台',
  tags: ['工作流编排', '插件生态', '闭源', '云服务', 'MVP 原型'],
  homepageUrl: 'https://www.coze.cn',
  githubUrl: null,
  docsUrl: 'https://www.coze.cn/open/docs/developer_guides/welcome',
  githubStars: null,
  primaryLanguage: null,
  pricing: 'SaaS 阶梯计费',
  license: '商业闭源',
  focus: 'Bot 构建、插件接入、渠道分发',
  deployment: '以云端为主，私有化灵活性有限。',
  modelSupport: ['豆包', '通义', 'DeepSeek', '第三方模型'],
  connectivity: ['平台托管', 'API 调用'],
  scenarios: ['运营机器人', '客服自动化', '渠道分发'],
  gfwStatus: '直连可用',
  pitfalls: ['深度定制能力受平台边界限制', '复杂审计链路需要外部系统补充', '跨云迁移成本较高'],
  benchmark: { successRate: 80, avgDurationMin: 6.7, retries: 1.8 },
  community: { stars: '官方平台', release: '持续迭代', trend: '国内应用开发者增长快' },
  rating: { security: 7.9, speed: 8.3, flexibility: 7.4, stability: 8.2, docs: 7.9 },
};
