import type { ToolProfile } from '@/lib/tools/types';

export const crewai: ToolProfile = {
  slug: 'crewai',
  name: 'CrewAI',
  tagline: '多 Agent 协作编排框架',
  summary: '适合搭建角色化、多任务分工的企业工作流。',
  vendor: 'CrewAI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['多角色协作', '工作流编排', '开源', '插件生态', '企业流程'],
  homepageUrl: 'https://github.com/crewAIInc/crewAI',
  githubUrl: 'https://github.com/crewAIInc/crewAI',
  docsUrl: 'https://docs.crewai.com',
  lastReleaseDate: "2026-03-18T13:38:51Z",
  latestVersion: "1.11.0",
  lastCommitDate: "2026-03-23T05:31:01Z",
  githubStars: 46940,
  primaryLanguage: "Python",
  pricing: '开源免费，企业版增值',
  license: 'MIT',
  focus: '角色分工、任务路由、流程治理',
  deployment: 'Python 生态友好，生产环境建议容器化。',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'Gemini', '本地 LLM'],
  connectivity: ['本地或云端均可', '可接入企业内部工具'],
  scenarios: ['企业流程自动化', '多角色协作', '工作流编排'],
  gfwStatus: '直连可用',
  pitfalls: ['流程设计不当会引起链路冗余', '多角色提示词治理成本较高', '可观测性体系需要额外建设'],
  benchmark: { successRate: 81, avgDurationMin: 8.6, retries: 1.6 },
  community: { stars: '31.5k', release: 'v0.88.1', trend: '企业编排场景热度持续提升' },
  rating: { security: 8.0, speed: 7.8, flexibility: 9.0, stability: 7.9, docs: 8.1 },
};
