import type { ToolProfile } from '@/lib/tools/types';

export const cursorAgent: ToolProfile = {
  slug: 'cursor-agent',
  name: 'Cursor Agent',
  tagline: 'IDE 原生代理式编码体验',
  summary: '开发者效率高，适合快速编码与重构。',
  vendor: 'Anysphere',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '闭源', '本地优先', '研发提效', '个人助手'],
  homepageUrl: 'https://cursor.com',
  githubUrl: null,
  docsUrl: 'https://docs.cursor.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业闭源',
  focus: '代码生成、重构、上下文编程',
  deployment: '客户端安装即用，企业治理需要补充控制层。',
  modelSupport: ['Claude', 'GPT', 'Gemini'],
  connectivity: ['云端模型 API'],
  scenarios: ['研发提效', '代码重构', '调试辅助'],
  gfwStatus: '需要代理',
  pitfalls: ['企业合规与代码外发需严格审计', '离线能力弱', '重度依赖网络质量'],
  benchmark: { successRate: 85, avgDurationMin: 5.9, retries: 1.5 },
  community: { stars: '商业产品', release: '持续迭代', trend: '开发者采用率快速增长' },
  rating: { security: 7.2, speed: 9.0, flexibility: 8.4, stability: 8.0, docs: 7.7 },
};
