import type { ToolProfile } from '@/lib/tools/types';

export const danswer: ToolProfile = {
  slug: 'danswer',
  name: 'Danswer',
  tagline: '企业级智能问答平台',
  summary: 'Danswer 是一款企业级智能问答平台，支持多源数据连接、权限管理、AI 问答，适合构建企业内部知识搜索系统。',
  vendor: 'Danswer AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['RAG', '开源', '知识库', '企业流程', '数据自动化'],
  homepageUrl: 'https://danswer.ai',
  githubUrl: 'https://github.com/danswer-ai/danswer',
  docsUrl: 'https://docs.danswer.ai',
  githubStars: 17977,
  primaryLanguage: "Python",
  pricing: '免费开源，企业版付费',
  license: 'MIT',
  focus: '企业搜索、权限管理、多源数据集成',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['GPT-4', 'Claude', 'Llama', '支持本地模型'],
  connectivity: ['REST API', '向量数据库', '企业系统 connector'],
  scenarios: ['企业知识搜索', '技术支持', '内部问答', '文档检索'],
  gfwStatus: '直连可用',
  pitfalls: ['企业集成需定制开发', '配置复杂度较高'],
  benchmark: { successRate: 81, avgDurationMin: 5.2, retries: 1.5 },
  community: { stars: '8.5k', release: 'v1.15.0', trend: '稳定增长' },
  rating: { security: 8.5, speed: 7.6, flexibility: 8.5, stability: 8.0, docs: 7.8 },
};
