import type { ToolProfile } from '@/lib/tools/types';

export const databricks: ToolProfile = {
  slug: 'databricks',
  name: 'Databricks AI',
  tagline: '数据 AI 平台领导者',
  summary: 'Databricks AI 是基于 Lakehouse 架构的 AI 平台，提供 Mosaic ML 模型训练和托管能力，适合企业构建数据驱动的 AI 应用。',
  vendor: 'Databricks',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: '云厂商 Agent 服务',
  tags: ['云服务', '数据自动化', '企业流程', 'AI 平台', '大数据'],
  homepageUrl: 'https://databricks.com',
  githubUrl: 'https://github.com/databricks',
  docsUrl: 'https://docs.databricks.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按使用量计费',
  license: '商业许可',
  focus: 'Lakehouse AI、模型训练、数据工程',
  deployment: '云平台，支持 AWS/Azure/GCP',
  modelSupport: ['Databricks 自研模型', '支持 HuggingFace 模型'],
  connectivity: ['Spark 集成', 'REST API', 'MLflow'],
  scenarios: ['数据科学', '模型训练', '企业 AI', '大数据分析'],
  gfwStatus: '需要代理',
  pitfalls: ['技术门槛较高', '成本需控制'],
  benchmark: { successRate: 88, avgDurationMin: 5.5, retries: 1.2 },
  community: { stars: '5k', release: '持续更新', trend: '企业市场增长' },
  rating: { security: 9.0, speed: 8.5, flexibility: 8.8, stability: 8.8, docs: 8.5 },
};
