import type { ToolProfile } from '@/lib/tools/types';

export const deepseekcoder: ToolProfile = {
  slug: 'deepseek-coder',
  name: 'DeepSeek Coder',
  tagline: '深度求索代码模型，15.8k stars',
  summary: 'DeepSeek Coder 是深度求索开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'DeepSeek',
  sourceType: '开源',
  region: '国内',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://deepseek.com',
  githubUrl: 'https://github.com/deepseek-ai/DeepSeek-Coder',
  docsUrl: 'https://deepseek.com/docs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '深度求索代码模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['DeepSeek Coder', '本地模型'],
  connectivity: ['本地运行', 'DeepSeek API'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '直连可用',
  pitfalls: ['资源占用较高', '复杂任务支持有限', '文档较少'],
  benchmark: { successRate: 85, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '15.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.5, stability: 8.5, docs: 8.5 },
};
