import type { ToolProfile } from '@/lib/tools/types';

export const devin: ToolProfile = {
  slug: 'devin',
  name: 'Devin',
  tagline: '云端软件工程代理服务',
  summary: '强调端到端任务执行和开发流程自动化。',
  vendor: 'Cognition',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['代码生成', '闭源', '云服务', '研发提效', '企业流程'],
  homepageUrl: 'https://devin.ai',
  githubUrl: null,
  docsUrl: 'https://docs.devin.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按 seat 与额度计费',
  license: '商业闭源',
  focus: '任务执行、代码实现、测试与回报',
  deployment: '云端托管，企业接入以 API 和控制台为主。',
  modelSupport: ['专有模型栈'],
  connectivity: ['云端服务'],
  scenarios: ['需求到 PR 自动化', '测试修复', '工程任务分派'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['成本较高', '任务边界需要严格定义', '敏感代码托管需审查合规'],
  benchmark: { successRate: 74, avgDurationMin: 12.4, retries: 2.7 },
  community: { stars: '商业产品', release: '持续发布', trend: '大型团队试点增加' },
  rating: { security: 7.0, speed: 7.4, flexibility: 8.2, stability: 7.3, docs: 7.2 },
};
