import type { ToolProfile } from '@/lib/tools/types';

export const devon: ToolProfile = {
  slug: 'devon',
  name: 'Devon',
  tagline: 'AI软件工程师，12k stars',
  summary: 'Devon 是一个AI软件工程师，能够自主完成复杂的开发任务。适合代码生成、 代码审查、 开发辅助等场景。',
  vendor: 'Cursorless',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/Cursorless/devon',
  githubUrl: 'https://github.com/Cursorless/devon',
  docsUrl: 'https://github.com/Cursorless/devon#readme',
  githubStars: 12000,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI软件工程师',
  deployment: 'Python Runtime, CLI',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['OpenAI API', 'Anthropic API'],
  scenarios: ['代码生成', '代码审查', '开发辅助'],
  gfwStatus: '需要代理',
  pitfalls: ['需要API密钥', '复杂任务支持有限', '需要人工审核'],
  benchmark: { successRate: 75, avgDurationMin: 4.5, retries: 2.0 },
  community: { stars: '12k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 7.5 },
};
