import type { ToolProfile } from '@/lib/tools/types';

export const devon: ToolProfile = {
  slug: 'devon',
  name: 'Devon',
  tagline: '开源代码 Agent，3.8k stars',
  summary: 'Devon 是一个开源的代码 Agent，能够自主完成代码编写、调试等任务。支持多种模型，适合软件开发自动化。',
  vendor: 'Entropy Research',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://github.com/entropy-research/Devon',
  githubUrl: 'https://github.com/entropy-research/Devon',
  docsUrl: 'https://github.com/entropy-research/Devon#readme',
  githubStars: 3454,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '开源代码 Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['软件开发', '代码生成', '调试'],
  gfwStatus: '需要代理',
  pitfalls: ['能力仍需完善', '复杂任务成功率有限', '需要人工引导'],
  benchmark: { successRate: 78, avgDurationMin: 4.0, retries: 2.0 },
  community: { stars: '3.8k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 7.0 },
};
