import type { ToolProfile } from '@/lib/tools/types';

export const dify: ToolProfile = {
  slug: 'dify',
  name: 'Dify',
  tagline: '可视化 AI 应用与 Agent 编排平台',
  summary: '提供低代码构建、知识库、工作流和应用发布能力。',
  vendor: 'Dify.AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '应用平台 / 工作流平台',
  tags: ['工作流编排', 'RAG', '开源', '自部署', '企业流程'],
  homepageUrl: 'https://dify.ai',
  githubUrl: 'https://github.com/langgenius/dify',
  docsUrl: 'https://docs.dify.ai',
  lastReleaseDate: "2026-03-18T14:20:55Z",
  latestVersion: "1.13.2",
  lastCommitDate: "2026-03-23T10:33:24Z",
  githubStars: 134081,
  primaryLanguage: "TypeScript",
  pricing: '开源自建免费，云服务付费',
  license: 'Apache-2.0',
  focus: '低代码编排、知识库、应用运营',
  deployment: 'Docker 部署友好，企业可私有化。',
  modelSupport: ['OpenAI', 'Claude', 'Gemini', 'Qwen', 'DeepSeek'],
  connectivity: ['本地私有化', '官方云服务'],
  scenarios: ['企业内部 AI 应用', '知识问答', 'Agent 工作流'],
  gfwStatus: '直连可用',
  pitfalls: ['复杂流程调试链路较长', '多租户权限需单独设计', '大规模检索性能需优化'],
  benchmark: { successRate: 84, avgDurationMin: 7.3, retries: 1.5 },
  community: { stars: '84.0k', release: 'v1.x', trend: '国内企业落地增长显著' },
  rating: { security: 8.1, speed: 8.0, flexibility: 8.7, stability: 8.0, docs: 8.4 },
};
