import type { ToolProfile } from '@/lib/tools/types';

export const digitaloceanclaw: ToolProfile = {
  slug: 'digitaloceanclaw',
  name: 'DigitalOcean Claw',
  tagline: 'DigitalOcean 云服务 Claw',
  summary: '开发者友好、简单部署的 OpenClaw 云服务。',
  vendor: 'DigitalOcean',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://digitaloceanclaw.digitalocean.com',
  githubUrl: null,
  docsUrl: 'https://docs.digitalocean.com/digitaloceanclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按资源计费',
  license: '商业闭源',
  focus: '开发者友好、简单部署、云托管',
  deployment: 'DigitalOcean 托管',
  modelSupport: ['DigitalOcean 模型', '自定义模型'],
  connectivity: ['DigitalOcean 服务', 'API 访问'],
  scenarios: ['云托管', '开发者场景', '简单部署'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 84, avgDurationMin: 6.0, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '开发者采用稳定' },
  rating: { security: 9.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.0 },
};
