import type { ToolProfile } from '@/lib/tools/types';

export const dobaoclaw: ToolProfile = {
  slug: 'dobaoclaw',
  name: 'DoubaoClaw',
  tagline: '字节跳动豆包 Claw 服务',
  summary: '基于豆包大模型、C端产品的 OpenClaw 云服务。',
  vendor: '字节跳动',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://dobaoclaw.doubao.com',
  githubUrl: null,
  docsUrl: 'https://platform.doubao.com/docs/dobaoclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按量计费',
  license: '商业闭源',
  focus: '豆包大模型、C端产品、内容创作',
  deployment: '字节云托管',
  modelSupport: ['豆包系列', 'Doubao 大模型'],
  connectivity: ['字节云服务', '抖音集成', '飞书集成'],
  scenarios: ['C端产品', '内容创作', '社交自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖字节生态', '跨平台支持有限', '企业功能待完善'],
  benchmark: { successRate: 85, avgDurationMin: 5.0, retries: 1.2 },
  community: { stars: '官方服务', release: '持续迭代', trend: 'C端用户增长快' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.0, stability: 8.2, docs: 7.5 },
};
