import type { ToolProfile } from '@/lib/tools/types';

export const fastgpt: ToolProfile = {
  slug: 'fastgpt',
  name: 'FastGPT',
  tagline: '开源的知识库问答平台',
  summary: 'FastGPT 是一款开源的知识库问答平台，基于 LLM 和 RAG 技术，提供可视化工作流编排，适合构建企业智能客服和知识问答系统。',
  vendor: 'FastGPT 团队',
  sourceType: '开源',
  region: '国内',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['RAG', '可视化编排', '开源', '知识库', '企业流程'],
  homepageUrl: 'https://fastgpt.in',
  githubUrl: 'https://github.com/labring/FastGPT',
  docsUrl: 'https://doc.fastgpt.in',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源，云服务付费',
  license: 'Apache-2.0',
  focus: '知识库问答、可视化编排、RAG',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['GPT-4', 'Claude', '通义千问', '支持国内大模型'],
  connectivity: ['REST API', '数据库连接', 'Web 界面'],
  scenarios: ['智能客服', '企业知识库', '文档问答', '培训系统'],
  gfwStatus: '直连可用',
  pitfalls: ['配置需一定技术门槛', '大规模部署需优化'],
  benchmark: { successRate: 83, avgDurationMin: 4.5, retries: 1.3 },
  community: { stars: '18k', release: 'v4.8.0', trend: '快速增长' },
  rating: { security: 8.2, speed: 8.0, flexibility: 8.5, stability: 8.2, docs: 8.0 },
};
