import type { ToolProfile } from '@/lib/tools/types';

export const fauxpilot: ToolProfile = {
  slug: 'fauxpilot',
  name: 'FauxPilot',
  tagline: '本地 GitHub Copilot，14.2k stars',
  summary: 'FauxPilot 是一个本地的 GitHub Copilot 替代品，提供代码补全、代码生成等功能。支持本地模型，适合离线使用。',
  vendor: 'FauxPilot',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/fauxpilot/fauxpilot',
  githubUrl: 'https://github.com/fauxpilot/fauxpilot',
  docsUrl: 'https://github.com/fauxpilot/fauxpilot#readme',
  githubStars: 14761,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '本地 GitHub Copilot',
  deployment: 'Docker, 本地部署',
  modelSupport: ['本地模型', 'Salesforce CodeGen'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '离线使用'],
  gfwStatus: '直连可用',
  pitfalls: ['需要本地部署', '模型性能有限', '维护不活跃'],
  benchmark: { successRate: 75, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '14.2k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 7.5, flexibility: 7.5, stability: 7.5, docs: 7.0 },
};
