import type { ToolProfile } from '@/lib/tools/types';

export const flowise: ToolProfile = {
  slug: 'flowise',
  name: 'Flowise',
  tagline: '可视化 LLM 应用开发平台',
  summary: 'Flowise 是一款可视化的 LLM 应用开发平台，通过拖拽方式构建 LangChain 流程，适合非技术人员快速搭建 AI 应用。',
  vendor: 'FlowiseAI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['可视化编排', '开源', '低代码', '企业流程', '开发工具'],
  homepageUrl: 'https://flowiseai.com',
  githubUrl: 'https://github.com/FlowiseAI/Flowise',
  docsUrl: 'https://docs.flowiseai.com',
  githubStars: 32500,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源，云服务付费',
  license: 'Apache-2.0',
  focus: '可视化编排、拖拽开发、快速部署',
  deployment: 'npm 包，支持 Docker 部署',
  modelSupport: ['GPT-4', 'Claude', '支持 LangChain 全量模型'],
  connectivity: ['REST API', 'WebSocket', '数据库连接'],
  scenarios: ['AI 应用开发', '原型验证', '企业工作流', '智能客服'],
  gfwStatus: '直连可用',
  pitfalls: ['大规模部署需优化', '复杂流程调试困难'],
  benchmark: { successRate: 80, avgDurationMin: 5.5, retries: 1.5 },
  community: { stars: '32.5k', release: 'v2.2.0', trend: '快速增长' },
  rating: { security: 7.8, speed: 7.6, flexibility: 8.8, stability: 7.8, docs: 8.0 },
};
