import type { ToolProfile } from '@/lib/tools/types';

export const flyclaw: ToolProfile = {
  slug: 'flyclaw',
  name: 'Fly.io Claw',
  tagline: 'Fly.io 边缘 Claw 服务',
  summary: '全球边缘节点、低延迟的 OpenClaw 云服务。',
  vendor: 'Fly.io',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://flyclaw.fly.io',
  githubUrl: null,
  docsUrl: 'https://docs.fly.io/flyclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按使用计费',
  license: '商业闭源',
  focus: '全球边缘节点、低延迟、边缘计算',
  deployment: 'Fly.io 托管',
  modelSupport: ['Fly.io 模型', '自定义模型'],
  connectivity: ['Fly.io 服务', 'API 访问'],
  scenarios: ['边缘计算', '全球加速', '低延迟场景'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 85, avgDurationMin: 5.5, retries: 1.3 },
  community: { stars: '官方服务', release: '持续更新', trend: '边缘计算采用增长' },
  rating: { security: 9.0, speed: 9.0, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};
