import type { ToolProfile } from '@/lib/tools/types';

export const gcpclaw: ToolProfile = {
  slug: 'gcpclaw',
  name: 'GCP Claw',
  tagline: 'Google Cloud Vertex AI Claw 服务',
  summary: 'BigQuery 集成、对话 Agent 的 OpenClaw 云服务。',
  vendor: 'Google Cloud',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://gcpclaw.cloud.google.com',
  githubUrl: null,
  docsUrl: 'https://cloud.google.com/docs/gcpclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按交互计费',
  license: '商业闭源',
  focus: 'BigQuery 集成、对话 Agent、Vertex AI 平台',
  deployment: 'GCP 托管',
  modelSupport: ['Gemini', 'PaLM', 'Vertex AI 模型'],
  connectivity: ['GCP 服务', 'API 访问', 'BigQuery 集成'],
  scenarios: ['对话 Agent', '数据分析', '智能助手'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 84, avgDurationMin: 5.8, retries: 1.3 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业试点增长快' },
  rating: { security: 9.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};
