import type { ToolProfile } from '@/lib/tools/types';

export const gemini: ToolProfile = {
  slug: 'gemini',
  name: 'Gemini',
  tagline: 'Google 的 AI 助手',
  summary: 'Gemini 是 Google 推出的 AI 助手，提供多模态理解、代码生成、Google 生态集成能力，支持原生多模态输入。',
  vendor: 'Google',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['对话 AI', '个人助手', '商业软件', '多模态', '代码生成'],
  homepageUrl: 'https://gemini.google.com',
  githubUrl: null,
  docsUrl: 'https://ai.google.dev',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Advanced $20/月',
  license: '商业许可',
  focus: '多模态理解、Google 集成、代码生成',
  deployment: 'Web 应用 + 移动 App + API',
  modelSupport: ['Gemini 1.5', 'Gemini 1.0', 'Gemini Ultra'],
  connectivity: ['Web 界面', '移动 App', 'REST API', 'Google 生态'],
  scenarios: ['日常助手', '多模态分析', 'Google 集成', '代码开发'],
  gfwStatus: '需要代理',
  pitfalls: ['需科学上网', '国内无法使用'],
  benchmark: { successRate: 91, avgDurationMin: 3.0, retries: 1.1 },
  community: { stars: null, release: '持续更新', trend: '快速增长' },
  rating: { security: 9.0, speed: 9.0, flexibility: 9.2, stability: 9.0, docs: 8.8 },
};
