import type { ToolProfile } from '@/lib/tools/types';

// 通用任务执行 Agent 开源产品
export const agentgpt: ToolProfile = {
  slug: 'agentgpt',
  name: 'AgentGPT',
  tagline: '浏览器Agent，32.1k stars',
  summary: 'AgentGPT 是一个浏览器Agent，能够自主完成网页任务。支持多种模型，适合网页自动化、 数据采集等场景。',
  vendor: 'Reworkd',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://agentgpt.reworkd.ai',
  githubUrl: 'https://github.com/reworkd/AgentGPT',
  docsUrl: 'https://docs.reworkd.ai',
  githubStars: 32100,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'GPL-3.0',
  focus: '浏览器Agent',
  deployment: 'Node.js Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['网页自动化', '数据采集', '任务执行'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限浏览器场景', '需要人工引导', '复杂任务成功率有限'],
  benchmark: { successRate: 78, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '32.1k', release: 'v2.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.0, stability: 7.5, docs: 8.0 },
};

export const gptresearcher: ToolProfile = {
  slug: 'gpt-researcher',
  name: 'GPT-Researcher',
  tagline: 'AI研究助手，30.8k stars',
  summary: 'GPT-Researcher 是一个AI研究助手，能够自主完成研究任务。支持多种模型、 适合研究自动化、 报告生成等场景。',
  vendor: 'Assaf Elovic',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '个人助手'],
  homepageUrl: 'https://gptr.dev',
  githubUrl: 'https://github.com/assafelovic/gpt-researcher',
  docsUrl: 'https://docs.gptr.dev',
  githubStars: 30800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI研究助手',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['研究自动化', '报告生成', '数据收集'],
  gfwStatus: '需要代理',
  pitfalls: ['需要人工引导', '复杂研究成功率有限', '成本较高'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '30.8k', release: 'v0.3.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};

export const superagi: ToolProfile = {
  slug: 'superagi',
  name: 'SuperAGI',
  tagline: 'Agent框架，16.2k stars',
  summary: 'SuperAGI 是一个Agent框架， 提供Agent开发、 部署、 管理等功能。支持多种模型、 适合Agent开发、 自动化等场景。',
  vendor: 'TransformerOptimus',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://superagi.com',
  githubUrl: 'https://github.com/TransformerOptimus/SuperAGI',
  docsUrl: 'https://docs.superagi.com',
  githubStars: 16200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'Agent框架',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['Agent开发', '自动化', '任务执行'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线', '文档较少', '社区规模小'],
  benchmark: { successRate: 75, avgDurationMin: 4.0, retries: 2.0 },
  community: { stars: '16.2k', release: 'v0.1.0', trend: '稳定' },
  rating: { security: 7.0, speed: 7.5, flexibility: 8.0, stability: 7.0, docs: 7.5 },
};

export const llamaindex: ToolProfile = {
  slug: 'llamaindex',
  name: 'LlamaIndex',
  tagline: '数据Agent框架，38.5k stars',
  summary: 'LlamaIndex 是一个数据Agent框架， 提供数据连接、 索引、 查询等功能。支持多种数据源、 适合RAG、 数据Agent等场景。',
  vendor: 'LlamaIndex',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '自部署'],
  homepageUrl: 'https://llamaindex.ai',
  githubUrl: 'https://github.com/run-llama/llama_index',
  docsUrl: 'https://docs.llamaindex.ai',
  githubStars: 38500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '数据Agent框架',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型', '多种数据源'],
  scenarios: ['RAG', '数据Agent', '知识库'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线', '配置复杂', '性能开销较大'],
  benchmark: { successRate: 82, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '38.5k', release: 'v0.10.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.0, flexibility: 9.0, stability: 8.0, docs: 9.0 },
};

export const haystack: ToolProfile = {
  slug: 'haystack',
  name: 'Haystack',
  tagline: 'NLP/Agent框架，19.2k stars',
  summary: 'Haystack 是一个NLP/Agent框架， 提供NLP管道、 Agent构建等功能。支持多种模型、 适合NLP应用、 Agent等场景。',
  vendor: 'deepset',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '自部署'],
  homepageUrl: 'https://haystack.deepset.ai',
  githubUrl: 'https://github.com/deepset-ai/haystack',
  docsUrl: 'https://docs.haystack.deepset.ai',
  githubStars: 19200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'NLP/Agent框架',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['NLP应用', 'Agent构建', 'RAG'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线', '配置复杂', '文档分散'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '19.2k', release: 'v2.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 7.5, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};

export const phidata: ToolProfile = {
  slug: 'phidata',
  name: 'Phidata',
  tagline: 'AI助手框架，15.8k stars',
  summary: 'Phidata 是一个AI助手框架， 提供助手构建、 部署、 管理等功能。支持多种模型、 适合AI助手、 Agent等场景。',
  vendor: 'Phidata',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://phidata.com',
  githubUrl: 'https://github.com/phidatahq/phidata',
  docsUrl: 'https://docs.phidata.com',
  githubStars: 15800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI助手框架',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['AI助手', 'Agent构建', '任务执行'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线', '文档较少', '社区规模小'],
  benchmark: { successRate: 78, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '15.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.0, stability: 7.5, docs: 8.0 },
};

export const memgpt: ToolProfile = {
  slug: 'memgpt',
  name: 'MemGPT',
  tagline: '有记忆Agent，12.5k stars',
  summary: 'MemGPT 是一个有记忆的Agent， 提供长期记忆、 自主执行等功能。支持多种模型、 适合长期任务、 记忆管理等场景。',
  vendor: 'Letta',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://memgpt.com',
  githubUrl: 'https://github.com/cpacker/memgpt',
  docsUrl: 'https://docs.memgpt.com',
  githubStars: 12500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '有记忆Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['长期任务', '记忆管理', 'Agent构建'],
  gfwStatus: '需要代理',
  pitfalls: ['记忆开销较大', '配置复杂', '文档较少'],
  benchmark: { successRate: 78, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '12.5k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 8.0 },
};

export const agentscope: ToolProfile = {
  slug: 'agentscope',
  name: 'AgentScope',
  tagline: '阿里多Agent，6.8k stars',
  summary: 'AgentScope 是阿里开发的多Agent框架， 提供多Agent协作、 任务编排等功能。支持多种模型、 适合多Agent场景。',
  vendor: 'Alibaba',
  sourceType: '开源',
  region: '国内',
  primaryCategory: '通用任务执行 Agent',
  tags: ['多角色协作', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://agentscope.io',
  githubUrl: 'https://github.com/modelscope/agentscope',
  docsUrl: 'https://agentscope.io/docs',
  githubStars: 6800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '阿里多Agent框架',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', 'Qwen', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '阿里云API', '本地模型'],
  scenarios: ['多Agent协作', '任务编排', 'Agent构建'],
  gfwStatus: '直连可用',
  pitfalls: ['阿里生态依赖', '文档较少', '社区规模小'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '6.8k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.0, stability: 8.0, docs: 8.0 },
};

export const miniagents: ToolProfile = {
  slug: 'miniagents',
  name: 'MiniAgents',
  tagline: '异步Agent框架，0.5k stars',
  summary: 'MiniAgents 是一个异步Agent框架， 提供异步执行、 任务编排等功能。支持多种模型、 适合异步任务、 Agent等场景。',
  vendor: 'Teremterem',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://github.com/teremterem/MiniAgents',
  githubUrl: 'https://github.com/teremterem/MiniAgents',
  docsUrl: 'https://github.com/teremterem/MiniAgents#readme',
  githubStars: 500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '异步Agent框架',
  deployment: 'Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['异步任务', 'Agent构建', '任务编排'],
  gfwStatus: '需要代理',
  pitfalls: ['文档较少', '社区规模小', '功能有限'],
  benchmark: { successRate: 75, avgDurationMin: 4.0, retries: 2.5 },
  community: { stars: '0.5k', release: 'v0.1.0', trend: '稳定' },
  rating: { security: 7.0, speed: 7.5, flexibility: 7.5, stability: 7.0, docs: 6.5 },
};

export const agentprotocol: ToolProfile = {
  slug: 'agentprotocol',
  name: 'AgentProtocol',
  tagline: 'Agent协议标准，1.8k stars',
  summary: 'AgentProtocol 是一个Agent协议标准， 提供Agent通信、 互操作等功能。适合Agent标准化、 互操作等场景。',
  vendor: 'AI Engineers Foundation',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://agentprotocol.ai',
  githubUrl: 'https://github.com/AI-Engineers-Foundation/agent-protocol',
  docsUrl: 'https://agentprotocol.ai/docs',
  githubStars: 1800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'Agent协议标准',
  deployment: 'Python Runtime',
  modelSupport: ['N/A'],
  connectivity: ['HTTP API'],
  scenarios: ['Agent标准化', '互操作', '协议实现'],
  gfwStatus: '直连可用',
  pitfalls: ['非Agent工具', '仅提供协议', '文档较少'],
  benchmark: { successRate: 85, avgDurationMin: 1.0, retries: 0.5 },
  community: { stars: '1.8k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.5, docs: 8.0 },
};

export const autogenstudio: ToolProfile = {
  slug: 'autogenstudio',
  name: 'AutoGen Studio',
  tagline: 'AutoGen可视化，3.2k stars',
  summary: 'AutoGen Studio 是AutoGen的可视化工具， 提供可视化Agent编排、 调试等功能。支持多种模型、 适合AutoGen可视化等场景。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['多角色协作', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://autogen.studio',
  githubUrl: 'https://github.com/microsoft/autogenstudio',
  docsUrl: 'https://autogen.studio/docs',
  githubStars: 3200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AutoGen可视化',
  deployment: 'Python Runtime, Web',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['AutoGen可视化', 'Agent编排', '调试'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖AutoGen', '功能有限', '文档较少'],
  benchmark: { successRate: 80, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '3.2k', release: 'v0.1.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 7.5, stability: 8.0, docs: 8.0 },
};

export const taskweaver: ToolProfile = {
  slug: 'taskweaver',
  name: 'TaskWeaver',
  tagline: '微软代码Agent，5.6k stars',
  summary: 'TaskWeaver 是微软开发的代码Agent， 提供代码生成、 执行等功能。支持多种模型、 适合代码任务、 自动化等场景。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://microsoft.github.io/TaskWeaver',
  githubUrl: 'https://github.com/microsoft/TaskWeaver',
  docsUrl: 'https://microsoft.github.io/TaskWeaver/docs',
  githubStars: 5600,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '微软代码Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', 'Azure OpenAI'],
  connectivity: ['OpenAI API', 'Azure OpenAI', '本地模型'],
  scenarios: ['代码任务', '自动化', '代码生成'],
  gfwStatus: '需要代理',
  pitfalls: ['微软生态依赖', '功能有限', '文档较少'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '5.6k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 7.5, stability: 8.0, docs: 8.0 },
};

export const agentllm: ToolProfile = {
  slug: 'agent-llm',
  name: 'Agent-LLM',
  tagline: '多模型Agent，4.8k stars',
  summary: 'Agent-LLM 是一个多模型Agent， 提供多模型集成、 任务执行等功能。支持多种模型、 适合多模型场景。',
  vendor: 'Josh XT',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://agent-llm.com',
  githubUrl: 'https://github.com/Josh-XT/Agent-LLM',
  docsUrl: 'https://agent-llm.com/docs',
  githubStars: 4800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '多模型Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['多模型场景', 'Agent构建', '任务执行'],
  gfwStatus: '需要代理',
  pitfalls: ['配置复杂', '文档较少', '社区规模小'],
  benchmark: { successRate: 75, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '4.8k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 7.5 },
};

export const openassistant: ToolProfile = {
  slug: 'openassistant',
  name: 'OpenAssistant',
  tagline: '开源助手，37.5k stars',
  summary: 'OpenAssistant 是一个开源助手项目， 提供助手构建、 部署等功能。支持多种模型、 适合开源助手、 AI应用等场景。',
  vendor: 'LAION',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://open-assistant.io',
  githubUrl: 'https://github.com/LAION-AI/Open-Assistant',
  docsUrl: 'https://open-assistant.io/docs',
  githubStars: 37500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '开源助手',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['开源助手', 'AI应用', '任务执行'],
  gfwStatus: '需要代理',
  pitfalls: ['项目维护不活跃', '文档较少', '功能有限'],
  benchmark: { successRate: 75, avgDurationMin: 4.0, retries: 2.5 },
  community: { stars: '37.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.0, flexibility: 8.0, stability: 7.5, docs: 7.5 },
};

export const privategpt: ToolProfile = {
  slug: 'privategpt',
  name: 'PrivateGPT',
  tagline: '私有GPT，54.2k stars',
  summary: 'PrivateGPT 是一个私有GPT解决方案， 提供本地部署、 私有化等功能。支持多种模型、 适合私有化、 本地部署等场景。',
  vendor: 'Zylon',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '自部署'],
  homepageUrl: 'https://privategpt.dev',
  githubUrl: 'https://github.com/zylon-ai/private-gpt',
  docsUrl: 'https://docs.privategpt.dev',
  githubStars: 54200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '私有GPT',
  deployment: 'Python Runtime, Docker, 本地部署',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型', 'LLaMA'],
  connectivity: ['本地运行', 'OpenAI API', '本地模型'],
  scenarios: ['私有化', '本地部署', 'RAG'],
  gfwStatus: '直连可用',
  pitfalls: ['资源占用较大', '配置复杂', '需要本地模型'],
  benchmark: { successRate: 82, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '54.2k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 8.5, speed: 7.5, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};

export const localgpt: ToolProfile = {
  slug: 'localgpt',
  name: 'LocalGPT',
  tagline: '本地GPT，20.5k stars',
  summary: 'LocalGPT 是一个本地GPT解决方案， 提供本地部署、 私有化等功能。支持多种模型、 适合本地部署、 私有化等场景。',
  vendor: 'Prompt Engineer',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '自部署'],
  homepageUrl: 'https://github.com/PromtEngineer/localGPT',
  githubUrl: 'https://github.com/PromtEngineer/localGPT',
  docsUrl: 'https://github.com/PromtEngineer/localGPT#readme',
  githubStars: 20500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '本地GPT',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型', 'LLaMA'],
  connectivity: ['本地运行', '本地模型'],
  scenarios: ['本地部署', '私有化', 'RAG'],
  gfwStatus: '直连可用',
  pitfalls: ['资源占用较大', '配置复杂', '需要本地模型'],
  benchmark: { successRate: 80, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '20.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 7.5, flexibility: 8.0, stability: 8.0, docs: 7.5 },
};

export const gpt4all: ToolProfile = {
  slug: 'gpt4all',
  name: 'GPT4All',
  tagline: '本地LLM，72.5k stars',
  summary: 'GPT4All 是一个本地LLM解决方案， 提供本地部署、 私有化等功能。支持多种模型、 适合本地部署、 私有化等场景。',
  vendor: 'Nomic AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://gpt4all.io',
  githubUrl: 'https://github.com/nomic-ai/gpt4all',
  docsUrl: 'https://docs.gpt4all.io',
  githubStars: 72500,
  primaryLanguage: 'C++',
  pricing: '免费开源',
  license: 'MIT',
  focus: '本地LLM',
  deployment: '桌面应用, 命令行',
  modelSupport: ['本地模型', 'LLaMA', 'Mistral', '多种开源模型'],
  connectivity: ['本地运行'],
  scenarios: ['本地部署', '私有化', '离线使用'],
  gfwStatus: '直连可用',
  pitfalls: ['模型能力有限', '资源占用较大', '需要本地模型'],
  benchmark: { successRate: 85, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '72.5k', release: 'v3.0.0', trend: '活跃' },
  rating: { security: 8.5, speed: 8.0, flexibility: 8.0, stability: 8.5, docs: 8.5 },
};

export const ollama: ToolProfile = {
  slug: 'ollama',
  name: 'Ollama',
  tagline: '本地模型运行，105.0k stars',
  summary: 'Ollama 是一个本地模型运行工具， 提供本地部署、 模型管理等功能。支持多种模型、 适合本地部署、 模型运行等场景。',
  vendor: 'Ollama',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://ollama.com',
  githubUrl: 'https://github.com/ollama/ollama',
  docsUrl: 'https://docs.ollama.com',
  githubStars: 105000,
  primaryLanguage: 'Go',
  pricing: '免费开源',
  license: 'MIT',
  focus: '本地模型运行',
  deployment: '命令行, Docker, 桌面应用',
  modelSupport: ['LLaMA', 'Mistral', 'DeepSeek R1', '多种开源模型'],
  connectivity: ['本地运行', 'API服务'],
  scenarios: ['本地部署', '模型运行', '私有化'],
  gfwStatus: '直连可用',
  pitfalls: ['需要本地模型', '资源占用较大', 'GPU推荐'],
  benchmark: { successRate: 90, avgDurationMin: 1.5, retries: 0.5 },
  community: { stars: '105.0k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 8.5, speed: 9.0, flexibility: 9.0, stability: 9.0, docs: 9.0 },
};

export const jan: ToolProfile = {
  slug: 'jan',
  name: 'Jan',
  tagline: '本地AI助手，22.5k stars',
  summary: 'Jan 是一个本地AI助手， 提供本地部署、 私有化等功能。支持多种模型、 适合本地部署、 私有化等场景。',
  vendor: 'Jan',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://jan.ai',
  githubUrl: 'https://github.com/janhq/jan',
  docsUrl: 'https://docs.jan.ai',
  githubStars: 22500,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'AGPL-3.0',
  focus: '本地AI助手',
  deployment: '桌面应用, 移动应用',
  modelSupport: ['本地模型', 'LLaMA', 'Mistral', '多种开源模型'],
  connectivity: ['本地运行'],
  scenarios: ['本地部署', '私有化', '离线使用'],
  gfwStatus: '直连可用',
  pitfalls: ['模型能力有限', '资源占用较大', '需要本地模型'],
  benchmark: { successRate: 82, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '22.5k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 8.5, speed: 8.0, flexibility: 8.0, stability: 8.0, docs: 8.5 },
};

export const anythingllm: ToolProfile = {
  slug: 'anythingllm',
  name: 'AnythingLLM',
  tagline: '本地RAG，28.5k stars',
  summary: 'AnythingLLM 是一个本地RAG解决方案， 提供本地部署、 RAG等功能。支持多种模型、 适合本地部署、 RAG等场景。',
  vendor: 'Mintplex Labs',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '自部署'],
  homepageUrl: 'https://useanything.com',
  githubUrl: 'https://github.com/Mintplex-Labs/anything-llm',
  docsUrl: 'https://docs.useanything.com',
  githubStars: 28500,
  primaryLanguage: 'JavaScript',
  pricing: '免费开源',
  license: 'MIT',
  focus: '本地RAG',
  deployment: 'Docker, 桌面应用',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型', 'LLaMA'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['本地部署', 'RAG', '知识库'],
  gfwStatus: '直连可用',
  pitfalls: ['配置复杂', '资源占用较大', '需要本地模型'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '28.5k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};

export const danswer: ToolProfile = {
  slug: 'danswer',
  name: 'Danswer',
  tagline: '企业问答，8.5k stars',
  summary: 'Danswer 是一个企业问答解决方案， 提供企业知识库、 问答等功能。支持多种模型、 适合企业问答、 知识库等场景。',
  vendor: 'Danswer',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '企业流程'],
  homepageUrl: 'https://danswer.ai',
  githubUrl: 'https://github.com/danswer-ai/danswer',
  docsUrl: 'https://docs.danswer.ai',
  githubStars: 8500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '企业问答',
  deployment: 'Docker, Kubernetes',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['企业问答', '知识库', 'RAG'],
  gfwStatus: '需要代理',
  pitfalls: ['配置复杂', '企业部署成本', '文档较少'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '8.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.0, stability: 8.0, docs: 8.0 },
};

export const khoj: ToolProfile = {
  slug: 'khoj',
  name: 'Khoj',
  tagline: 'AI助手，15.2k stars',
  summary: 'Khoj 是一个AI助手， 提供个人知识库、 问答等功能。支持多种模型、 适合个人助手、 知识库等场景。',
  vendor: 'Khoj',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', 'RAG', '开源', '个人助手'],
  homepageUrl: 'https://khoj.dev',
  githubUrl: 'https://github.com/khoj-ai/khoj',
  docsUrl: 'https://docs.khoj.dev',
  githubStars: 15200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'AGPL-3.0',
  focus: 'AI助手',
  deployment: 'Python Runtime, Docker, 桌面应用',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['个人助手', '知识库', 'RAG'],
  gfwStatus: '需要代理',
  pitfalls: ['配置复杂', '资源占用较大', '文档较少'],
  benchmark: { successRate: 78, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '15.2k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 8.0 },
};

export const perplexica: ToolProfile = {
  slug: 'perplexica',
  name: 'Perplexica',
  tagline: '开源Perplexity，12.8k stars',
  summary: 'Perplexica 是一个开源的Perplexity替代品， 提供AI搜索、 问答等功能。支持多种模型、 适合AI搜索、 问答等场景。',
  vendor: 'ItzCrazyKns',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '自部署', '个人助手'],
  homepageUrl: 'https://perplexica.ai',
  githubUrl: 'https://github.com/ItzCrazyKns/Perplexica',
  docsUrl: 'https://docs.perplexica.ai',
  githubStars: 12800,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'MIT',
  focus: '开源Perplexity',
  deployment: 'Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型', 'SearXNG'],
  scenarios: ['AI搜索', '问答', '知识库'],
  gfwStatus: '需要代理',
  pitfalls: ['需要SearXNG', '配置复杂', '资源占用较大'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 1.5 },
  community: { stars: '12.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.0, stability: 8.0, docs: 8.0 },
};

// 导出所有产品
export const generalAgentProducts: ToolProfile[] = [
  agentgpt,
  gptresearcher,
  superagi,
  llamaindex,
  haystack,
  phidata,
  memgpt,
  agentscope,
  miniagents,
  agentprotocol,
  autogenstudio,
  taskweaver,
  agentllm,
  openassistant,
  privategpt,
  localgpt,
  gpt4all,
  ollama,
  jan,
  anythingllm,
  danswer,
  khoj,
  perplexica,
];
