import type { ToolProfile } from '@/lib/tools/types';

export const githubCopilotWorkspace: ToolProfile = {
  slug: 'github-copilot-workspace',
  name: 'GitHub Copilot Workspace',
  tagline: 'GitHub Copilot 的全流程开发平台',
  summary: 'GitHub Copilot Workspace 是 GitHub 推出的全流程 AI 开发平台，从需求到 PR 一体化，支持任务规划、代码生成、测试编写，适合团队提升开发效率。',
  vendor: 'GitHub',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '代码生成', '商业软件', '开发工具', '企业流程'],
  homepageUrl: 'https://github.com/features/copilot/workspace',
  githubUrl: null,
  docsUrl: 'https://docs.github.com/copilot',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制，包含在 Copilot 套餐',
  license: '商业许可',
  focus: '全流程开发、任务规划、代码生成',
  deployment: '云平台 + VS Code 扩展',
  modelSupport: ['GPT-4', 'Codex', 'GitHub 自研模型'],
  connectivity: ['GitHub API', 'VS Code 集成', 'CLI 工具'],
  scenarios: ['需求到 PR', '代码生成', '测试编写', 'Bug 修复'],
  gfwStatus: '需要代理',
  pitfalls: ['代码外发合规风险', '需 GitHub 账号'],
  benchmark: { successRate: 88, avgDurationMin: 5.0, retries: 1.2 },
  community: { stars: null, release: 'Preview', trend: '快速增长' },
  rating: { security: 8.5, speed: 8.8, flexibility: 9.0, stability: 8.5, docs: 8.8 },
};
