import type { ToolProfile } from '@/lib/tools/types';

export const glmclaw: ToolProfile = {
  slug: 'glmclaw',
  name: 'GLMClaw',
  tagline: '智谱 AI GLM 企业智能体 Claw 服务',
  summary: '基于 GLM-4 大模型的代码能力 OpenClaw 云服务。',
  vendor: '智谱 AI',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '研发提效', '代码生成'],
  homepageUrl: 'https://glmclaw.zhipuai.cn',
  githubUrl: null,
  docsUrl: 'https://open.bigmodel.cn/docs/glmclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: 'API 计费',
  license: '商业闭源',
  focus: 'GLM-4 大模型、代码能力、企业智能体',
  deployment: '智谱云托管',
  modelSupport: ['GLM-4', 'GLM-4-Plus', 'GLM 系列'],
  connectivity: ['智谱云服务', 'API 访问'],
  scenarios: ['代码生成', '企业智能体', '研发提效'],
  gfwStatus: '直连可用',
  pitfalls: ['生态成熟度仍在完善', '复杂多 Agent 场景能力边界需验证', '跨平台可移植性较弱'],
  benchmark: { successRate: 81, avgDurationMin: 6.5, retries: 1.6 },
  community: { stars: '官方服务', release: '持续更新', trend: '政企试点增加' },
  rating: { security: 8.0, speed: 8.2, flexibility: 7.5, stability: 7.8, docs: 7.5 },
};
