import type { ToolProfile } from '@/lib/tools/types';

export const gptResearcher: ToolProfile = {
  slug: 'gpt-researcher',
  name: 'GPT-Researcher',
  tagline: 'AI 驱动的研究助手，自动生成深度报告',
  summary: 'GPT-Researcher 是一款专注于自动研究的 AI Agent，能够自主搜索、筛选、总结信息，生成结构化的研究报告。',
  vendor: 'Assaf Elovic',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['数据自动化', '研究助手', '开源', '信息搜集', '报告生成'],
  homepageUrl: 'https://gptr.dev',
  githubUrl: 'https://github.com/assafelovic/gpt-researcher',
  docsUrl: 'https://docs.gptr.dev',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '自动信息搜集、内容筛选、报告生成',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'GPT-3.5', '支持本地模型'],
  connectivity: ['Web 搜索 API', '本地文件系统', 'PDF 导出'],
  scenarios: ['市场调研', '竞品分析', '学术研究', '新闻摘要'],
  gfwStatus: '需要代理',
  pitfalls: ['搜索结果依赖外部 API', '中文搜索能力有限'],
  benchmark: { successRate: 80, avgDurationMin: 12.0, retries: 1.5 },
  community: { stars: '30.8k', release: 'v0.9.0', trend: '快速增长' },
  rating: { security: 7.8, speed: 7.5, flexibility: 8.2, stability: 7.6, docs: 8.0 },
};
