import type { ToolProfile } from '@/lib/tools/types';

export const gptengineer: ToolProfile = {
  slug: 'gpt-engineer',
  name: 'GPT-Engineer',
  tagline: 'AI代码生成，52.1k stars',
  summary: 'GPT-Engineer 是一个AI代码生成工具，能够根据自然语言描述生成完整的代码库。支持多种编程语言，适合快速原型开发、代码生成、项目初始化等场景。',
  vendor: 'GPT-Engineer Org',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://gptengineer.app',
  githubUrl: 'https://github.com/gpt-engineer-org/gpt-engineer',
  docsUrl: 'https://docs.gptengineer.app',
  lastReleaseDate: "2024-06-06T18:25:22Z",
  latestVersion: "v0.3.1",
  lastCommitDate: "2025-05-14T10:15:10Z",
  githubStars: 55232,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI代码生成工具',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码生成', '快速原型', '项目初始化', '代码库生成'],
  gfwStatus: '需要代理',
  pitfalls: ['生成代码需审查', '复杂项目成功率有限', '需要人工优化'],
  benchmark: { successRate: 80, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '52.1k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.0, speed: 8.0, flexibility: 8.5, stability: 7.5, docs: 8.0 },
};
