import type { ToolProfile } from '@/lib/tools/types';

export const gpt4all: ToolProfile = {
  slug: 'gpt4all',
  name: 'GPT4All',
  tagline: '在本地 CPU 上运行的大语言模型',
  summary: 'GPT4All 是一款可以在本地 CPU 上运行的大语言模型应用，无需 GPU，提供聊天、文档处理、代码生成等能力。',
  vendor: 'Nomic AI',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['本地优先', '开源', '个人助手', '多模态'],
  homepageUrl: 'https://gpt4all.io',
  githubUrl: 'https://github.com/nomic-ai/gpt4all',
  docsUrl: 'https://docs.gpt4all.io',
  githubStars: 72500,
  primaryLanguage: 'C++',
  pricing: '免费开源',
  license: 'MIT',
  focus: '本地 LLM 推理、CPU 优化、离线使用',
  deployment: '桌面应用 + Python 库',
  modelSupport: ['GPT4All 自研模型', '支持 GGUF 格式'],
  connectivity: ['本地 API', '桌面应用', 'Python SDK'],
  scenarios: ['个人助手', '离线聊天', '文档处理', '代码生成'],
  gfwStatus: '需要代理',
  pitfalls: ['模型下载需网络', '推理速度依赖硬件'],
  benchmark: { successRate: 78, avgDurationMin: 3.8, retries: 1.3 },
  community: { stars: '72.5k', release: 'v3.8.0', trend: '活跃增长' },
  rating: { security: 8.5, speed: 7.0, flexibility: 8.0, stability: 8.2, docs: 7.8 },
};
