import type { ToolProfile } from '@/lib/tools/types';

export const gpt4free: ToolProfile = {
  slug: 'gpt4free',
  name: 'GPT4Free',
  tagline: '多模型聚合的免费 AI 平台',
  summary: 'GPT4Free 是一款多模型聚合平台，整合了多个免费的 AI 模型接口，提供统一的访问方式，适合预算有限的开发者和用户。',
  vendor: 'xtekky',
  sourceType: '开源',
  region: '海外',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['开源', '多模态', '个人助手', '开发工具'],
  homepageUrl: null,
  githubUrl: 'https://github.com/xtekky/gpt4free',
  docsUrl: null,
  githubStars: 65841,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'GPL-3.0',
  focus: '多模型聚合、免费访问、API 统一',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'Claude', 'Gemini', '支持 20+ 模型'],
  connectivity: ['REST API', 'Python SDK'],
  scenarios: ['个人学习', '原型开发', '模型测试', '预算有限场景'],
  gfwStatus: '需要代理',
  pitfalls: ['接口稳定性依赖第三方', '仅供学习研究使用'],
  benchmark: { successRate: 65, avgDurationMin: 8.0, retries: 2.5 },
  community: { stars: '65k', release: 'v1.2.0', trend: '活跃增长' },
  rating: { security: 6.0, speed: 6.5, flexibility: 8.5, stability: 5.5, docs: 6.0 },
};
