import type { ToolProfile } from '@/lib/tools/types';

export const guiagent: ToolProfile = {
  slug: 'guiagent',
  name: 'GUIAgent',
  tagline: 'GUI自动化Agent，1.2k stars',
  summary: 'GUIAgent 是一个GUI自动化Agent，能够通过视觉理解自动操作GUI元素。支持多模型、 适合GUI自动化、 测试自动化等场景。',
  vendor: 'GUIAgent AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/GUIAgent/GUIAgent',
  githubUrl: 'https://github.com/GUIAgent/GUIAgent',
  docsUrl: 'https://github.com/GUIAgent/GUIAgent#readme',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: 'GUI自动化',
  deployment: 'Python Runtime, Desktop',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['GUI自动化', '测试自动化', '任务自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限桌面场景', '需要桌面环境', '复杂GUI支持有限'],
  benchmark: { successRate: 68, avgDurationMin: 6.5, retries: 3.2 },
  community: { stars: '1.2k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 6.5, speed: 6.0, flexibility: 7.0, stability: 6.0, docs: 6.0 },
};
