import type { ToolProfile } from '@/lib/tools/types';

export const gumloop: ToolProfile = {
  slug: 'gumloop',
  name: 'Gumloop',
  tagline: 'AI 工作流自动化平台',
  summary: 'Gumloop 是一款 AI 驱动的工作流自动化平台，提供可视化流程设计和 AI 节点，适合企业快速构建智能业务流程。',
  vendor: 'Gumloop Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['AI', '工作流自动化', '商业软件', '可视化编排', '企业流程'],
  homepageUrl: 'https://gumloop.com',
  githubUrl: null,
  docsUrl: 'https://docs.gumloop.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业许可',
  focus: 'AI 工作流、可视化设计、企业集成',
  deployment: '云服务平台',
  modelSupport: ['GPT-4', 'Claude', '多模型支持'],
  connectivity: ['REST API', 'Webhook', '第三方集成'],
  scenarios: ['市场营销', '销售自动化', '客户服务', '运营流程'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线陡峭', '定价较高'],
  benchmark: { successRate: 84, avgDurationMin: 5.0, retries: 1.4 },
  community: { stars: null, release: '持续更新', trend: '快速增长' },
  rating: { security: 8.5, speed: 8.0, flexibility: 8.8, stability: 8.0, docs: 7.8 },
};
