import type { ToolProfile } from '@/lib/tools/types';

export const haystack: ToolProfile = {
  slug: 'haystack',
  name: 'Haystack',
  tagline: '开源 NLP 和搜索框架',
  summary: 'Haystack 是 deepset 推出的开源 NLP 框架，提供语义搜索、问答系统、文档检索等能力，适合构建企业级知识检索应用。',
  vendor: 'deepset',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['RAG', '数据自动化', '开源', '知识库', 'NLP'],
  homepageUrl: 'https://haystack.deepset.ai',
  githubUrl: 'https://github.com/deepset-ai/haystack',
  docsUrl: 'https://docs.haystack.deepset.ai',
  githubStars: 19200,
  primaryLanguage: 'Python',
  pricing: '免费开源，云服务付费',
  license: 'Apache-2.0',
  focus: '语义搜索、问答系统、文档检索',
  deployment: 'Python 包，支持 Docker 部署',
  modelSupport: ['Transformer 模型', '支持 HuggingFace 全量模型'],
  connectivity: ['Elasticsearch', '向量数据库', 'REST API'],
  scenarios: ['企业搜索', '智能客服', '知识管理', '文档问答'],
  gfwStatus: '直连可用',
  pitfalls: ['需要自行部署向量后端', '中文模型需自行选择'],
  benchmark: { successRate: 83, avgDurationMin: 4.2, retries: 1.3 },
  community: { stars: '19.2k', release: 'v2.9.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.8, flexibility: 8.5, stability: 8.0, docs: 8.2 },
};
