import type { ToolProfile } from '@/lib/tools/types';

export const herokuclaw: ToolProfile = {
  slug: 'herokuclaw',
  name: 'Heroku Claw',
  tagline: 'Heroku PaaS Claw 服务',
  summary: '简单部署、dyno 计费的 OpenClaw 云服务。',
  vendor: 'Salesforce',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://herokuclaw.heroku.com',
  githubUrl: null,
  docsUrl: 'https://devcenter.heroku.com/herokuclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按 dyno 计费',
  license: '商业闭源',
  focus: '简单部署、PaaS 平台、开发者友好',
  deployment: 'Heroku 托管',
  modelSupport: ['Heroku 模型', '自定义模型'],
  connectivity: ['Heroku 服务', 'API 访问'],
  scenarios: ['快速原型验证', '开发者场景', 'MVP 原型'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 84, avgDurationMin: 6.0, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '开发者采用稳定' },
  rating: { security: 9.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.0 },
};
