import type { ToolProfile } from '@/lib/tools/types';

export const hiveclaw: ToolProfile = {
  slug: 'hiveclaw',
  name: 'HiveClaw',
  tagline: 'AI 代理技能经济平台',
  summary: 'HiveClaw 是 AI 代理的技能经济市场平台。用户可以发现、购买和出售强大的 AI 代理技能。开发者可以构建工具并在每笔销售中获得 95% 的收益。提供技能展示、交易管理和收藏功能。',
  vendor: 'Hive',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: '应用平台 / 工作流平台',
  tags: ['AI 平台', '开发者工具', 'API 集成', 'Web3', '社区生态', '插件生态'],
  homepageUrl: 'https://hiveclaw.com/',
  githubUrl: null,
  docsUrl: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费 + 交易分成',
  license: '专有',
  focus: '技能市场、开发者收益、AI 代理工具、技能发现',
  deployment: '云服务，需要钱包连接',
  modelSupport: ['AI Agents', '多技能支持'],
  connectivity: ['钱包集成', '技能 API', '交易市场'],
  scenarios: ['技能购买', '技能开发', '工具销售', 'AI 代理增强'],
  gfwStatus: '需要代理',
  pitfalls: ['需要加密货币钱包', '平台处于早期阶段'],
  benchmark: { successRate: 85, avgDurationMin: 3.0, retries: 1.0 },
  community: { stars: null, release: 'v1.0.0', trend: '早期开发' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.5, stability: 7.0, docs: 6.5 },
};
