import type { ToolProfile } from '@/lib/tools/types';

export const hunyuanclaw: ToolProfile = {
  slug: 'hunyuanclaw',
  name: 'HunyuanClaw',
  tagline: '腾讯云混元 Claw 平台服务',
  summary: '基于混元大模型、微信生态的 OpenClaw 云服务。',
  vendor: '腾讯云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://hunyuanclaw.tencent.com',
  githubUrl: null,
  docsUrl: 'https://cloud.tencent.com/docs/hunyuanclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按量计费',
  license: '商业闭源',
  focus: '混元大模型、微信生态、智能体平台',
  deployment: '腾讯云托管',
  modelSupport: ['混元系列', 'Hunyuan 大模型'],
  connectivity: ['腾讯云服务', '微信集成', 'API 访问'],
  scenarios: ['微信生态', '个人助手', '企业流程'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖腾讯生态', '跨平台支持有限', '企业功能待完善'],
  benchmark: { successRate: 84, avgDurationMin: 5.5, retries: 1.3 },
  community: { stars: '官方服务', release: '持续迭代', trend: '微信场景采用增长' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};
