import type { ToolProfile } from '@/lib/tools/types';

export const ibmclaw: ToolProfile = {
  slug: 'ibmclaw',
  name: 'IBM Claw',
  tagline: 'IBM watsonx Orchestrate Claw 服务',
  summary: '企业自动化、watsonx 生态的 OpenClaw 云服务。',
  vendor: 'IBM',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://ibmclaw.ibm.com',
  githubUrl: null,
  docsUrl: 'https://docs.ibm.com/ibmclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业定价',
  license: '商业闭源',
  focus: 'watsonx 生态、企业自动化、合规场景',
  deployment: 'IBM Cloud 托管',
  modelSupport: ['watsonx', 'Granite', 'IBM 模型'],
  connectivity: ['IBM Cloud 服务', 'API 访问'],
  scenarios: ['企业自动化', '合规场景', '金融行业'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 83, avgDurationMin: 6.5, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '政企客户增长稳定' },
  rating: { security: 9.0, speed: 8.0, flexibility: 7.0, stability: 8.5, docs: 8.0 },
};
