import type { ToolProfile } from '@/lib/tools/types';

export const ifttt: ToolProfile = {
  slug: 'ifttt',
  name: 'IFTTT',
  tagline: '简单的 If This Then That 自动化服务',
  summary: 'IFTTT 是一款简单易懂的自动化服务，提供 Applet 模式的触发器 - 动作流程，适合个人用户和小微企业快速实现轻量级自动化。',
  vendor: 'IFTTT Inc',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '个人助手', '轻量级', '商业软件', 'IoT'],
  homepageUrl: 'https://ifttt.com',
  githubUrl: null,
  docsUrl: 'https://help.ifttt.com',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Pro $5/月',
  license: '商业许可',
  focus: '简单自动化、IoT 集成、移动应用',
  deployment: '云服务平台',
  modelSupport: ['基础 AI 功能'],
  connectivity: ['800+ 服务集成', 'IoT 设备', '移动应用'],
  scenarios: ['智能家居', '社交媒体同步', '通知推送', '天气提醒'],
  gfwStatus: '需要代理',
  pitfalls: ['功能相对基础', '复杂场景不支持'],
  benchmark: { successRate: 82, avgDurationMin: 2.5, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '稳定维护' },
  rating: { security: 7.8, speed: 8.5, flexibility: 7.0, stability: 8.2, docs: 7.5 },
};
