import type { ToolProfile } from '@/lib/tools/types';

export const instructcode: ToolProfile = {
  slug: 'instructcode',
  name: 'InstructCode',
  tagline: '指令代码生成，1.2k stars',
  summary: 'InstructCode 是一个指令驱动的代码生成工具，提供代码生成、代码补全等功能。支持多种模型，适合快速原型开发。',
  vendor: 'InstructLab',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://github.com/instructlab/instructcode',
  githubUrl: 'https://github.com/instructlab/instructcode',
  docsUrl: 'https://github.com/instructlab/instructcode#readme',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '指令代码生成',
  deployment: 'Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码生成', '快速原型', '项目初始化'],
  gfwStatus: '需要代理',
  pitfalls: ['功能精简', '复杂项目支持有限', '文档较少'],
  benchmark: { successRate: 75, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '1.2k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.5, flexibility: 7.5, stability: 7.5, docs: 7.0 },
};
