import type { ToolProfile } from '@/lib/tools/types';

export const ironclaw: ToolProfile = {
  slug: 'ironclaw',
  name: 'IronClaw',
  tagline: 'Rust 实现的隐私安全 OpenClaw',
  summary: 'IronClaw 是一个受 OpenClaw 启发的 Rust 实现，专注于隐私和安全。提供高性能、内存安全和系统级保护。支持 Apache-2.0 和 MIT 双重许可。',
  vendor: 'nearai',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', 'Rust', '安全', '隐私保护', '跨平台', 'Linux'],
  homepageUrl: 'https://www.ironclaw.com',
  githubUrl: 'https://github.com/nearai/ironclaw',
  docsUrl: 'https://github.com/nearai/ironclaw#readme',
  githubStars: 10700,
  primaryLanguage: 'Rust',
  pricing: '免费开源',
  license: 'Apache-2.0 / MIT',
  focus: '隐私安全、Rust 实现、高性能、系统级保护',
  deployment: '本地部署，支持编译运行',
  modelSupport: ['OpenClaw 兼容', '多模型支持'],
  connectivity: ['本地运行', 'API 集成', '工具调用'],
  scenarios: ['安全 AI 代理', '隐私保护场景', '高性能需求', '系统级集成'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 Rust 知识', '编译时间较长'],
  benchmark: { successRate: 92, avgDurationMin: 3.0, retries: 1.0 },
  community: { stars: '10.7k', release: 'v1.0.0', trend: '活跃开发' },
  rating: { security: 9.5, speed: 9.5, flexibility: 8.0, stability: 9.0, docs: 8.0 },
};
