import type { ToolProfile } from '@/lib/tools/types';

export const jan: ToolProfile = {
  slug: 'jan',
  name: 'Jan',
  tagline: '开源的本地 AI 助手平台',
  summary: 'Jan 是一款开源的本地 AI 助手平台，提供美观的 UI 界面和本地模型管理能力，支持多种开源模型，是完全本地的 ChatGPT 替代方案。',
  vendor: 'Jan AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['本地优先', '开源', '个人助手', '多模态'],
  homepageUrl: 'https://jan.ai',
  githubUrl: 'https://github.com/janhq/jan',
  docsUrl: 'https://jan.ai/docs',
  githubStars: 22500,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'AGPL-3.0',
  focus: '本地 AI 助手、模型管理、美观 UI',
  deployment: '桌面应用，跨平台支持',
  modelSupport: ['Llama', 'Mistral', '支持 GGUF 格式模型'],
  connectivity: ['本地 API', '桌面应用', 'REST API'],
  scenarios: ['个人助手', '离线聊天', '本地开发', '知识问答'],
  gfwStatus: '需要代理',
  pitfalls: ['模型下载需网络', '内存占用较高'],
  benchmark: { successRate: 80, avgDurationMin: 3.2, retries: 1.3 },
  community: { stars: '22.5k', release: 'v0.6.0', trend: '快速增长' },
  rating: { security: 8.5, speed: 7.5, flexibility: 8.2, stability: 7.8, docs: 8.0 },
};
