import type { ToolProfile } from '@/lib/tools/types';

export const jetbrainsAI: ToolProfile = {
  slug: 'jetbrains-ai',
  name: 'JetBrains AI',
  tagline: 'JetBrains IDE 集成 AI 助手',
  summary: 'JetBrains AI 是 JetBrains 官方推出的 AI 助手，深度集成在 IntelliJ IDEA、PyCharm 等 IDE 中，提供代码生成、重构、解释能力。',
  vendor: 'JetBrains',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', 'IDE 集成', '商业软件', '开发工具', '代码补全'],
  homepageUrl: 'https://jetbrains.com/ai',
  githubUrl: null,
  docsUrl: 'https://jetbrains.com/help/ai',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制，包含在 All Products Pack',
  license: '商业许可',
  focus: 'IDE 深度集成、代码理解、智能重构',
  deployment: 'IDE 插件',
  modelSupport: ['自研模型', '多模型支持'],
  connectivity: ['IDE 原生集成', '本地项目', '云同步'],
  scenarios: ['日常开发', '代码重构', '调试', '代码审查'],
  gfwStatus: '直连可用',
  pitfalls: ['需 JetBrains 订阅', '部分功能需联网'],
  benchmark: { successRate: 88, avgDurationMin: 3.0, retries: 1.2 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.8, speed: 8.5, flexibility: 8.8, stability: 9.0, docs: 9.0 },
};
