import type { ToolProfile } from '@/lib/tools/types';

export const khoj: ToolProfile = {
  slug: 'khoj',
  name: 'Khoj',
  tagline: '你的第二大脑 AI 助手',
  summary: 'Khoj 是一款开源的 AI 助手，支持个人知识库管理、日程提醒、文档问答，可以作为 Obsidian、Emacs 等工具的 AI 插件使用。',
  vendor: 'Khoj AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['RAG', '开源', '个人助手', '知识库', '开发工具'],
  homepageUrl: 'https://khoj.dev',
  githubUrl: 'https://github.com/khoj-ai/khoj',
  docsUrl: 'https://docs.khoj.dev',
  lastReleaseDate: "2026-02-22T20:00:23Z",
  latestVersion: "2.0.0-beta.25",
  lastCommitDate: "2026-03-19T19:28:44Z",
  githubStars: 33574,
  primaryLanguage: "Python",
  pricing: '免费开源，云服务付费',
  license: 'AGPL-3.0',
  focus: '个人知识管理、文档问答、日程提醒',
  deployment: 'Python 包，支持 Docker 部署',
  modelSupport: ['GPT-4', 'Claude', '支持本地模型'],
  connectivity: ['Obsidian 插件', 'Emacs 插件', 'REST API', 'Web 界面'],
  scenarios: ['个人知识管理', '文档检索', '日程管理', '笔记增强'],
  gfwStatus: '直连可用',
  pitfalls: ['配置需要一定技术门槛', '部分功能需云服务'],
  benchmark: { successRate: 79, avgDurationMin: 4.0, retries: 1.4 },
  community: { stars: '15.2k', release: 'v1.26.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.6, flexibility: 8.5, stability: 7.8, docs: 8.0 },
};
