import type { ToolProfile } from '@/lib/tools/types';

export const kimiclaw: ToolProfile = {
  slug: 'kimiclaw',
  name: 'KimiClaw',
  tagline: '月之暗面 Kimi 企业版 Claw 服务',
  summary: '基于 Kimi 大模型的长文本处理 OpenClaw 云服务。',
  vendor: '月之暗面',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://kimiclaw.moonshot.cn',
  githubUrl: null,
  docsUrl: 'https://platform.moonshot.cn/docs/kimiclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: 'API 计费',
  license: '商业闭源',
  focus: 'Kimi 大模型、长文本处理、个人助手',
  deployment: '月之暗面托管',
  modelSupport: ['Kimi', 'Moonshot 系列'],
  connectivity: ['月之暗面服务', 'API 访问'],
  scenarios: ['长文本分析', '个人助手', '知识问答'],
  gfwStatus: '直连可用',
  pitfalls: ['企业功能待完善', '生态集成有限', '定制能力受限'],
  benchmark: { successRate: 83, avgDurationMin: 6.0, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '个人用户增长稳定' },
  rating: { security: 8.0, speed: 8.2, flexibility: 7.0, stability: 8.0, docs: 7.5 },
};
