import type { ToolProfile } from '@/lib/tools/types';

export const komo: ToolProfile = {
  slug: 'komo',
  name: 'Komo',
  tagline: 'AI 驱动的信息搜索平台',
  summary: 'Komo 是一款 AI 驱动的信息搜索平台，提供智能搜索、总结、溯源能力，支持多语言搜索和个性化推荐。',
  vendor: 'Komo',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI 搜索', '信息搜集', '商业软件', '个人助手'],
  homepageUrl: 'https://komo.ai',
  githubUrl: null,
  docsUrl: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费订阅',
  license: '商业许可',
  focus: 'AI 搜索、信息总结、个性化推荐',
  deployment: 'Web 应用 + 浏览器扩展',
  modelSupport: ['GPT-4', 'Claude', '多模型'],
  connectivity: ['Web 界面', '浏览器扩展'],
  scenarios: ['信息搜集', '市场调研', '学习研究', '新闻摘要'],
  gfwStatus: '需要代理',
  pitfalls: ['功能相对基础', '高级功能需付费'],
  benchmark: { successRate: 82, avgDurationMin: 4.5, retries: 1.4 },
  community: { stars: null, release: '持续更新', trend: '稳定维护' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.2, docs: 7.5 },
};
