import type { ToolProfile } from '@/lib/tools/types';

export const langserve: ToolProfile = {
  slug: 'langserve',
  name: 'LangServe',
  tagline: 'LangChain 部署工具',
  summary: 'LangServe 是 LangChain 官方推出的部署工具，提供一键式 API 发布和远程调用能力，适合将 LangChain 应用快速部署到生产环境。',
  vendor: 'LangChain',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['开源', '开发工具', '部署', 'API', 'LangChain 生态'],
  homepageUrl: 'https://python.langchain.com/docs/langserve',
  githubUrl: 'https://github.com/langchain-ai/langserve',
  docsUrl: 'https://python.langchain.com/docs/langserve',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: 'LangChain 部署、API 发布、远程调用',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['LangChain 支持的所有模型'],
  connectivity: ['REST API', 'Playground', 'SDK 客户端'],
  scenarios: ['生产部署', 'API 服务', '团队协作', '原型验证'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖 LangChain 版本', '功能相对单一'],
  benchmark: { successRate: 82, avgDurationMin: 2.5, retries: 1.2 },
  community: { stars: '2.5k', release: 'v0.2.0', trend: '稳定维护' },
  rating: { security: 8.0, speed: 8.2, flexibility: 7.8, stability: 8.0, docs: 8.2 },
};
