import type { ToolProfile } from '@/lib/tools/types';

export const langflow: ToolProfile = {
  slug: 'langflow',
  name: 'LangFlow',
  tagline: '可视化的 LangChain 开发工具',
  summary: 'LangFlow 是一款可视化的 LangChain 开发工具，提供实时原型设计和 Python 代码导出能力，是 LangChain 官方推荐的可视化开发平台。',
  vendor: 'Langflow AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['可视化编排', '开源', '低代码', '开发工具', '企业流程'],
  homepageUrl: 'https://langflow.org',
  githubUrl: 'https://github.com/langflow-ai/langflow',
  docsUrl: 'https://docs.langflow.org',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源，云服务付费',
  license: 'MIT',
  focus: '可视化 LangChain、实时原型、代码导出',
  deployment: 'Python 包，支持 Docker 部署',
  modelSupport: ['GPT-4', 'Claude', '支持 LangChain 全量模型'],
  connectivity: ['REST API', 'WebSocket', 'Python SDK'],
  scenarios: ['LLM 应用开发', '原型设计', '教学演示', '企业工作流'],
  gfwStatus: '直连可用',
  pitfalls: ['与 LangChain 版本绑定', '复杂流程性能需优化'],
  benchmark: { successRate: 82, avgDurationMin: 5.0, retries: 1.4 },
  community: { stars: '38.5k', release: 'v1.1.0', trend: '快速增长' },
  rating: { security: 7.8, speed: 7.8, flexibility: 9.0, stability: 8.0, docs: 8.2 },
};
