import type { ToolProfile } from '@/lib/tools/types';

export const langchain: ToolProfile = {
  slug: 'langchain',
  name: 'LangChain',
  tagline: 'LLM应用框架，102.0k stars',
  summary: 'LangChain 是一个强大的LLM应用开发框架，提供了构建AI应用所需的各种组件和工具。支持多种模型、向量数据库、Agent编排，是AI应用开发的基础设施。',
  vendor: 'LangChain',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['工作流编排', 'RAG', '开源', '自部署'],
  homepageUrl: 'https://langchain.com',
  githubUrl: 'https://github.com/langchain-ai/langchain',
  docsUrl: 'https://python.langchain.com/docs',
  githubStars: 130652,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'LLM应用开发框架',
  deployment: 'Python Runtime, JavaScript, 云服务',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '所有主流模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型', '向量数据库'],
  scenarios: ['AI应用开发', 'RAG系统', 'Agent构建', '工作流编排'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线陡峭', '版本更新快', '文档碎片化'],
  benchmark: { successRate: 85, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '102.0k', release: 'v0.3.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.0, flexibility: 9.5, stability: 8.5, docs: 9.0 },
};
