import type { ToolProfile } from '@/lib/tools/types';

export const langgraph: ToolProfile = {
  slug: 'langgraph',
  name: 'LangGraph',
  tagline: '状态机风格的 Agent 工作流框架',
  summary: '适合构建可恢复、可观察、可控的生产级 Agent 系统。',
  vendor: 'LangChain',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['工作流编排', '多角色协作', '开源', '自部署', '企业流程'],
  homepageUrl: 'https://github.com/langchain-ai/langgraph',
  githubUrl: 'https://github.com/langchain-ai/langgraph',
  docsUrl: 'https://langchain-ai.github.io/langgraph/',
  githubStars: 27184,
  primaryLanguage: "Python",
  pricing: '开源免费，托管能力另计',
  license: 'MIT',
  focus: '有状态工作流、节点编排、人工介入',
  deployment: '支持本地和云端，团队需要配套可观测与存储。',
  modelSupport: ['OpenAI', 'Anthropic', 'Gemini', 'DeepSeek'],
  connectivity: ['本地部署', '云托管'],
  scenarios: ['可控 Agent 编排', '高可靠工作流', '审批流自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['图结构设计复杂度高', '需要较强工程化能力', '初学成本高于脚本方案'],
  benchmark: { successRate: 87, avgDurationMin: 8.1, retries: 1.2 },
  community: { stars: '14.9k', release: 'v0.2.x', trend: '企业生产化采用持续增加' },
  rating: { security: 8.8, speed: 7.9, flexibility: 9.3, stability: 8.5, docs: 8.2 },
};
