import type { ToolProfile } from '@/lib/tools/types';

export const librechat: ToolProfile = {
  slug: 'librechat',
  name: 'LibreChat',
  tagline: '开源的 ChatGPT 克隆平台',
  summary: 'LibreChat 是一款开源的 ChatGPT 克隆平台，支持多模型、多用户、插件系统，适合团队构建共享的 AI 聊天平台。',
  vendor: 'LibreChat 团队',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['开源', '多模态', '个人助手', '企业流程'],
  homepageUrl: 'https://librechat.ai',
  githubUrl: 'https://github.com/danny-avila/LibreChat',
  docsUrl: 'https://docs.librechat.ai',
  githubStars: 18000,
  primaryLanguage: 'JavaScript',
  pricing: '免费开源',
  license: 'MIT',
  focus: '多模型聊天、多用户管理、插件系统',
  deployment: 'Docker 部署，支持本地运行',
  modelSupport: ['GPT-4', 'Claude', 'Gemini', '支持 OpenAI 兼容 API'],
  connectivity: ['REST API', 'WebSocket', 'Web 界面'],
  scenarios: ['团队共享 AI', '个人助手', '多模型对比', '教学演示'],
  gfwStatus: '需要代理',
  pitfalls: ['配置需一定技术门槛', '部分模型需代理访问'],
  benchmark: { successRate: 82, avgDurationMin: 3.8, retries: 1.3 },
  community: { stars: '18k', release: 'v0.7.5', trend: '快速增长' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 7.8 },
};
