import type { ToolProfile } from '@/lib/tools/types';

export const llamaindex: ToolProfile = {
  slug: 'llamaindex',
  name: 'LlamaIndex',
  tagline: '面向 LLM 应用的数据框架',
  summary: 'LlamaIndex 是一款面向 LLM 应用的数据框架，提供数据索引、检索、RAG 等能力，适合构建基于私有数据的 AI 应用。',
  vendor: 'LlamaIndex 团队',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['RAG', '数据自动化', '开源', '知识库', '企业流程'],
  homepageUrl: 'https://llamaindex.ai',
  githubUrl: 'https://github.com/run-llama/llama_index',
  docsUrl: 'https://docs.llamaindex.ai',
  githubStars: 47861,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '数据索引、向量检索、RAG 应用构建',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'Claude', 'Llama', '支持任意 HuggingFace 模型'],
  connectivity: ['向量数据库', '文档存储', 'API 集成'],
  scenarios: ['知识库问答', '文档检索', '企业搜索', '智能客服'],
  gfwStatus: '直连可用',
  pitfalls: ['向量数据库需单独部署', '大规模数据索引性能需优化'],
  benchmark: { successRate: 85, avgDurationMin: 3.5, retries: 1.2 },
  community: { stars: '38.5k', release: 'v0.12.0', trend: '快速增长' },
  rating: { security: 8.2, speed: 8.0, flexibility: 9.0, stability: 8.2, docs: 8.5 },
};
