import type { ToolProfile } from '@/lib/tools/types';

export const localgpt: ToolProfile = {
  slug: 'localgpt',
  name: 'LocalGPT',
  tagline: '本地化的文档问答系统',
  summary: 'LocalGPT 是一款本地化的文档问答系统，使用 Prompt 工程和本地 embedding 实现离线文档分析，适合隐私敏感场景。',
  vendor: 'Prompt Engineering',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['RAG', '开源', '本地优先', '知识库'],
  homepageUrl: null,
  githubUrl: 'https://github.com/PromtEngineer/localGPT',
  docsUrl: null,
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '本地文档处理、隐私保护、离线问答',
  deployment: 'Python 脚本，支持本地运行',
  modelSupport: ['Llama', 'Mistral', '支持 HuggingFace 模型'],
  connectivity: ['本地文件系统', '本地 embedding'],
  scenarios: ['私有文档分析', '本地知识检索', '个人知识库'],
  gfwStatus: '直连可用',
  pitfalls: ['无官方维护', '功能相对基础'],
  benchmark: { successRate: 76, avgDurationMin: 4.8, retries: 1.5 },
  community: { stars: '20.5k', release: 'v1.0.0', trend: '稳定维护' },
  rating: { security: 8.8, speed: 6.8, flexibility: 7.5, stability: 7.4, docs: 6.5 },
};
