import type { ToolProfile } from '@/lib/tools/types';

export const magical: ToolProfile = {
  slug: 'magical',
  name: 'Magical',
  tagline: '文本自动化助手',
  summary: 'Magical 是一款文本自动化助手，提供快捷回复、模板管理、跨应用文本复用能力，适合客服和销售团队提升效率。',
  vendor: 'Magical Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['文本自动化', '商业软件', '个人助手', '浏览器自动化', '效率工具'],
  homepageUrl: 'https://magical.so',
  githubUrl: null,
  docsUrl: 'https://help.magical.so',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费 $10/月',
  license: '商业许可',
  focus: '文本复用、快捷回复、模板管理',
  deployment: '浏览器扩展',
  modelSupport: ['基础 AI', '模板匹配'],
  connectivity: ['浏览器扩展', 'Slack 集成', 'CRM 集成'],
  scenarios: ['客服回复', '销售邮件', '消息模板', '文档协作'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限文本场景', '高级功能需付费'],
  benchmark: { successRate: 90, avgDurationMin: 1.0, retries: 0.5 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.0, speed: 9.0, flexibility: 7.5, stability: 8.8, docs: 8.0 },
};
