import type { ToolProfile } from '@/lib/tools/types';

export const make: ToolProfile = {
  slug: 'make',
  name: 'Make',
  tagline: '可视化场景自动化平台',
  summary: 'Make（原 Integromat）是一款可视化场景自动化平台，提供直观的流程设计和强大的数据处理能力，适合中小企业构建业务自动化流程。',
  vendor: 'Make.com',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', '可视化编排', '商业软件', '低代码'],
  homepageUrl: 'https://make.com',
  githubUrl: null,
  docsUrl: 'https://docs.make.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '$9 起/月，按操作量计费',
  license: '商业许可',
  focus: '可视化场景、数据处理、多应用集成',
  deployment: '云服务平台',
  modelSupport: ['支持集成 AI 服务'],
  connectivity: ['1000+ 预置集成', 'REST API', 'Webhook'],
  scenarios: ['市场营销自动化', 'CRM 同步', '电商流程', '数据聚合'],
  gfwStatus: '需要代理',
  pitfalls: ['复杂场景成本较高', '学习曲线中等'],
  benchmark: { successRate: 86, avgDurationMin: 3.5, retries: 1.2 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.8, speed: 8.5, flexibility: 9.0, stability: 8.8, docs: 8.5 },
};
