import type { ToolProfile } from '@/lib/tools/types';

export const manus: ToolProfile = {
  slug: 'manus',
  name: 'Manus',
  tagline: '面向通用任务执行的智能代理产品',
  summary: '偏 SaaS 形态，强调任务拆解与自动执行体验。',
  vendor: 'Monica',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '闭源', '云服务', '运营自动化', '个人助手'],
  homepageUrl: 'https://manus.im',
  githubUrl: null,
  docsUrl: 'https://manus.im',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业闭源',
  focus: '任务执行、自动检索、结果交付',
  deployment: '云端服务形态，接入门槛低。',
  modelSupport: ['多模型融合'],
  connectivity: ['官方云服务'],
  scenarios: ['运营任务', '资料整理', '自动报告'],
  gfwStatus: '直连可用',
  pitfalls: ['复杂系统集成能力仍需验证', '深度定制接口有限', '企业合规能力需按场景评估'],
  benchmark: { successRate: 75, avgDurationMin: 7.6, retries: 2.1 },
  community: { stars: '商业产品', release: '持续更新', trend: '个人与中小团队关注提升' },
  rating: { security: 7.4, speed: 8.0, flexibility: 7.0, stability: 7.6, docs: 7.1 },
};
