import type { ToolProfile } from '@/lib/tools/types';

export const maxclaw: ToolProfile = {
  slug: 'maxclaw',
  name: 'MaxClaw',
  tagline: 'MiniMax 多模态 Claw 服务',
  summary: '支持语音、视觉多模态交互的 MiniMax OpenClaw 云服务。',
  vendor: 'MiniMax',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://maxclaw.minimax.ai',
  githubUrl: null,
  docsUrl: 'https://api.minimax.ai/docs/maxclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: 'API 计费',
  license: '商业闭源',
  focus: '多模态大模型、语音能力、视觉能力',
  deployment: 'MiniMax 云托管',
  modelSupport: ['MiniMax 系列', 'abab 系列'],
  connectivity: ['MiniMax 服务', 'API 访问', 'WebSocket'],
  scenarios: ['多模态交互', '语音助手', '视觉理解'],
  gfwStatus: '直连可用',
  pitfalls: ['生态集成有限', '企业功能待完善', '成本控制需注意'],
  benchmark: { successRate: 84, avgDurationMin: 5.8, retries: 1.3 },
  community: { stars: '官方服务', release: '持续迭代', trend: '多模态场景采用增长' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};
