import type { ToolProfile } from '@/lib/tools/types';

export const maxkb: ToolProfile = {
  slug: 'maxkb',
  name: 'MaxKB',
  tagline: '飞致云开源的知识库平台',
  summary: 'MaxKB 是飞致云推出的开源知识库平台，基于 RAG 技术提供文档导入、自动分段、智能问答能力，适合企业构建知识管理系统。',
  vendor: '飞致云',
  sourceType: '开源',
  region: '国内',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['RAG', '开源', '知识库', '企业流程', '可视化编排'],
  homepageUrl: 'https://maxkb.cn',
  githubUrl: 'https://github.com/1Panel-dev/MaxKB',
  docsUrl: 'https://maxkb.cn/docs',
  githubStars: 20541,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '知识库管理、文档问答、智能客服',
  deployment: 'Docker 部署，1Panel 集成',
  modelSupport: ['GPT-4', 'Claude', '通义千问', '支持国内大模型'],
  connectivity: ['REST API', '数据库连接', 'Web 界面'],
  scenarios: ['企业知识库', '智能客服', '文档问答', '培训系统'],
  gfwStatus: '直连可用',
  pitfalls: ['功能相对单一', '定制能力有限'],
  benchmark: { successRate: 81, avgDurationMin: 4.2, retries: 1.4 },
  community: { stars: '8.0k', release: 'v1.5.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.8, flexibility: 7.5, stability: 8.0, docs: 7.8 },
};
