import type { ToolProfile } from '@/lib/tools/types';

export const memgpt: ToolProfile = {
  slug: 'memgpt',
  name: 'MemGPT',
  tagline: '具有长期记忆的 AI Agent 框架',
  summary: 'MemGPT 是一款具有长期记忆能力的 AI Agent 框架，通过分层存储系统实现跨对话的上下文管理，适合需要持续学习的应用场景。',
  vendor: 'UC Berkeley',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['Agent 协作', '开源', '个人助手', '数据自动化', '知识库'],
  homepageUrl: 'https://memgpt.ai',
  githubUrl: 'https://github.com/cpacker/memgpt',
  docsUrl: 'https://docs.memgpt.ai',
  lastReleaseDate: "2026-03-04T03:14:10Z",
  latestVersion: "0.16.6",
  lastCommitDate: "2026-03-16T01:40:58Z",
  githubStars: 21713,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '长期记忆、上下文管理、持续学习',
  deployment: 'Python 包，支持 Docker 部署',
  modelSupport: ['GPT-4', 'Claude', 'Llama', '支持本地模型'],
  connectivity: ['本地存储', '向量数据库', 'REST API'],
  scenarios: ['个人知识管理', '长期对话助手', '学习助手', '研究助手'],
  gfwStatus: '直连可用',
  pitfalls: ['记忆存储需定期清理', '配置复杂度较高'],
  benchmark: { successRate: 77, avgDurationMin: 6.2, retries: 1.7 },
  community: { stars: '12.5k', release: 'v0.6.0', trend: '稳定增长' },
  rating: { security: 7.5, speed: 7.2, flexibility: 8.8, stability: 7.4, docs: 7.6 },
};
