import type { ToolProfile } from '@/lib/tools/types';

export const metagpt: ToolProfile = {
  slug: 'metagpt',
  name: 'MetaGPT',
  tagline: 'SOP 驱动的软件公司式多 Agent 框架',
  summary: '以角色分工和标准流程组织复杂软件任务。',
  vendor: 'DeepWisdom',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['多角色协作', '代码生成', '开源', '研发提效', '企业流程'],
  homepageUrl: 'https://github.com/geekan/MetaGPT',
  githubUrl: 'https://github.com/geekan/MetaGPT',
  docsUrl: 'https://docs.deepwisdom.ai/main/zh/guide/get_started/introduction.html',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '开源免费',
  license: 'MIT',
  focus: 'SOP 流程、角色协作、软件研发自动化',
  deployment: '本地可跑，团队规模化需配套任务调度和存储。',
  modelSupport: ['OpenAI', 'Claude', 'Qwen', '本地模型'],
  connectivity: ['本地运行', '云端模型 API'],
  scenarios: ['需求到代码自动化', '角色化开发流程', '研发协作试验'],
  gfwStatus: '直连可用',
  pitfalls: ['链路较长时稳定性波动', '需要大量提示词调优', '生产接入需二次工程化'],
  benchmark: { successRate: 77, avgDurationMin: 10.1, retries: 2.1 },
  community: { stars: '50.4k', release: 'v0.8.x', trend: '国内外开发者持续活跃' },
  rating: { security: 7.6, speed: 7.1, flexibility: 8.8, stability: 7.2, docs: 7.6 },
};
