import type { ToolProfile } from '@/lib/tools/types';

export const microclaw: ToolProfile = {
  slug: 'microclaw',
  name: 'MicroClaw',
  tagline: '聊天中的代理式 AI 助手',
  summary: 'MicroClaw 是一个代理式 AI 助手，生活在您的聊天中，受 NanoClaw 启发并融合了其设计理念。使用 Rust 构建，提供高性能和内存安全。支持插件系统和上下文注入功能。',
  vendor: 'microclaw',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', 'Rust', 'AI', '机器人', '插件平台', '轻量级'],
  homepageUrl: 'https://microclaw.ai',
  githubUrl: 'https://github.com/microclaw/microclaw',
  docsUrl: 'https://github.com/microclaw/microclaw#readme',
  githubStars: 585,
  primaryLanguage: 'Rust',
  pricing: '免费开源',
  license: 'MIT',
  focus: '聊天集成、插件系统、Rust 实现、轻量级设计',
  deployment: '本地部署，支持 Windows 安装程序',
  modelSupport: ['多模型支持', 'AI 代理'],
  connectivity: ['聊天平台集成', '插件扩展', '上下文注入'],
  scenarios: ['聊天助手', '自动化任务', '插件扩展', '轻量级 AI'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 Rust 知识', '插件生态较新'],
  benchmark: { successRate: 88, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '585', release: 'v0.1.22', trend: '活跃开发' },
  rating: { security: 8.5, speed: 9.0, flexibility: 8.0, stability: 8.0, docs: 7.5 },
};
