import type { ToolProfile } from '@/lib/tools/types';

export const miniclaw: ToolProfile = {
  slug: 'miniclaw',
  name: 'MiniClaw',
  tagline: '精简版Claw，核心功能精简',
  summary: 'MiniClaw 是 OpenClaw 的精简版本，只保留核心的桌面控制和 Shell 执行能力。适合资源受限环境、快速原型验证和轻量级自动化场景。',
  vendor: 'OpenClaw Community',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', '自部署'],
  homepageUrl: 'https://mimiclaw.io/',
  githubUrl: 'https://github.com/memovai/mimiclaw',
  docsUrl: 'https://docs.memovai.com/mimiclaw',
  githubStars: 4750,
  primaryLanguage: "C",
  pricing: '免费开源',
  license: 'MIT',
  focus: '精简版桌面自动化框架',
  deployment: '单文件部署, 无依赖',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['本地运行', 'OpenAI API'],
  scenarios: ['快速原型', '轻量自动化', '资源受限环境'],
  gfwStatus: '需要代理',
  pitfalls: ['功能精简', '不支持高级编排', '扩展性有限'],
  benchmark: { successRate: 78, avgDurationMin: 4.0, retries: 2.5 },
  community: { stars: '420', release: 'v0.3.0', trend: '稳定' },
  rating: { security: 7.0, speed: 8.5, flexibility: 6.5, stability: 7.5, docs: 6.8 },
};
