import type { ToolProfile } from '@/lib/tools/types';

export const miniagents: ToolProfile = {
  slug: 'miniagents',
  name: 'MiniAgents',
  tagline: '极简异步 Agent 框架',
  summary: 'MiniAgents 是一款极简的异步 Agent 框架，专注于轻量级任务执行，适合快速构建简单的自动化脚本和定时任务。',
  vendor: 'Terem Terem',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['开源', '开发工具', '任务自动化', '轻量级'],
  homepageUrl: null,
  githubUrl: 'https://github.com/teremterem/MiniAgents',
  docsUrl: null,
  githubStars: 500,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'MIT',
  focus: '轻量级任务执行、异步处理、简单集成',
  deployment: 'npm 包，支持 Node.js 环境',
  modelSupport: ['GPT-4', 'GPT-3.5', '支持任意 OpenAI 兼容 API'],
  connectivity: ['REST API', '本地文件系统'],
  scenarios: ['定时任务', '简单自动化', '数据采集', '通知推送'],
  gfwStatus: '需要代理',
  pitfalls: ['功能较为基础', '社区规模小'],
  benchmark: { successRate: 70, avgDurationMin: 3.2, retries: 1.4 },
  community: { stars: '0.5k', release: 'v0.2.1', trend: '缓慢增长' },
  rating: { security: 7.0, speed: 8.0, flexibility: 6.5, stability: 7.2, docs: 6.0 },
};
