import type { ToolProfile } from '@/lib/tools/types';

export const mintlify: ToolProfile = {
  slug: 'mintlify',
  name: 'Mintlify',
  tagline: 'AI 文档生成平台',
  summary: 'Mintlify 是一款 AI 驱动的文档生成平台，自动分析代码生成 API 文档，支持多种语言和框架，适合团队构建技术文档。',
  vendor: 'Mintlify',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '文档生成', '商业软件', '开发工具', 'API 文档'],
  homepageUrl: 'https://mintlify.com',
  githubUrl: null,
  docsUrl: 'https://mintlify.com/docs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费订阅',
  license: '商业许可',
  focus: '文档生成、代码分析、API 文档',
  deployment: '云服务平台',
  modelSupport: ['GPT-4', '自研文档模型'],
  connectivity: ['Git 集成', 'CI/CD', 'REST API'],
  scenarios: ['API 文档', '技术文档', '文档维护', '团队知识库'],
  gfwStatus: '需要代理',
  pitfalls: ['定制能力有限', '高级功能需付费'],
  benchmark: { successRate: 86, avgDurationMin: 5.0, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.2, speed: 8.5, flexibility: 7.8, stability: 8.5, docs: 8.8 },
};
