import type { ToolProfile } from '@/lib/tools/types';

export const modelartsclaw: ToolProfile = {
  slug: 'modelartsclaw',
  name: 'ModelArtsClaw',
  tagline: '华为云 ModelArts Claw 服务',
  summary: '基于 ModelArts 平台、全栈 AI 开发的 OpenClaw 云服务。',
  vendor: '华为云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://modelartsclaw.huaweicloud.com',
  githubUrl: null,
  docsUrl: 'https://support.huaweicloud.com/docs/modelartsclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按资源计费',
  license: '商业闭源',
  focus: 'ModelArts 平台、全栈 AI 开发、企业智能体',
  deployment: '华为云托管',
  modelSupport: ['盘古系列', 'Pangu 大模型', '开源模型'],
  connectivity: ['华为云服务', 'API 访问'],
  scenarios: ['全栈 AI 开发', '企业智能体', '模型训练'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖华为生态', '跨平台支持有限', '企业功能待完善'],
  benchmark: { successRate: 84, avgDurationMin: 6.0, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '政企客户增长稳定' },
  rating: { security: 8.5, speed: 8.3, flexibility: 7.5, stability: 8.5, docs: 8.0 },
};
