import type { ToolProfile } from '@/lib/tools/types';

export const moltworker: ToolProfile = {
  slug: 'moltworker',
  name: 'MoltWorker',
  tagline: '在 Cloudflare Workers 上运行 OpenClaw',
  summary: 'MoltWorker 是 Cloudflare 官方出品的 OpenClaw（原名 Moltbot / Clawdbot）实现，可在 Cloudflare Workers 无服务器平台上运行。提供边缘计算能力、低成本部署和全球分布式执行。支持 AI 网关集成和任意 AI 模型路由。',
  vendor: 'Cloudflare',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['开源', '云服务', '分布式', '实时', '连接器', 'API'],
  homepageUrl: 'https://blog.cloudflare.com/moltworker',
  githubUrl: 'https://github.com/cloudflare/moltworker',
  docsUrl: 'https://github.com/cloudflare/moltworker#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费 + Cloudflare 用量',
  license: 'Apache-2.0',
  focus: '无服务器部署、边缘计算、AI 网关、成本优化',
  deployment: 'Cloudflare Workers 部署，全球边缘节点',
  modelSupport: ['OpenClaw', '多模型路由', 'AI Gateway 集成'],
  connectivity: ['Cloudflare Workers', 'AI Gateway', 'REST API', '定时任务'],
  scenarios: ['边缘 AI 代理', '低成本部署', '全球分布式执行', '企业自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 Cloudflare 账户', 'Workers 用量限制'],
  benchmark: { successRate: 95, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '9.7k', release: 'v1.0.0', trend: '活跃维护' },
  rating: { security: 9.0, speed: 9.5, flexibility: 8.5, stability: 9.0, docs: 8.5 },
};
