import type { ToolProfile } from '@/lib/tools/types';

export const multion: ToolProfile = {
  slug: 'multion',
  name: 'MultiOn',
  tagline: 'AI 网页操作助手',
  summary: 'MultiOn 是一款 AI 驱动的网页操作助手，通过自然语言指令控制浏览器执行任务，适合自动化网页交互场景。',
  vendor: 'MultiOn AI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['浏览器自动化', 'AI', '商业软件', 'API', '任务自动化'],
  homepageUrl: 'https://multion.ai',
  githubUrl: null,
  docsUrl: 'https://docs.multion.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: 'API 计费',
  license: '商业许可',
  focus: '网页操作、自然语言控制、API 集成',
  deployment: '浏览器扩展 + 云服务',
  modelSupport: ['GPT-4', '自研导航模型'],
  connectivity: ['浏览器扩展', 'REST API', 'SDK'],
  scenarios: ['网页自动化', '数据采集', '表单填写', '跨网站操作'],
  gfwStatus: '需要代理',
  pitfalls: ['API 调用成本', '复杂页面识别率'],
  benchmark: { successRate: 80, avgDurationMin: 8.0, retries: 1.8 },
  community: { stars: null, release: 'v2.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.5, flexibility: 8.5, stability: 7.5, docs: 8.0 },
};
