import type { ToolProfile } from '@/lib/tools/types';

export const mutableAI: ToolProfile = {
  slug: 'mutable-ai',
  name: 'Mutable.ai',
  tagline: 'AI 代码审查平台',
  summary: 'Mutable.ai 是一款 AI 驱动的代码审查平台，提供自动代码审查、建议生成、质量分析能力，适合团队提升代码质量。',
  vendor: 'Mutable.ai',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '代码审查', '商业软件', '开发工具', '质量保障'],
  homepageUrl: 'https://mutable.ai',
  githubUrl: null,
  docsUrl: 'https://docs.mutable.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业许可',
  focus: '代码审查、质量分析、建议生成',
  deployment: 'GitHub/GitLab 集成',
  modelSupport: ['GPT-4', '自研代码模型'],
  connectivity: ['Git 平台集成', 'REST API'],
  scenarios: ['代码审查', '质量提升', '知识传承', '规范执行'],
  gfwStatus: '需要代理',
  pitfalls: ['需 Git 平台权限', '误报需人工确认'],
  benchmark: { successRate: 82, avgDurationMin: 6.0, retries: 1.5 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 7.8, flexibility: 8.0, stability: 8.2, docs: 7.8 },
};
