import type { ToolProfile } from '@/lib/tools/types';

export const n8n: ToolProfile = {
  slug: 'n8n',
  name: 'n8n',
  tagline: '可自托管的工作流自动化平台',
  summary: 'n8n 是一款可自托管的工作流自动化平台，提供可视化流程编辑和 200+ 预置集成，适合中小企业和开发者构建自动化流程。',
  vendor: 'n8n GmbH',
  sourceType: '开源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '开源', '可视化编排', '自部署', '开发工具'],
  homepageUrl: 'https://n8n.io',
  githubUrl: 'https://github.com/n8n-io/n8n',
  docsUrl: 'https://docs.n8n.io',
  lastReleaseDate: "2026-03-18T10:55:15Z",
  latestVersion: "stable",
  lastCommitDate: "2026-03-23T10:57:20Z",
  githubStars: 180622,
  primaryLanguage: "TypeScript",
  pricing: '自托管免费，云服务$20/月起',
  license: 'Sustainable Use License',
  focus: '工作流自动化、可视化编排、自托管',
  deployment: 'npm 包，支持 Docker 部署',
  modelSupport: ['LangChain 节点', '支持集成 LLM'],
  connectivity: ['200+ 预置集成', 'REST API', 'Webhook'],
  scenarios: ['市场营销自动化', '数据同步', '通知推送', 'API 编排'],
  gfwStatus: '直连可用',
  pitfalls: ['商业用途需购买许可证', '大规模部署需优化'],
  benchmark: { successRate: 85, avgDurationMin: 3.5, retries: 1.2 },
  community: { stars: '42k', release: 'v1.20.0', trend: '快速增长' },
  rating: { security: 8.2, speed: 8.5, flexibility: 9.0, stability: 8.2, docs: 8.5 },
};
