import type { ToolProfile } from '@/lib/tools/types';

export const nanobot: ToolProfile = {
  slug: 'nanobot',
  name: 'NanoBot',
  tagline: '微型任务机器人，命令行优先',
  summary: '单任务专注执行的轻量级 Agent，适合 CI/CD 集成。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['Shell 执行', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/HKUDS/nanobot',
  githubUrl: 'https://github.com/HKUDS/nanobot',
  docsUrl: 'https://github.com/HKUDS/nanobot#readme',
  lastReleaseDate: "2026-03-16T15:21:09Z",
  latestVersion: "v0.1.4.post5",
  lastCommitDate: "2026-03-23T10:57:08Z",
  githubStars: 35636,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '单任务执行、命令行自动化、CI/CD 集成',
  deployment: '单二进制文件，跨平台支持',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['本地运行', 'CI/CD 集成'],
  scenarios: ['CI/CD 集成', '定时任务', '批处理'],
  gfwStatus: '直连可用',
  pitfalls: ['不支持多任务并行', '编排能力有限', '需要脚本化配置'],
  benchmark: { successRate: 84, avgDurationMin: 3.8, retries: 1.2 },
  community: { stars: '3.1k', release: 'v0.6.0', trend: 'DevOps 场景采用增长' },
  rating: { security: 8.5, speed: 9.0, flexibility: 7.0, stability: 8.5, docs: 7.5 },
};
