import type { ToolProfile } from '@/lib/tools/types';

export const nanoclaw: ToolProfile = {
  slug: 'nanoclaw',
  name: 'NanoClaw',
  tagline: '轻量级 OpenClaw 替代方案',
  summary: 'NanoClaw 是一个轻量级的 OpenClaw 替代方案，在容器中运行以确保安全性。支持连接 WhatsApp、Telegram、Slack、Discord、Gmail 等消息应用，具有记忆功能、定时任务，可直接在 Anthropic 的 Agents SDK 上运行。',
  vendor: 'qwibitai',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '轻量级', '部署', 'AI', '连接器', '多语言'],
  homepageUrl: 'https://nanoclaw.dev',
  githubUrl: 'https://github.com/qwibitai/nanoclaw',
  docsUrl: 'https://github.com/qwibitai/nanoclaw#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-03-22T14:55:26Z",
  githubStars: 24985,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: '轻量级设计、容器安全、多平台消息集成、记忆功能',
  deployment: '容器部署，支持 Docker',
  modelSupport: ['Anthropic Agents SDK', 'Claude', '多模型支持'],
  connectivity: ['WhatsApp', 'Telegram', 'Slack', 'Discord', 'Gmail', '定时任务'],
  scenarios: ['消息机器人', 'AI 助手', '自动化任务', '多平台集成'],
  gfwStatus: '需要代理',
  pitfalls: ['需要容器知识', '配置相对复杂'],
  benchmark: { successRate: 92, avgDurationMin: 3.0, retries: 1.0 },
  community: { stars: '24.9k', release: 'v1.0.0', trend: '活跃开发' },
  rating: { security: 9.0, speed: 9.0, flexibility: 8.5, stability: 8.5, docs: 8.0 },
};
