import type { ToolProfile } from '@/lib/tools/types';

export const nullclaw: ToolProfile = {
  slug: 'nullclaw',
  name: 'NullClaw',
  tagline: 'Zig 编写的最小 AI 助手',
  summary: 'NullClaw 是最快、最小、完全自主的 AI 助手基础设施，使用 Zig 语言编写。提供极致的性能和极简的资源占用。支持本地令牌认证、外部通道和 Web 功能。',
  vendor: 'nullclaw',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '轻量级', '跨平台', 'AI', '个人助手', 'CLI 工具'],
  homepageUrl: 'https://nullclaw.io',
  githubUrl: 'https://github.com/nullclaw/nullclaw',
  docsUrl: 'https://github.com/nullclaw/nullclaw#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '极致性能、最小资源占用、自主 AI、Zig 实现',
  deployment: '本地部署，支持编译运行',
  modelSupport: ['多模型支持', '自主 AI'],
  connectivity: ['本地令牌认证', '外部通道', 'Web API'],
  scenarios: ['个人 AI 助手', '轻量级自动化', '高性能需求', '资源受限环境'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 Zig 知识', '生态较新'],
  benchmark: { successRate: 90, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '6.7k', release: 'v1.0.0', trend: '活跃开发' },
  rating: { security: 8.5, speed: 10.0, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};
