import type { ToolProfile } from '@/lib/tools/types';

export const nutjs: ToolProfile = {
  slug: 'nutjs',
  name: 'nut.js',
  tagline: '跨平台桌面自动化库，2.4k stars',
  summary: 'nut.js 是一个跨平台桌面自动化库，支持鼠标、键盘和屏幕操作。适合桌面自动化、 GUI测试、 任务自动化等场景。',
  vendor: 'nut.js Project',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://nutjs.dev',
  githubUrl: 'https://github.com/nut-tree/nut.js',
  docsUrl: 'https://nutjs.dev/guides',
  githubStars: 2400,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '跨平台桌面自动化',
  deployment: 'Node.js Runtime, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['桌面自动化', 'GUI测试', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要编程知识', '跨平台兼容性有限'],
  benchmark: { successRate: 85, avgDurationMin: 0.4, retries: 1.5 },
  community: { stars: '2.4k', release: 'v4.2.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 8.5 },
};
