import type { ToolProfile } from '@/lib/tools/types';

export const ollama: ToolProfile = {
  slug: 'ollama',
  name: 'Ollama',
  tagline: '本地运行大模型的最简单方式',
  summary: 'Ollama 是一款极简的本地大模型运行工具，支持一键下载和运行开源模型，提供简单的 API 接口，适合开发者快速集成 LLM 能力。',
  vendor: 'Ollama',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['本地优先', '开源', '开发工具', '多模态'],
  homepageUrl: 'https://ollama.com',
  githubUrl: 'https://github.com/ollama/ollama',
  docsUrl: 'https://ollama.com/docs',
  lastReleaseDate: "2026-03-18T09:02:25Z",
  latestVersion: "v0.18.2",
  lastCommitDate: "2026-03-22T21:05:52Z",
  githubStars: 165927,
  primaryLanguage: "Go",
  pricing: '免费开源',
  license: 'MIT',
  focus: '本地模型部署、简单 API、模型管理',
  deployment: 'CLI 工具，支持 Docker 部署',
  modelSupport: ['Llama', 'Mistral', 'Gemma', '支持 100+ 模型'],
  connectivity: ['REST API', 'CLI', 'WebSocket'],
  scenarios: ['本地开发测试', '个人助手', '原型验证', '边缘部署'],
  gfwStatus: '需要代理',
  pitfalls: ['模型下载需网络', 'GPU 加速需配置'],
  benchmark: { successRate: 85, avgDurationMin: 2.5, retries: 1.2 },
  community: { stars: '105k', release: 'v0.5.0', trend: '爆发式增长' },
  rating: { security: 8.5, speed: 8.5, flexibility: 8.8, stability: 8.5, docs: 8.2 },
};
