import type { ToolProfile } from '@/lib/tools/types';

export const omniparser: ToolProfile = {
  slug: 'omniparser',
  name: 'OmniParser',
  tagline: '微软屏幕解析工具，4.2k stars',
  summary: 'OmniParser 是微软开发的屏幕解析工具，能够通过视觉理解将屏幕内容转换为结构化数据。支持多种UI元素识别，适合屏幕自动化场景。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面控制', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/microsoft/OmniParser',
  githubUrl: 'https://github.com/microsoft/OmniParser',
  docsUrl: 'https://github.com/microsoft/OmniParser#readme',
  githubStars: 24564,
  primaryLanguage: "Jupyter Notebook",
  pricing: '免费开源',
  license: 'MIT',
  focus: '屏幕解析工具',
  deployment: 'Python Runtime, ONNX',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地视觉模型'],
  connectivity: ['本地运行', 'ONNX Runtime'],
  scenarios: ['屏幕解析', 'UI元素识别', '自动化辅助', '数据提取'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限屏幕解析', '需要配合其他工具', '识别准确率有限'],
  benchmark: { successRate: 82, avgDurationMin: 1.5, retries: 1.8 },
  community: { stars: '4.2k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.5, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};
