import type { ToolProfile } from '@/lib/tools/types';

export const openwebui: ToolProfile = {
  slug: 'openwebui',
  name: 'OpenWebUI',
  tagline: '自托管的 AI 聊天界面',
  summary: 'OpenWebUI 是一款自托管的 AI 聊天界面，支持多模型、RAG、多模态输入，是 Ollama 等本地模型的热门 Web 前端。',
  vendor: 'OpenWebUI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'AI 编排与工作流平台',
  tags: ['本地优先', '开源', '多模态', '知识库', '个人助手'],
  homepageUrl: 'https://openwebui.com',
  githubUrl: 'https://github.com/open-webui/open-webui',
  docsUrl: 'https://docs.openwebui.com',
  githubStars: 128313,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '本地模型前端、RAG、多模态',
  deployment: 'Docker 部署，支持 pip 安装',
  modelSupport: ['Ollama', 'GPT-4', 'Claude', '支持 50+ 模型'],
  connectivity: ['REST API', 'Ollama API', 'WebSocket'],
  scenarios: ['个人助手', '本地开发', '团队共享', '知识库问答'],
  gfwStatus: '需要代理',
  pitfalls: ['模型需单独部署', '配置复杂度较高'],
  benchmark: { successRate: 84, avgDurationMin: 3.5, retries: 1.2 },
  community: { stars: '45k', release: 'v0.5.0', trend: '爆发式增长' },
  rating: { security: 8.2, speed: 8.0, flexibility: 9.0, stability: 8.2, docs: 8.0 },
};
