import type { ToolProfile } from '@/lib/tools/types';

export const openhands: ToolProfile = {
  slug: 'openhands',
  name: 'OpenHands',
  tagline: '开源Devin替代，35.2k stars',
  summary: 'OpenHands（原OpenDevin）是一个开源的软件工程Agent，能够自主完成代码编写、调试、测试等任务。作为Devin的开源替代品，它提供了完整的软件开发自动化能力。',
  vendor: 'All-Hands-AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://all-hands.dev',
  githubUrl: 'https://github.com/All-Hands-AI/OpenHands',
  docsUrl: 'https://docs.all-hands.dev',
  githubStars: 69571,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '开源软件工程Agent',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['软件开发', '代码生成', '调试', '测试自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['能力仍需完善', '复杂任务成功率有限', '需要人工引导'],
  benchmark: { successRate: 78, avgDurationMin: 4.0, retries: 2.5 },
  community: { stars: '35.2k', release: 'v0.15.0', trend: '快速增长' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.5, stability: 7.5, docs: 8.0 },
};
