import type { ToolProfile } from '@/lib/tools/types';

export const openrpa: ToolProfile = {
  slug: 'openrpa',
  name: 'OpenRPA',
  tagline: '开源RPA工具，1.8k stars',
  summary: 'OpenRPA 是一个开源RPA工具，支持桌面自动化、 网页自动化和OCR。适合RPA自动化、 任务自动化、 流程自动化等场景。',
  vendor: 'OpenRPA Project',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://openrpa.openrpa.dk',
  githubUrl: 'https://github.com/open-rpa/openrpa',
  docsUrl: 'https://docs.openrpa.dk',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MPL-2.0',
  focus: '开源RPA工具',
  deployment: 'Windows Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['RPA自动化', '任务自动化', '流程自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '主要支持Windows', '社区规模较小'],
  benchmark: { successRate: 78, avgDurationMin: 1.5, retries: 2.0 },
  community: { stars: '1.8k', release: 'v1.3.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.0, flexibility: 8.0, stability: 7.5, docs: 7.0 },
};
