import type { ToolProfile } from '@/lib/tools/types';

export const openinterpreter: ToolProfile = {
  slug: 'openinterpreter',
  name: 'OpenInterpreter',
  tagline: '命令行优先的个人 AI 终端助手',
  summary: '上手快，适合单机开发辅助和脚本型任务。',
  vendor: 'OpenInterpreter 团队',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['Shell 执行', '代码生成', '开源', '本地优先', '个人助手'],
  homepageUrl: 'https://github.com/openinterpreter/open-interpreter',
  githubUrl: 'https://github.com/openinterpreter/open-interpreter',
  docsUrl: 'https://docs.openinterpreter.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源，可接商业模型',
  license: 'AGPL-3.0',
  focus: '本地命令执行、代码解释、轻量自动化',
  deployment: '本地 pip 安装最便捷，企业化治理能力中等。',
  modelSupport: ['GPT-4o', 'Claude 3.5', '本地 LLM'],
  connectivity: ['本地运行', '可选云模型 API'],
  scenarios: ['开发机辅助', '脚本执行', '本地实验'],
  gfwStatus: '直连可用',
  pitfalls: ['复杂多步骤任务时需要人工分段引导', '长期运行会话需手动管理上下文', '团队协作能力弱于编排型框架'],
  benchmark: { successRate: 79, avgDurationMin: 6.2, retries: 1.9 },
  community: { stars: '57.2k', release: 'v0.5.6', trend: '社区热度高，生态插件丰富' },
  rating: { security: 7.5, speed: 8.6, flexibility: 7.9, stability: 7.4, docs: 8.3 },
};
