import type { ToolProfile } from '@/lib/tools/types';

export const openassistant: ToolProfile = {
  slug: 'openassistant',
  name: 'OpenAssistant',
  tagline: '开源的对话式 AI 助手',
  summary: 'OpenAssistant 是一款开源的对话式 AI 助手项目，提供高质量的训练数据和模型，适合构建多语言 AI 应用。',
  vendor: 'LAION-AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['开源', '个人助手', '多模态', '知识库'],
  homepageUrl: 'https://open-assistant.io',
  githubUrl: 'https://github.com/LAION-AI/Open-Assistant',
  docsUrl: 'https://docs.open-assistant.io',
  githubStars: 37437,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '对话式 AI、多语言支持、开放数据',
  deployment: 'Python 包，支持 Docker 部署',
  modelSupport: ['OpenAssistant 自研模型', '支持 HuggingFace 模型'],
  connectivity: ['REST API', 'WebSocket', 'Web 界面'],
  scenarios: ['智能客服', '个人助手', '教育应用', '多语言场景'],
  gfwStatus: '直连可用',
  pitfalls: ['项目已归档', '社区支持有限'],
  benchmark: { successRate: 72, avgDurationMin: 4.5, retries: 1.6 },
  community: { stars: '37.5k', release: 'v0.0.22', trend: '已归档' },
  rating: { security: 7.5, speed: 7.4, flexibility: 7.8, stability: 7.0, docs: 7.2 },
};
