import type { ToolProfile } from '@/lib/tools/types';

export const openclawSkills: ToolProfile = {
  slug: 'openclaw-skills',
  name: 'OpenClaw Skills',
  tagline: 'OpenClaw 技能档案库',
  summary: 'OpenClaw Skills 是 clawhub.com 上所有技能版本的归档仓库。包含所有 OpenClaw 技能的完整历史记录，由 clawhub 机器人自动同步维护。提供 MIT 许可的开源技能资源库。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '插件生态', '社区生态', '开发者工具', '文档工具', '自动化'],
  homepageUrl: 'https://clawhub.ai',
  githubUrl: 'https://github.com/openclaw/skills',
  docsUrl: 'https://github.com/openclaw/skills#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-03-23T11:02:31Z",
  githubStars: 3287,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '技能归档、版本管理、OpenClaw 生态资源',
  deployment: 'GitHub 仓库，可本地克隆',
  modelSupport: ['OpenClaw', '多技能支持'],
  connectivity: ['GitHub 集成', 'clawhub 同步', '自动更新'],
  scenarios: ['技能发现', '版本回溯', '技能开发参考', '生态研究'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 Git 知识', '技能数量庞大需筛选'],
  benchmark: { successRate: 95, avgDurationMin: 1.0, retries: 1.0 },
  community: { stars: '3.3k', release: 'v1.1.0', trend: '活跃维护' },
  rating: { security: 8.5, speed: 8.0, flexibility: 9.0, stability: 9.0, docs: 7.5 },
};
