import type { ToolProfile } from '@/lib/tools/types';

export const openadapt: ToolProfile = {
  slug: 'openadapt',
  name: 'OpenAdapt',
  tagline: 'AI 驱动的开源 RPA 自动化工具',
  summary: 'OpenAdapt 是一款基于 AI 的开源 RPA 工具，通过记录和回放用户操作来实现自动化流程，支持视觉理解和智能决策。',
  vendor: 'OpenAdapt AI',
  sourceType: '开源',
  region: '海外',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', 'RPA', 'AI', '开源', '视觉理解'],
  homepageUrl: 'https://openadapt.ai',
  githubUrl: 'https://github.com/OpenAdaptAI/OpenAdapt',
  docsUrl: 'https://openadapt.ai/docs',
  lastReleaseDate: "2026-03-04T02:22:21Z",
  latestVersion: "v1.2.2",
  lastCommitDate: "2026-03-04T02:39:37Z",
  githubStars: 1524,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '操作录制回放、视觉理解、智能自动化',
  deployment: '本地桌面应用，支持 Docker 部署',
  modelSupport: ['自研视觉模型', '支持集成主流 LLM'],
  connectivity: ['本地桌面', 'API 调用', '数据库连接'],
  scenarios: ['办公自动化', '数据录入', '跨应用流程', '报表生成'],
  gfwStatus: '直连可用',
  pitfalls: ['录制脚本需要人工校验', '复杂场景识别率待提升'],
  benchmark: { successRate: 75, avgDurationMin: 6.5, retries: 1.8 },
  community: { stars: '2.1k', release: 'v0.8.0', trend: '快速增长' },
  rating: { security: 7.8, speed: 7.2, flexibility: 8.2, stability: 7.0, docs: 7.5 },
};
