import type { ToolProfile } from '@/lib/tools/types';

export const openadapt: ToolProfile = {
  slug: 'openadapt',
  name: 'OpenAdapt',
  tagline: 'AI RPA自动化工具，3.2k stars',
  summary: 'OpenAdapt 是一个AI驱动的RPA自动化工具，能够通过录制和回放自动执行桌面任务。支持多模型、 适合RPA自动化、 桌面自动化等场景。',
  vendor: 'OpenAdapt AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/OpenAdaptAI/OpenAdapt',
  githubUrl: 'https://github.com/OpenAdaptAI/OpenAdapt',
  docsUrl: 'https://docs.openadapt.ai',
  githubStars: 3200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI RPA自动化',
  deployment: 'Python Runtime, Desktop',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['RPA自动化', '桌面自动化', '任务录制'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限桌面场景', '需要桌面环境', '复杂任务支持有限'],
  benchmark: { successRate: 75, avgDurationMin: 5.0, retries: 2.5 },
  community: { stars: '3.2k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.0, speed: 7.0, flexibility: 7.5, stability: 7.0, docs: 7.0 },
};
