import type { ToolProfile } from '@/lib/tools/types';

export const openfang: ToolProfile = {
  slug: 'openfang',
  name: 'OpenFang',
  tagline: '安全增强版 Agent，企业合规场景',
  summary: '内置安全沙箱和审计日志的 OpenClaw 企业版。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', '自部署', '企业流程'],
  homepageUrl: 'https://openfang.ai',
  githubUrl: 'https://github.com/openclaw/openfang',
  docsUrl: 'https://docs.openfang.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源，企业支持付费',
  license: 'GPL-3.0',
  focus: '安全沙箱、审计日志、企业合规',
  deployment: 'Docker 部署，支持企业级安全策略',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['本地运行', '企业网关', 'SIEM 集成'],
  scenarios: ['企业合规场景', '金融行业', '政府机构'],
  gfwStatus: '直连可用',
  pitfalls: ['性能开销较大', '配置复杂', '需要企业级运维'],
  benchmark: { successRate: 80, avgDurationMin: 9.5, retries: 1.8 },
  community: { stars: '4.5k', release: 'v0.4.2', trend: '企业用户增长稳定' },
  rating: { security: 9.5, speed: 7.5, flexibility: 7.0, stability: 8.5, docs: 8.0 },
};
