import type { ToolProfile } from '@/lib/tools/types';

export const openclaw: ToolProfile = {
  slug: 'openclaw',
  name: 'OpenClaw',
  tagline: '桌面 + Shell 的全栈自动化 Agent',
  summary: '适合需要真实操作系统控制能力的自动化团队。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', '自部署', '企业流程'],
  homepageUrl: 'https://openclaw.ai',
  githubUrl: 'https://github.com/openclaw/openclaw',
  docsUrl: 'https://docs.openclaw.ai',
  githubStars: 329876,
  primaryLanguage: "TypeScript",
  pricing: '免费开源，可自建',
  license: 'Apache-2.0',
  focus: '桌面控制、命令执行、跨流程编排',
  deployment: 'Docker 与脚本化部署都可行，云端需处理网络出口策略。',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['可选 Discord 通道', 'Tailscale 内网穿透', '本地 Agent 网关'],
  scenarios: ['桌面自动化', '运维脚本编排', '跨应用操作'],
  gfwStatus: '需要代理',
  pitfalls: ['海外网络波动时首次连接耗时较高', '桌面权限需要额外加固审计策略', '混合云场景建议拆分执行与调度节点'],
  benchmark: { successRate: 86, avgDurationMin: 7.8, retries: 1.3 },
  community: { stars: '18.4k', release: 'v0.19.2', trend: '近 30 天活跃提交稳定增长' },
  rating: { security: 8.2, speed: 8.4, flexibility: 9.1, stability: 8.1, docs: 7.8 },
};
