import type { ToolProfile } from '@/lib/tools/types';

export const oracleclaw: ToolProfile = {
  slug: 'oracleclaw',
  name: 'Oracle Claw',
  tagline: 'Oracle Digital Assistant Claw 服务',
  summary: '数据库集成、企业助手的 OpenClaw 云服务。',
  vendor: 'Oracle',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://oracleclaw.oracle.com',
  githubUrl: null,
  docsUrl: 'https://docs.oracle.com/oracleclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业闭源',
  focus: '数据库集成、企业助手、Oracle 生态',
  deployment: 'Oracle Cloud 托管',
  modelSupport: ['Oracle 模型', '自定义模型'],
  connectivity: ['Oracle Cloud 服务', 'API 访问'],
  scenarios: ['企业助手', '数据库集成', '合规场景'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 82, avgDurationMin: 6.5, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业客户增长稳定' },
  rating: { security: 9.0, speed: 8.0, flexibility: 7.0, stability: 8.5, docs: 8.0 },
};
