import type { ToolProfile } from '@/lib/tools/types';

export const panguclaw: ToolProfile = {
  slug: 'panguclaw',
  name: 'PanguClaw',
  tagline: '华为云盘古 Claw 服务',
  summary: '基于盘古大模型、鸿蒙生态的 OpenClaw 云服务。',
  vendor: '华为云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://panguclaw.huaweicloud.com',
  githubUrl: null,
  docsUrl: 'https://support.huaweicloud.com/docs/panguclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按资源计费',
  license: '商业闭源',
  focus: '盘古大模型、鸿蒙生态、AI 开发平台',
  deployment: '华为云托管',
  modelSupport: ['盘古系列', 'Pangu 大模型'],
  connectivity: ['华为云服务', '鸿蒙集成', 'API 访问'],
  scenarios: ['鸿蒙生态', '政企场景', 'AI 开发'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖华为生态', '跨平台支持有限', '企业功能待完善'],
  benchmark: { successRate: 85, avgDurationMin: 5.5, retries: 1.3 },
  community: { stars: '官方服务', release: '持续更新', trend: '政企客户增长稳定' },
  rating: { security: 8.5, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.0 },
};
