import type { ToolProfile } from '@/lib/tools/types';

export const pearai: ToolProfile = {
  slug: 'pearai',
  name: 'PearAI',
  tagline: '开源 AI 编辑器，2.8k stars',
  summary: 'PearAI 是一个开源的 AI 编辑器，提供代码补全、代码生成等功能。支持多种模型，适合日常开发。',
  vendor: 'PearAI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://trypear.ai',
  githubUrl: 'https://github.com/trypear/pearai-master',
  docsUrl: 'https://docs.trypear.ai',
  githubStars: 2800,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'AGPL-3.0',
  focus: '开源 AI 编辑器',
  deployment: 'Electron App',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码补全', '代码生成', '日常开发'],
  gfwStatus: '需要代理',
  pitfalls: ['AGPL 许可证', '功能相对简单', '社区规模小'],
  benchmark: { successRate: 80, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '2.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.0, stability: 7.5, docs: 7.5 },
};
