import type { ToolProfile } from '@/lib/tools/types';

export const perplexica: ToolProfile = {
  slug: 'perplexica',
  name: 'Perplexica',
  tagline: '开源的 AI 搜索引擎',
  summary: 'Perplexica 是一款开源的 AI 搜索引擎，类似 Perplexity AI，支持网络搜索、引用来源、Follow-up 提问，适合信息搜集和研究。',
  vendor: 'ItzCrazyKns',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['开源', '信息搜集', '搜索', '个人助手'],
  homepageUrl: null,
  githubUrl: 'https://github.com/ItzCrazyKns/Perplexica',
  docsUrl: null,
  githubStars: 33309,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI 搜索、引用来源、信息总结',
  deployment: 'Docker 部署，支持本地运行',
  modelSupport: ['GPT-4', 'Claude', '支持本地模型'],
  connectivity: ['网络搜索 API', 'REST API', 'Web 界面'],
  scenarios: ['信息搜集', '市场调研', '学术研究', '新闻摘要'],
  gfwStatus: '需要代理',
  pitfalls: ['搜索依赖外部 API', '需自行配置搜索后端'],
  benchmark: { successRate: 77, avgDurationMin: 6.5, retries: 1.6 },
  community: { stars: '12.8k', release: 'v1.10.0', trend: '快速增长' },
  rating: { security: 7.5, speed: 7.4, flexibility: 8.0, stability: 7.2, docs: 6.8 },
};
