import type { ToolProfile } from '@/lib/tools/types';

export const perplexity: ToolProfile = {
  slug: 'perplexity',
  name: 'Perplexity AI',
  tagline: 'AI 驱动的搜索引擎',
  summary: 'Perplexity AI 是一款 AI 驱动的搜索引擎，结合网络搜索和 LLM 能力，提供带引用来源的答案，适合信息搜集和研究。',
  vendor: 'Perplexity AI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI 搜索', '信息搜集', '商业软件', '个人助手', '研究'],
  homepageUrl: 'https://perplexity.ai',
  githubUrl: null,
  docsUrl: 'https://docs.perplexity.ai',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Pro $20/月',
  license: '商业许可',
  focus: 'AI 搜索、引用来源、信息总结',
  deployment: 'Web 应用 + 移动 App',
  modelSupport: ['GPT-4', 'Claude', '自研模型'],
  connectivity: ['Web 界面', 'API', '移动 App'],
  scenarios: ['信息搜集', '市场调研', '学术研究', '新闻摘要'],
  gfwStatus: '需要代理',
  pitfalls: ['搜索结果依赖外部源', '高级功能需付费'],
  benchmark: { successRate: 88, avgDurationMin: 5.0, retries: 1.2 },
  community: { stars: null, release: '持续更新', trend: '快速增长' },
  rating: { security: 8.5, speed: 8.8, flexibility: 8.5, stability: 8.8, docs: 8.5 },
};
