import type { ToolProfile } from '@/lib/tools/types';

export const pgclaw: ToolProfile = {
  slug: 'pgclaw',
  name: 'PgClaw',
  tagline: '400 行 PostgreSQL 实现的 Clawdbot',
  summary: 'PgClaw 是一个完全用 PostgreSQL SQL 实现的 Clawdbot 项目，仅用 400 行 SQL 代码。这是一个轻量级的数据库驱动机器人实现，展示了 PostgreSQL 的强大功能和灵活性。',
  vendor: 'calebwin',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '轻量级', '实验性', '大数据', '云原生'],
  homepageUrl: 'https://github.com/calebwin/pgclaw',
  githubUrl: 'https://github.com/calebwin/pgclaw',
  docsUrl: 'https://github.com/calebwin/pgclaw#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2026-02-12T17:32:22Z",
  githubStars: 208,
  primaryLanguage: "Rust",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'PostgreSQL 实现、轻量级机器人、数据库驱动',
  deployment: '本地部署，需要 PostgreSQL',
  modelSupport: ['Clawdbot', 'SQL 驱动'],
  connectivity: ['PostgreSQL 数据库', '本地运行'],
  scenarios: ['数据库驱动机器人', 'PostgreSQL 实验', '轻量级自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 PostgreSQL 环境', '功能相对简单'],
  benchmark: { successRate: 85, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '208', release: 'v1.0.0', trend: '实验性项目' },
  rating: { security: 7.5, speed: 8.0, flexibility: 7.0, stability: 7.0, docs: 6.5 },
};
