import type { ToolProfile } from '@/lib/tools/types';

export const phidata: ToolProfile = {
  slug: 'phidata',
  name: 'Phidata',
  tagline: '轻量级 AI 助手开发框架',
  summary: 'Phidata 是一款轻量级的 AI 助手开发框架，提供工具调用、记忆管理、多模态支持，适合快速构建个性化 AI 应用。',
  vendor: 'Phidata HQ',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['Agent 协作', '开源', '个人助手', '开发工具', '多模态'],
  homepageUrl: 'https://phidata.com',
  githubUrl: 'https://github.com/phidatahq/phidata',
  docsUrl: 'https://docs.phidata.com',
  githubStars: 38861,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '工具集成、记忆管理、多模态交互',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'Claude', 'Gemini', 'Llama', 'Groq'],
  connectivity: ['REST API', 'WebSocket', '数据库连接'],
  scenarios: ['个人助手', '自动化任务', '数据分析', '智能客服'],
  gfwStatus: '直连可用',
  pitfalls: ['部分模型需代理访问', '复杂场景需自行扩展工具'],
  benchmark: { successRate: 79, avgDurationMin: 5.8, retries: 1.6 },
  community: { stars: '15.8k', release: 'v2.7.0', trend: '快速增长' },
  rating: { security: 7.8, speed: 8.0, flexibility: 8.5, stability: 7.6, docs: 7.8 },
};
