import type { ToolProfile } from '@/lib/tools/types';

export const phind: ToolProfile = {
  slug: 'phind',
  name: 'Phind',
  tagline: '开发者 AI 搜索引擎',
  summary: 'Phind 是一款专为开发者打造的 AI 搜索引擎，提供代码示例、技术问答、文档搜索能力，适合开发者快速解决问题。',
  vendor: 'Phind',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI 搜索', '开发者工具', '商业软件', '信息搜集', '代码问答'],
  homepageUrl: 'https://phind.com',
  githubUrl: null,
  docsUrl: null,
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费订阅',
  license: '商业许可',
  focus: '开发者搜索、代码示例、技术问答',
  deployment: 'Web 应用 + 浏览器扩展',
  modelSupport: ['自研代码模型', 'GPT-4'],
  connectivity: ['Web 界面', '浏览器扩展', 'API'],
  scenarios: ['问题解决', '代码查询', '技术学习', '文档搜索'],
  gfwStatus: '需要代理',
  pitfalls: ['高级功能需付费', '国内访问速度慢'],
  benchmark: { successRate: 86, avgDurationMin: 4.0, retries: 1.3 },
  community: { stars: null, release: 'v2.0', trend: '稳定增长' },
  rating: { security: 8.2, speed: 8.8, flexibility: 8.5, stability: 8.5, docs: 8.0 },
};
