import type { ToolProfile } from '@/lib/tools/types';

export const pi: ToolProfile = {
  slug: 'pi',
  name: 'Pi',
  tagline: '个人 AI 助手',
  summary: 'Pi 是 Inflection AI 推出的个人 AI 助手，注重情感交流和陪伴，提供友好的对话体验和人生建议。',
  vendor: 'Inflection AI',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['对话 AI', '个人助手', '商业软件', '情感陪伴'],
  homepageUrl: 'https://pi.ai',
  githubUrl: null,
  docsUrl: null,
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费',
  license: '商业许可',
  focus: '情感交流、人生建议、日常陪伴',
  deployment: 'Web 应用 + 移动 App',
  modelSupport: ['Inflection-1', '自研模型'],
  connectivity: ['Web 界面', '移动 App'],
  scenarios: ['情感陪伴', '人生咨询', '日常对话', '压力缓解'],
  gfwStatus: '需要代理',
  pitfalls: ['功能相对单一', '专业能力有限'],
  benchmark: { successRate: 82, avgDurationMin: 3.5, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 7.5 },
};
