import type { ToolProfile } from '@/lib/tools/types';

export const picoclaw: ToolProfile = {
  slug: 'picoclaw',
  name: 'PicoClaw',
  tagline: '嵌入式微型 Agent，资源占用极低',
  summary: '适合 IoT 设备和边缘计算场景的 OpenClaw 边缘版。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://picoclaw.ai',
  githubUrl: 'https://github.com/openclaw/picoclaw',
  docsUrl: 'https://docs.picoclaw.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '边缘计算、IoT 设备、资源受限环境',
  deployment: '单二进制文件，内存占用<100MB',
  modelSupport: ['GPT-4o', 'Claude 3.5', '本地 LLM'],
  connectivity: ['本地运行', '边缘网关'],
  scenarios: ['IoT 自动化', '边缘计算', '嵌入式系统'],
  gfwStatus: '直连可用',
  pitfalls: ['能力受限', '不支持复杂任务', '模型支持有限'],
  benchmark: { successRate: 79, avgDurationMin: 4.5, retries: 1.8 },
  community: { stars: '2.8k', release: 'v0.5.1', trend: '边缘场景采用增加' },
  rating: { security: 8.5, speed: 9.0, flexibility: 6.5, stability: 8.0, docs: 7.0 },
};
