import type { ToolProfile } from '@/lib/tools/types';

export const pieces: ToolProfile = {
  slug: 'pieces',
  name: 'Pieces for Dev',
  tagline: '代码片段管理 AI 助手',
  summary: 'Pieces for Dev 是一款代码片段管理工具，集成 AI 能力提供代码搜索、分类、解释、生成功能，适合开发者管理代码资产。',
  vendor: 'Pieces for Dev',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '代码管理', '商业软件', '开发工具', '知识管理'],
  homepageUrl: 'https://pieces.app',
  githubUrl: null,
  docsUrl: 'https://docs.pieces.app',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费',
  license: '商业许可',
  focus: '代码片段管理、AI 搜索、代码生成',
  deployment: '桌面应用 + IDE 插件',
  modelSupport: ['GPT-4', '本地模型'],
  connectivity: ['IDE 插件', '本地存储', '云同步'],
  scenarios: ['代码收藏', '知识管理', '快速复用', '团队共享'],
  gfwStatus: '需要代理',
  pitfalls: ['高级功能需付费', '云同步需配置'],
  benchmark: { successRate: 88, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.8, flexibility: 8.5, stability: 8.5, docs: 8.0 },
};
