import type { ToolProfile } from '@/lib/tools/types';

export const pinchchat: ToolProfile = {
  slug: 'pinchchat',
  name: 'PinchChat',
  tagline: 'OpenClaw 深色主题 Web 聊天 UI',
  summary: 'PinchChat 是一个为 OpenClaw 设计的时尚深色主题 Web 聊天界面。提供 PWA 安装支持、Docker 部署、懒加载优化等功能。拥有现代化的 UI 设计和流畅的用户体验。',
  vendor: 'MarlBurroW',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', 'UI 生成', '前端开发', 'React', '跨平台', '部署'],
  homepageUrl: 'https://marlburrow.github.io/pinchchat',
  githubUrl: 'https://github.com/MarlBurroW/pinchchat',
  docsUrl: 'https://github.com/MarlBurroW/pinchchat#readme',
  githubStars: 106,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'Web 聊天 UI、深色主题、PWA 支持、Docker 部署',
  deployment: '本地部署，支持 Docker 和 PWA',
  modelSupport: ['OpenClaw', 'Web 聊天'],
  connectivity: ['WebSocket', 'REST API', 'PWA 离线支持'],
  scenarios: ['OpenClaw 聊天界面', 'Web 应用部署', '移动端 PWA', '自托管聊天'],
  gfwStatus: '需要代理',
  pitfalls: ['需要前端部署知识', '配置需要时间'],
  benchmark: { successRate: 90, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '106', release: 'v1.0.0', trend: '活跃开发' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 7.5 },
};
