import type { ToolProfile } from '@/lib/tools/types';

export const pipedream: ToolProfile = {
  slug: 'pipedream',
  name: 'Pipedream',
  tagline: '开发者优先的自动化平台',
  summary: 'Pipedream 是一款面向开发者的自动化平台，支持代码级自定义和 1000+ 预置集成，提供免费的开发额度，适合开发者快速构建 API 驱动的工作流。',
  vendor: 'Pipedream Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '开发工具', 'API 集成', '免费额度', '工作流自动化'],
  homepageUrl: 'https://pipedream.com',
  githubUrl: 'https://github.com/PipedreamHQ/pipedream',
  docsUrl: 'https://docs.pipedream.com',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费额度 + 按量计费',
  license: '商业许可',
  focus: '开发者友好、代码自定义、API 集成',
  deployment: '云平台，支持本地开发',
  modelSupport: ['支持集成 LLM', 'AI 步骤'],
  connectivity: ['1000+ 预置集成', 'REST API', 'GraphQL'],
  scenarios: ['API 编排', '数据处理', '通知推送', 'Webhook 处理'],
  gfwStatus: '需要代理',
  pitfalls: ['免费额度有限', '复杂场景成本较高'],
  benchmark: { successRate: 88, avgDurationMin: 2.8, retries: 1.2 },
  community: { stars: '5k', release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 9.0, flexibility: 9.2, stability: 8.5, docs: 8.8 },
};
