import type { ToolProfile } from '@/lib/tools/types';

export const plandex: ToolProfile = {
  slug: 'plandex',
  name: 'Plandex',
  tagline: '面向复杂开发任务的计划驱动 Agent',
  summary: '强调任务分解和长链路执行的一致性。',
  vendor: 'Plandex 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['工作流编排', '代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://github.com/plandex-ai/plandex',
  githubUrl: 'https://github.com/plandex-ai/plandex',
  docsUrl: 'https://docs.plandex.ai',
  githubStars: 15123,
  primaryLanguage: "Go",
  pricing: '社区版免费，托管能力付费',
  license: 'MIT',
  focus: '多阶段计划、代码库级重构、任务恢复',
  deployment: 'CLI 安装快，团队部署需要配置统一状态存储。',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['本地模式', '远程执行节点'],
  scenarios: ['复杂开发任务', '长链路执行', '任务恢复'],
  gfwStatus: '直连可用',
  pitfalls: ['计划层级过深时执行时间拉长', '首次接入需要定义项目级约束模板', '并行任务策略需要经验调参'],
  benchmark: { successRate: 83, avgDurationMin: 9.4, retries: 1.4 },
  community: { stars: '13.7k', release: 'v1.11.0', trend: '企业用户增长明显' },
  rating: { security: 8.1, speed: 7.5, flexibility: 8.9, stability: 8.3, docs: 7.7 },
};
