import type { ToolProfile } from '@/lib/tools/types';

export const playwright: ToolProfile = {
  slug: 'playwright',
  name: 'Playwright',
  tagline: '跨浏览器自动化测试框架，68k stars',
  summary: 'Playwright 是一个跨浏览器自动化测试框架，支持Chromium、Firefox和WebKit。适合网页自动化、 测试自动化、 爬虫等场景。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://playwright.dev',
  githubUrl: 'https://github.com/microsoft/playwright',
  docsUrl: 'https://playwright.dev/docs/intro',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '跨浏览器自动化',
  deployment: 'Node.js Runtime, Browser',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['网页自动化', '测试自动化', '爬虫'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要编程知识', '仅限浏览器场景'],
  benchmark: { successRate: 95, avgDurationMin: 0.5, retries: 1.0 },
  community: { stars: '68k', release: 'v1.40.0', trend: '活跃' },
  rating: { security: 9.0, speed: 9.5, flexibility: 9.0, stability: 9.5, docs: 9.5 },
};
