import type { ToolProfile } from '@/lib/tools/types';

export const poe: ToolProfile = {
  slug: 'poe',
  name: 'Poe',
  tagline: '多模型聚合聊天平台',
  summary: 'Poe 是 Quora 推出的多模型聚合聊天平台，支持 GPT-4、Claude 等多种模型，提供 Bot 创建和分享能力。',
  vendor: 'Quora',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['多模态', '个人助手', '商业软件', '对话 AI'],
  homepageUrl: 'https://poe.com',
  githubUrl: null,
  docsUrl: null,
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费 $20/月',
  license: '商业许可',
  focus: '多模型聚合、Bot 创建、对话 AI',
  deployment: 'Web 应用 + 移动 App',
  modelSupport: ['GPT-4', 'Claude', 'Gemini', 'Llama'],
  connectivity: ['Web 界面', '移动 App', 'API'],
  scenarios: ['日常对话', '模型对比', 'Bot 创建', '知识问答'],
  gfwStatus: '需要代理',
  pitfalls: ['消息限额', '高级模型需付费'],
  benchmark: { successRate: 88, avgDurationMin: 2.5, retries: 1.1 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.8, flexibility: 9.0, stability: 8.8, docs: 8.0 },
};
