import type { ToolProfile } from '@/lib/tools/types';

export const powerAutomate: ToolProfile = {
  slug: 'power-automate',
  name: 'Power Automate',
  tagline: '微软自动化平台',
  summary: 'Power Automate 是微软推出的自动化平台，集成 Office 365 和 Azure 生态，提供低代码流程设计和 AI Builder 能力，适合企业快速构建自动化流程。',
  vendor: 'Microsoft',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', '低代码', '商业软件', '微软生态'],
  homepageUrl: 'https://powerautomate.microsoft.com',
  githubUrl: null,
  docsUrl: 'https://docs.microsoft.com/power-automate',
  githubStars: null,
  primaryLanguage: null,
  pricing: '$15-40/月，按用户计费',
  license: '商业许可',
  focus: '工作流自动化、Office 集成、AI Builder',
  deployment: '云服务，支持本地网关',
  modelSupport: ['AI Builder', 'Azure AI', 'GPT-4 集成'],
  connectivity: ['Office 365', 'Azure 服务', '第三方 connector'],
  scenarios: ['审批流程', '邮件自动化', '数据同步', '通知推送'],
  gfwStatus: '需要代理',
  pitfalls: ['国内由世纪互联运营功能受限', '复杂流程需 Premium 许可证'],
  benchmark: { successRate: 87, avgDurationMin: 4.2, retries: 1.2 },
  community: { stars: null, release: '持续更新', trend: '企业市场主流' },
  rating: { security: 9.0, speed: 8.0, flexibility: 8.5, stability: 8.8, docs: 8.8 },
};
