import type { ToolProfile } from '@/lib/tools/types';

export const praisonai: ToolProfile = {
  slug: 'praisonai',
  name: 'PraisonAI',
  tagline: '低代码多 Agent 协作平台',
  summary: 'PraisonAI 是一款低代码的多 Agent 协作平台，支持_yaml_配置快速构建 Agent 工作流，适合非技术人员快速搭建 AI 应用。',
  vendor: 'Mervin Praison',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '低代码', '可视化编排', '企业流程'],
  homepageUrl: 'https://praison.ai',
  githubUrl: 'https://github.com/mervinpraison/PraisonAI',
  docsUrl: 'https://docs.praison.ai',
  lastReleaseDate: "2026-03-21T17:51:29Z",
  latestVersion: "v4.5.82",
  lastCommitDate: "2026-03-23T10:18:26Z",
  githubStars: 5718,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '低代码配置、多 Agent 编排、快速部署',
  deployment: 'Python 包，支持 Docker 部署',
  modelSupport: ['GPT-4', 'Claude', '支持 30+ 模型'],
  connectivity: ['REST API', 'YAML 配置', 'Web 界面'],
  scenarios: ['企业流程自动化', '智能客服', '数据分析', '报告生成'],
  gfwStatus: '直连可用',
  pitfalls: ['部分高级功能需付费', '模型需自行配置'],
  benchmark: { successRate: 76, avgDurationMin: 6.0, retries: 1.6 },
  community: { stars: '2.8k', release: 'v2.1.0', trend: '稳定增长' },
  rating: { security: 7.6, speed: 7.4, flexibility: 8.2, stability: 7.4, docs: 7.5 },
};
