import type { ToolProfile } from '@/lib/tools/types';

export const privategpt: ToolProfile = {
  slug: 'privategpt',
  name: 'PrivateGPT',
  tagline: '本地运行的私有 GPT 实现',
  summary: 'PrivateGPT 是一款完全本地运行的 GPT 实现，支持离线文档问答，数据不出本地，适合对数据隐私有严格要求的场景。',
  vendor: 'Zylon AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '通用任务执行 Agent',
  tags: ['RAG', '开源', '本地优先', '知识库', '企业流程'],
  homepageUrl: 'https://privategpt.dev',
  githubUrl: 'https://github.com/zylon-ai/private-gpt',
  docsUrl: 'https://docs.privategpt.dev',
  githubStars: 54200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '本地文档问答、数据隐私、离线运行',
  deployment: 'Python 包，支持 Docker 部署',
  modelSupport: ['Llama', 'Mistral', '支持 GGUF 格式模型'],
  connectivity: ['本地文件系统', 'REST API', '向量数据库'],
  scenarios: ['私有知识库', '文档检索', '企业搜索', '个人知识管理'],
  gfwStatus: '直连可用',
  pitfalls: ['本地模型推理速度慢', '需要较强硬件支持'],
  benchmark: { successRate: 80, avgDurationMin: 5.5, retries: 1.4 },
  community: { stars: '54.2k', release: 'v0.6.0', trend: '快速增长' },
  rating: { security: 9.0, speed: 6.5, flexibility: 8.2, stability: 7.8, docs: 8.0 },
};
