import type { ToolProfile } from '@/lib/tools/types';

export const puppeteer: ToolProfile = {
  slug: 'puppeteer',
  name: 'Puppeteer',
  tagline: 'Chrome自动化工具，88k stars',
  summary: 'Puppeteer 是一个Chrome自动化工具，支持Headless Chrome和Chromium。适合网页自动化、 测试自动化、 爬虫等场景。',
  vendor: 'Google',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://pptr.dev',
  githubUrl: 'https://github.com/puppeteer/puppeteer',
  docsUrl: 'https://pptr.dev/guides',
  lastReleaseDate: "2026-03-19T13:45:00Z",
  latestVersion: "puppeteer-core-v24.40.0",
  lastCommitDate: "2026-03-23T09:52:58Z",
  githubStars: 93910,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Chrome自动化',
  deployment: 'Node.js Runtime, Browser',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['网页自动化', '测试自动化', '爬虫'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要编程知识', '仅限Chrome场景'],
  benchmark: { successRate: 94, avgDurationMin: 0.6, retries: 1.1 },
  community: { stars: '88k', release: 'v21.5.0', trend: '活跃' },
  rating: { security: 9.0, speed: 9.0, flexibility: 8.5, stability: 9.0, docs: 9.0 },
};
