import type { ToolProfile } from '@/lib/tools/types';

export const pyautogui: ToolProfile = {
  slug: 'pyautogui',
  name: 'PyAutoGUI',
  tagline: 'Python桌面自动化库，9.5k stars',
  summary: 'PyAutoGUI 是一个Python桌面自动化库，能够通过编程控制鼠标和键盘。适合桌面自动化、 GUI测试、 任务自动化等场景。',
  vendor: 'PyAutoGUI Project',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://pyautogui.readthedocs.io',
  githubUrl: 'https://github.com/asweigart/pyautogui',
  docsUrl: 'https://pyautogui.readthedocs.io/en/latest',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'BSD-3-Clause',
  focus: 'Python桌面自动化',
  deployment: 'Python Runtime, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['桌面自动化', 'GUI测试', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要编程知识', '跨平台兼容性有限'],
  benchmark: { successRate: 88, avgDurationMin: 0.3, retries: 1.5 },
  community: { stars: '9.5k', release: 'v0.9.54', trend: '稳定' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 8.5 },
};
