import type { ToolProfile } from '@/lib/tools/types';

export const pyclaw: ToolProfile = {
  slug: 'pyclaw',
  name: 'PyClaw',
  tagline: 'Python原生Claw，Python生态集成',
  summary: 'PyClaw 是用 Python 原生实现的 Claw 桌面自动化框架，提供与 Python 生态无缝集成的桌面控制能力。支持所有 Python 库和框架，适合数据科学、AI 开发场景。',
  vendor: 'OpenClaw Community',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', 'Python'],
  homepageUrl: 'https://github.com/openclaw/pyclaw',
  githubUrl: null,
  docsUrl: 'https://docs.openclaw.org/pyclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Python桌面自动化框架',
  deployment: 'Python Runtime, Conda, Pip',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地 Python 模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API', 'Python 库集成'],
  scenarios: ['数据科学自动化', 'AI 开发辅助', 'Python 脚本自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['性能略低于原生', '依赖 Python 环境', 'GIL 限制'],
  benchmark: { successRate: 83, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '1100', release: 'v1.5.0', trend: '活跃' },
  rating: { security: 7.5, speed: 7.5, flexibility: 9.0, stability: 7.8, docs: 8.5 },
};
