import type { ToolProfile } from '@/lib/tools/types';

export const qwenAgent: ToolProfile = {
  slug: 'qwen-agent',
  name: 'Qwen-Agent',
  tagline: '阿里系开源 Agent 框架',
  summary: '对中文场景与 Qwen 模型生态支持完善。',
  vendor: '阿里云',
  sourceType: '开源',
  region: '国内',
  primaryCategory: '通用任务执行 Agent',
  tags: ['工作流编排', '开源', '云服务', '企业流程', '个人助手'],
  homepageUrl: 'https://github.com/QwenLM/Qwen-Agent',
  githubUrl: 'https://github.com/QwenLM/Qwen-Agent',
  docsUrl: 'https://qwen.readthedocs.io/zh-cn/latest/framework/qwen_agent.html',
  lastReleaseDate: "2025-05-29T09:36:00Z",
  latestVersion: "v0.0.26",
  lastCommitDate: "2026-03-04T08:15:07Z",
  githubStars: 15742,
  primaryLanguage: "Python",
  pricing: '开源免费',
  license: 'Apache-2.0',
  focus: '工具调用、RAG、多 Agent 协作',
  deployment: '本地与云端都可落地，中文文档友好。',
  modelSupport: ['Qwen 系列', 'OpenAI 兼容 API'],
  connectivity: ['本地部署', '阿里云模型服务'],
  scenarios: ['中文业务流程', '企业问答', '自动化助手'],
  gfwStatus: '直连可用',
  pitfalls: ['跨模型迁移需要适配层', '复杂流程监控能力需补齐', '国际生态插件较少'],
  benchmark: { successRate: 82, avgDurationMin: 7.4, retries: 1.6 },
  community: { stars: '9.7k', release: 'v0.3.x', trend: '中文开发者快速增长' },
  rating: { security: 8.2, speed: 8.2, flexibility: 8.1, stability: 7.9, docs: 8.3 },
};
