import type { ToolProfile } from '@/lib/tools/types';

export const railclaw: ToolProfile = {
  slug: 'railwayclaw',
  name: 'Railway Claw',
  tagline: 'Railway 一键部署 Claw 服务',
  summary: '一键部署、快速原型验证的 OpenClaw 云服务。',
  vendor: 'Railway',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://railwayclaw.railway.app',
  githubUrl: null,
  docsUrl: 'https://docs.railway.app/railwayclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按资源计费',
  license: '商业闭源',
  focus: '一键部署、快速原型验证、开发者友好',
  deployment: 'Railway 托管',
  modelSupport: ['Railway 模型', '自定义模型'],
  connectivity: ['Railway 服务', 'API 访问'],
  scenarios: ['快速原型验证', '开发者场景', 'MVP 原型'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 84, avgDurationMin: 5.5, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '独立开发者增长快' },
  rating: { security: 9.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.0 },
};
