import type { ToolProfile } from '@/lib/tools/types';

export const refact: ToolProfile = {
  slug: 'refact',
  name: 'Refact',
  tagline: '自托管代码补全，1.8k stars',
  summary: 'Refact 是一个自托管的代码补全工具，提供代码补全、代码生成等功能。支持多种模型，适合企业内部使用。',
  vendor: 'SmallCloudAI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://refact.ai',
  githubUrl: 'https://github.com/smallcloudai/refact',
  docsUrl: 'https://refact.ai/docs',
  githubStars: 3524,
  primaryLanguage: "Rust",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '自托管代码补全',
  deployment: 'Docker, 本地部署',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API'],
  scenarios: ['代码补全', '代码生成', '企业内部使用'],
  gfwStatus: '直连可用',
  pitfalls: ['需要本地部署', '模型配置复杂', '文档较少'],
  benchmark: { successRate: 82, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '1.8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 7.5 },
};
