import type { ToolProfile } from '@/lib/tools/types';

export const replitAgent: ToolProfile = {
  slug: 'replit-agent',
  name: 'Replit Agent',
  tagline: '云开发环境内置全流程代理',
  summary: '从原型到部署一体化体验，适合快速验证产品。',
  vendor: 'Replit',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '闭源', '云服务', 'MVP 原型', '个人助手'],
  homepageUrl: 'https://replit.com',
  githubUrl: null,
  docsUrl: 'https://docs.replit.com/replitai/agent',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅 + 算力计费',
  license: '商业闭源',
  focus: '云开发、自动编码、部署上线',
  deployment: '完全云端化，使用门槛低。',
  modelSupport: ['Replit Model', 'OpenAI 兼容模型'],
  connectivity: ['Replit 云平台'],
  scenarios: ['MVP 开发', '教学场景', '小团队原型'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['企业内网系统接入受限', '复杂架构可控性较低', '成本随使用量增长较快'],
  benchmark: { successRate: 78, avgDurationMin: 6.8, retries: 1.9 },
  community: { stars: '商业产品', release: '周更', trend: '独立开发者增长快' },
  rating: { security: 7.1, speed: 8.5, flexibility: 7.2, stability: 7.9, docs: 8.0 },
};
