import type { ToolProfile } from '@/lib/tools/types';

export const robocorp: ToolProfile = {
  slug: 'robocorp',
  name: 'Robocorp',
  tagline: 'Python RPA框架，5.2k stars',
  summary: 'Robocorp 是一个Python RPA框架，支持云端和本地部署。适合RPA自动化、 任务自动化、 流程自动化等场景。',
  vendor: 'Robocorp',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://robocorp.com',
  githubUrl: 'https://github.com/robocorp/rcc',
  docsUrl: 'https://robocorp.com/docs',
  githubStars: 5200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Python RPA框架',
  deployment: 'Python Runtime, Cloud, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['RPA自动化', '任务自动化', '流程自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['无AI能力', '需要Python知识', '云端服务需要付费'],
  benchmark: { successRate: 85, avgDurationMin: 1.0, retries: 1.5 },
  community: { stars: '5.2k', release: 'v17.10.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.5, stability: 8.0, docs: 8.5 },
};
