import type { ToolProfile } from '@/lib/tools/types';

export const robotgo: ToolProfile = {
  slug: 'robotgo',
  name: 'RobotGo',
  tagline: 'Go桌面自动化库，2.1k stars',
  summary: 'RobotGo 是一个Go桌面自动化库，支持鼠标、键盘、屏幕和位图操作。适合桌面自动化、 GUI测试、 任务自动化等场景。',
  vendor: 'RobotGo Project',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先', 'Go'],
  homepageUrl: 'https://robotn.io',
  githubUrl: 'https://github.com/go-vgo/robotgo',
  docsUrl: 'https://github.com/go-vgo/robotgo#readme',
  lastReleaseDate: "2026-02-27T16:40:45Z",
  latestVersion: "v1.0.1",
  lastCommitDate: "2026-03-02T19:11:39Z",
  githubStars: 10657,
  primaryLanguage: "Go",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Go桌面自动化',
  deployment: 'Go Runtime, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['桌面自动化', 'GUI测试', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要Go知识', '跨平台兼容性有限'],
  benchmark: { successRate: 83, avgDurationMin: 0.3, retries: 1.5 },
  community: { stars: '2.1k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 9.0, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};
