import type { ToolProfile } from '@/lib/tools/types';

export const robotframework: ToolProfile = {
  slug: 'robotframework',
  name: 'Robot Framework',
  tagline: '通用自动化测试框架，9.2k stars',
  summary: 'Robot Framework 是一个通用自动化测试框架，支持关键字驱动测试。适合测试自动化、 RPA自动化、 任务自动化等场景。',
  vendor: 'Robot Framework Foundation',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://robotframework.org',
  githubUrl: 'https://github.com/robotframework/robotframework',
  docsUrl: 'https://robotframework.org/robotframework',
  githubStars: 9200,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '通用自动化测试',
  deployment: 'Python Runtime, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['测试自动化', 'RPA自动化', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要关键字知识', '学习曲线较陡'],
  benchmark: { successRate: 85, avgDurationMin: 0.8, retries: 1.5 },
  community: { stars: '9.2k', release: 'v6.1.1', trend: '活跃' },
  rating: { security: 8.0, speed: 8.0, flexibility: 9.0, stability: 8.5, docs: 9.0 },
};
