import type { ToolProfile } from '@/lib/tools/types';

export const roocode: ToolProfile = {
  slug: 'roo-code',
  name: 'Roo Code',
  tagline: 'VSCode AI 助手，4.2k stars',
  summary: 'Roo Code 是一个 VSCode AI 助手，提供代码补全、代码生成等功能。支持多种模型，适合日常开发。',
  vendor: 'Roo Vet',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://roo.dev',
  githubUrl: 'https://github.com/RooVetGit/Roo-Cline',
  docsUrl: 'https://docs.roo.dev',
  githubStars: 4200,
  primaryLanguage: 'TypeScript',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'VSCode AI 助手',
  deployment: 'VSCode Extension',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码补全', '代码生成', '日常开发'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖 VSCode', '功能相对简单', '文档较少'],
  benchmark: { successRate: 82, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: '4.2k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 7.5 },
};
