import type { ToolProfile } from '@/lib/tools/types';

export const rpapython: ToolProfile = {
  slug: 'rpapython',
  name: 'RPA-Python',
  tagline: 'Python RPA库，3.8k stars',
  summary: 'RPA-Python 是一个Python RPA库，支持网页自动化、 桌面自动化、 OCR等。适合RPA自动化、 测试自动化、 任务自动化等场景。',
  vendor: 'TagUI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/tebelorg/RPA-Python',
  githubUrl: 'https://github.com/tebelorg/RPA-Python',
  docsUrl: 'https://github.com/tebelorg/RPA-Python#readme',
  githubStars: 3800,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: 'Python RPA库',
  deployment: 'Python Runtime, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['RPA自动化', '测试自动化', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要Python知识', '跨平台兼容性有限'],
  benchmark: { successRate: 80, avgDurationMin: 1.0, retries: 2.0 },
  community: { stars: '3.8k', release: 'v1.50.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 7.5 },
};
