import type { ToolProfile } from '@/lib/tools/types';

export const rylenaAwesomeOpenclaw: ToolProfile = {
  slug: 'rylena-awesome-openclaw',
  name: 'Awesome OpenClaw (Rylena)',
  tagline: 'OpenClaw 统一资源列表',
  summary: 'Rylena Awesome OpenClaw 是一个整合的 OpenClaw 资源列表，将设置指南、生态系统资源、所有列出的用例和完整的技能目录合并到一个统一的 README 文档中。提供一站式的 OpenClaw 资源参考。',
  vendor: 'rylena',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['开源', '社区生态', '开发工具', '文档工具', 'AI', '研究'],
  homepageUrl: 'https://github.com/rylena/awesome-openclaw',
  githubUrl: 'https://github.com/rylena/awesome-openclaw',
  docsUrl: 'https://github.com/rylena/awesome-openclaw#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '资源聚合、统一文档、用例集合、技能目录',
  deployment: 'GitHub 仓库，可在线浏览',
  modelSupport: ['OpenClaw', '多资源集成'],
  connectivity: ['GitHub 集成', '社区贡献', '持续更新'],
  scenarios: ['资源发现', '学习参考', '用例研究', '技能查询'],
  gfwStatus: '需要代理',
  pitfalls: ['项目较新', '内容持续更新需关注'],
  benchmark: { successRate: 90, avgDurationMin: 1.0, retries: 1.0 },
  community: { stars: '8', release: 'v1.0.0', trend: '早期开发' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.5, stability: 7.5, docs: 8.0 },
};
