import type { ToolProfile } from '@/lib/tools/types';

export const salesforceclaw: ToolProfile = {
  slug: 'salesforceclaw',
  name: 'Salesforce Einstein GPT Claw',
  tagline: 'Salesforce CRM 场景 Claw 服务',
  summary: 'CRM 深度集成、Einstein GPT 的 OpenClaw 云服务。',
  vendor: 'Salesforce',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://salesforceclaw.salesforce.com',
  githubUrl: null,
  docsUrl: 'https://docs.salesforce.com/salesforceclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业闭源',
  focus: 'CRM 深度集成、Einstein GPT、企业场景',
  deployment: 'Salesforce Cloud 托管',
  modelSupport: ['Einstein GPT', 'Salesforce 模型'],
  connectivity: ['Salesforce Cloud 服务', 'API 访问'],
  scenarios: ['CRM 场景', '销售自动化', '客户服务'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 84, avgDurationMin: 6.0, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业试点增长快' },
  rating: { security: 9.0, speed: 8.0, flexibility: 7.0, stability: 8.5, docs: 8.0 },
};
