import type { ToolProfile } from '@/lib/tools/types';

export const sapclaw: ToolProfile = {
  slug: 'sapclaw',
  name: 'SAP Joule Claw',
  tagline: 'SAP Joule 企业 AI 助手 Claw 服务',
  summary: 'ERP 深度集成、HR 场景的 OpenClaw 云服务。',
  vendor: 'SAP',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://sapclaw.sap.com',
  githubUrl: null,
  docsUrl: 'https://docs.sap.com/sapclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业闭源',
  focus: 'ERP 深度集成、HR 场景、HCM 集成',
  deployment: 'SAP Cloud 托管',
  modelSupport: ['SAP 模型', '自定义模型'],
  connectivity: ['SAP Cloud 服务', 'API 访问'],
  scenarios: ['HR 场景', 'ERP 集成', '企业流程'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 83, avgDurationMin: 6.5, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业客户增长稳定' },
  rating: { security: 9.0, speed: 8.0, flexibility: 7.0, stability: 8.5, docs: 8.0 },
};
