import type { ToolProfile } from '@/lib/tools/types';

export const screenpilot: ToolProfile = {
  slug: 'screenpilot',
  name: 'ScreenPilot',
  tagline: '屏幕操作Agent，1.5k stars',
  summary: 'ScreenPilot 是一个屏幕操作Agent，能够通过视觉理解自动操作屏幕元素。支持多模型、 适合屏幕自动化、 GUI测试等场景。',
  vendor: 'ScreenPilot AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/ScreenPilot/ScreenPilot',
  githubUrl: 'https://github.com/ScreenPilot/ScreenPilot',
  docsUrl: 'https://github.com/ScreenPilot/ScreenPilot#readme',
  githubStars: 1500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '屏幕操作自动化',
  deployment: 'Python Runtime, Desktop',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['屏幕自动化', 'GUI测试', '任务自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限桌面场景', '需要桌面环境', '复杂屏幕支持有限'],
  benchmark: { successRate: 70, avgDurationMin: 6.0, retries: 3.0 },
  community: { stars: '1.5k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.0, speed: 6.0, flexibility: 7.0, stability: 6.5, docs: 6.0 },
};
