import type { ToolProfile } from '@/lib/tools/types';

export const sdkworkClawStudio: ToolProfile = {
  slug: 'sdkwork-claw-studio',
  name: 'Sdkwork Claw Studio',
  tagline: 'Claw 生态系统管理平台',
  summary: 'Sdkwork Claw Studio 是一个开源平台，用于安装和管理 Claw 生态系统。它提供了一个统一的工作空间来安装、配置和运行 OpenClaw、ZeroClaw、IronClaw 等各种 Claw 组件，以及 Skills 和 Apps，使开发者能够高效地构建和运营模块化 AI 系统。',
  vendor: 'Sdkwork Cloud',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', '开发工具', '插件生态'],
  homepageUrl: 'https://github.com/Sdkwork-Cloud/claw-studio',
  githubUrl: 'https://github.com/Sdkwork-Cloud/claw-studio',
  docsUrl: 'https://github.com/Sdkwork-Cloud/claw-studio#readme',
  githubStars: 1,
  primaryLanguage: "TypeScript",
  pricing: '免费开源',
  license: 'AGPL-3.0',
  focus: 'Claw 生态管理、组件安装配置、统一工作空间',
  deployment: '本地部署，支持 Docker',
  modelSupport: ['OpenClaw', 'ZeroClaw', 'IronClaw', '多 Claw 组件'],
  connectivity: ['本地运行', '组件管理', 'Skills/Apps 集成'],
  scenarios: ['Claw 生态管理', '组件安装配置', 'AI 系统构建', '开发者工作空间'],
  gfwStatus: '需要代理',
  pitfalls: ['需要 Claw 生态知识', '配置复杂度中等'],
  benchmark: { successRate: 85, avgDurationMin: 3.0, retries: 1.0 },
  community: { stars: '1', release: 'v1.0.0', trend: '早期开发' },
  rating: { security: 8.0, speed: 8.0, flexibility: 8.5, stability: 7.5, docs: 7.0 },
};
