import type { ToolProfile } from '@/lib/tools/types';

export const seeact: ToolProfile = {
  slug: 'seeact',
  name: 'SeeAct',
  tagline: '网页视觉操作Agent，2.1k stars',
  summary: 'SeeAct 是一个网页视觉操作Agent，能够通过视觉理解自动操作网页元素。支持多模型、 适合网页自动化、 视觉测试等场景。',
  vendor: 'OSU NLP Group',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/OSU-NLP-Group/SeeAct',
  githubUrl: 'https://github.com/OSU-NLP-Group/SeeAct',
  docsUrl: 'https://github.com/OSU-NLP-Group/SeeAct#readme',
  githubStars: 2100,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: '网页视觉操作',
  deployment: 'Python Runtime, Browser',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'Gemini Pro'],
  connectivity: ['OpenAI API', 'Anthropic API', 'Google AI API'],
  scenarios: ['网页自动化', '视觉测试', 'UI测试'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限浏览器场景', '需要视觉模型', '复杂网页支持有限'],
  benchmark: { successRate: 78, avgDurationMin: 4.0, retries: 2.3 },
  community: { stars: '2.1k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.0, speed: 7.5, flexibility: 7.5, stability: 7.0, docs: 7.5 },
};
