import type { ToolProfile } from '@/lib/tools/types';

export const selenium: ToolProfile = {
  slug: 'selenium',
  name: 'Selenium',
  tagline: '网页自动化测试框架，30k stars',
  summary: 'Selenium 是一个网页自动化测试框架，支持多种浏览器和编程语言。适合网页自动化、 测试自动化、 爬虫等场景。',
  vendor: 'Selenium Project',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://www.selenium.dev',
  githubUrl: 'https://github.com/SeleniumHQ/selenium',
  docsUrl: 'https://www.selenium.dev/documentation',
  githubStars: 34167,
  primaryLanguage: "Java",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '网页自动化测试',
  deployment: 'Java Runtime, Browser',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['网页自动化', '测试自动化', '爬虫'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要编程知识', '仅限浏览器场景'],
  benchmark: { successRate: 92, avgDurationMin: 0.8, retries: 1.2 },
  community: { stars: '30k', release: 'v4.15.0', trend: '稳定' },
  rating: { security: 8.5, speed: 8.0, flexibility: 9.0, stability: 9.0, docs: 9.0 },
};
