import type { ToolProfile } from '@/lib/tools/types';

export const semanticKernel: ToolProfile = {
  slug: 'semantic-kernel',
  name: 'Semantic Kernel',
  tagline: '微软AI SDK，23.5k stars',
  summary: 'Semantic Kernel 是微软开发的AI SDK，提供了构建AI应用所需的各种组件和工具。支持多种模型、插件系统、Agent编排，是微软AI生态的核心组件。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['工作流编排', '插件生态', '开源', '自部署'],
  homepageUrl: 'https://learn.microsoft.com/semantic-kernel',
  githubUrl: 'https://github.com/microsoft/semantic-kernel',
  docsUrl: 'https://learn.microsoft.com/semantic-kernel',
  githubStars: 27528,
  primaryLanguage: "C#",
  pricing: '免费开源',
  license: 'MIT',
  focus: '微软AI SDK',
  deployment: '.NET Runtime, Python, Java',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', 'Azure OpenAI'],
  connectivity: ['Azure OpenAI', 'OpenAI API', '本地模型'],
  scenarios: ['AI应用开发', '插件系统', 'Agent构建', '企业集成'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线陡峭', '微软生态依赖', '文档分散'],
  benchmark: { successRate: 85, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '23.5k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 8.5, speed: 8.0, flexibility: 8.5, stability: 8.5, docs: 8.0 },
};
