import type { ToolProfile } from '@/lib/tools/types';

export const sensechatclaw: ToolProfile = {
  slug: 'sensechatclaw',
  name: 'SenseChatClaw',
  tagline: '商汤日日新大模型平台 Claw 服务',
  summary: '基于日日新大模型、视觉能力的 OpenClaw 云服务。',
  vendor: '商汤科技',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://sensechatclaw.sensetime.com',
  githubUrl: null,
  docsUrl: 'https://docs.sensetime.com/sensechatclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业定价',
  license: '商业闭源',
  focus: '日日新大模型、视觉能力、大模型平台',
  deployment: '商汤云托管',
  modelSupport: ['日日新系列', 'SenseChat 大模型'],
  connectivity: ['商汤云服务', 'API 访问'],
  scenarios: ['视觉理解', '企业场景', '知识问答'],
  gfwStatus: '直连可用',
  pitfalls: ['生态成熟度仍在完善', '复杂多 Agent 场景能力边界需验证', '跨平台可移植性较弱'],
  benchmark: { successRate: 82, avgDurationMin: 6.0, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业场景采用增长' },
  rating: { security: 8.0, speed: 8.2, flexibility: 7.5, stability: 7.8, docs: 7.5 },
};
