import type { ToolProfile } from '@/lib/tools/types';

export const servicenowclaw: ToolProfile = {
  slug: 'servicenowclaw',
  name: 'ServiceNow Now Assist Claw',
  tagline: 'ServiceNow IT 服务 AI Claw 服务',
  summary: 'ITSM 集成、企业服务自动化的 OpenClaw 云服务。',
  vendor: 'ServiceNow',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://servicenowclaw.servicenow.com',
  githubUrl: null,
  docsUrl: 'https://docs.servicenow.com/servicenowclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业闭源',
  focus: 'ITSM 集成、企业服务自动化、IT 流程',
  deployment: 'ServiceNow Cloud 托管',
  modelSupport: ['ServiceNow 模型', '自定义模型'],
  connectivity: ['ServiceNow Cloud 服务', 'API 访问'],
  scenarios: ['IT 服务自动化', 'ITSM 流程', '企业场景'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 83, avgDurationMin: 6.5, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业客户增长稳定' },
  rating: { security: 9.0, speed: 8.0, flexibility: 7.0, stability: 8.5, docs: 8.0 },
};
