import type { ToolProfile } from '@/lib/tools/types';

export const shengsuclaw: ToolProfile = {
  slug: 'shengsuclaw',
  name: 'ShengsuClaw',
  tagline: '盛派科技 Claw 服务',
  summary: '面向行业解决方案的 OpenClaw 云服务。',
  vendor: '盛派科技',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://shengsuclaw.shengpai.com',
  githubUrl: null,
  docsUrl: 'https://docs.shengpai.com/shengsuclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业定价',
  license: '商业闭源',
  focus: '行业解决方案、企业场景、垂直行业',
  deployment: '盛派云托管',
  modelSupport: ['多种模型', '行业定制模型'],
  connectivity: ['盛派云服务', 'API 访问'],
  scenarios: ['行业解决方案', '企业流程', '垂直行业'],
  gfwStatus: '直连可用',
  pitfalls: ['生态成熟度仍在完善', '复杂多 Agent 场景能力边界需验证', '跨平台可移植性较弱'],
  benchmark: { successRate: 80, avgDurationMin: 7.0, retries: 1.8 },
  community: { stars: '官方服务', release: '持续更新', trend: '行业客户增长稳定' },
  rating: { security: 8.0, speed: 7.8, flexibility: 7.0, stability: 7.5, docs: 7.0 },
};
