import type { ToolProfile } from '@/lib/tools/types';

export const sikulix: ToolProfile = {
  slug: 'sikulix',
  name: 'SikuliX',
  tagline: '视觉自动化工具，2.8k stars',
  summary: 'SikuliX 是一个视觉自动化工具，能够通过图像识别自动操作GUI元素。适合桌面自动化、 GUI测试、 任务自动化等场景。',
  vendor: 'SikuliX Project',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://sikulix.github.io',
  githubUrl: 'https://github.com/RaiMan/SikuliX1',
  docsUrl: 'https://sikulix.github.io/docs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '视觉自动化',
  deployment: 'Java Runtime, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['桌面自动化', 'GUI测试', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要图像匹配', '跨平台兼容性有限'],
  benchmark: { successRate: 78, avgDurationMin: 1.0, retries: 2.0 },
  community: { stars: '2.8k', release: 'v2.0.5', trend: '稳定' },
  rating: { security: 7.5, speed: 7.0, flexibility: 8.0, stability: 7.5, docs: 7.5 },
};
