import type { ToolProfile } from '@/lib/tools/types';

export const skyvern: ToolProfile = {
  slug: 'skyvern',
  name: 'Skyvern',
  tagline: 'AI浏览器自动化， 8.9k stars',
  summary: 'Skyvern 是一个AI驱动的浏览器自动化工具，能够通过视觉理解自动操作网页。支持多模型、无需选择器， 适合网页自动化、 电商自动化等场景。',
  vendor: 'Skyvern AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/Skyvern-AI/skyvern',
  githubUrl: 'https://github.com/Skyvern-AI/skyvern',
  docsUrl: 'https://docs.skyvern.ai',
  githubStars: 20898,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'AGPL-3.0',
  focus: 'AI浏览器自动化',
  deployment: 'Python Runtime, Docker',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['网页自动化', '电商自动化', '数据采集'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限浏览器场景', '需要视觉模型', '复杂网页支持有限'],
  benchmark: { successRate: 82, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '8.9k', release: 'v0.1.0', trend: '活跃' },
  rating: { security: 7.5, speed: 8.0, flexibility: 8.0, stability: 7.5, docs: 8.0 },
};
