import type { ToolProfile } from '@/lib/tools/types';

export const smoldeveloper: ToolProfile = {
  slug: 'smol-developer',
  name: 'Smol Developer',
  tagline: '极简 AI 开发，12.4k stars',
  summary: 'Smol Developer 是一个极简的 AI 开发工具，提供代码生成、项目初始化等功能。支持多种模型，适合快速原型开发。',
  vendor: 'Smol AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://smol.ai',
  githubUrl: 'https://github.com/smol-ai/developer',
  docsUrl: 'https://smol.ai/docs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2024-04-07T07:11:03Z",
  githubStars: 12202,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '极简 AI 开发',
  deployment: 'Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['代码生成', '项目初始化', '快速原型'],
  gfwStatus: '需要代理',
  pitfalls: ['功能精简', '复杂项目支持有限', '文档较少'],
  benchmark: { successRate: 80, avgDurationMin: 2.5, retries: 1.5 },
  community: { stars: '12.4k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 8.0, flexibility: 7.5, stability: 7.5, docs: 7.5 },
};
