import type { ToolProfile } from '@/lib/tools/types';

export const smolDeveloper: ToolProfile = {
  slug: 'smol-developer',
  name: 'smol-developer',
  tagline: 'AI开发者代理，15k stars',
  summary: 'smol-developer 是一个AI开发者代理，能够自主完成小型开发任务。适合代码生成、 开发辅助、 原型开发等场景。',
  vendor: 'smol-ai',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/smol-ai/developer',
  githubUrl: 'https://github.com/smol-ai/developer',
  docsUrl: 'https://github.com/smol-ai/developer#readme',
  githubStars: 15000,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI开发者代理',
  deployment: 'Python Runtime, CLI',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['OpenAI API', 'Anthropic API'],
  scenarios: ['代码生成', '开发辅助', '原型开发'],
  gfwStatus: '需要代理',
  pitfalls: ['需要API密钥', '复杂任务支持有限', '需要人工审核'],
  benchmark: { successRate: 72, avgDurationMin: 5.0, retries: 2.5 },
  community: { stars: '15k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.0, speed: 7.0, flexibility: 8.0, stability: 7.0, docs: 7.5 },
};
