import type { ToolProfile } from '@/lib/tools/types';

export const snowflakeclaw: ToolProfile = {
  slug: 'snowflakeclaw',
  name: 'Snowflake Cortex Claw',
  tagline: 'Snowflake 数据 AI Claw 服务',
  summary: '数据仓库集成、数据 AI 的 OpenClaw 云服务。',
  vendor: 'Snowflake',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://snowflakeclaw.snowflake.com',
  githubUrl: null,
  docsUrl: 'https://docs.snowflake.com/snowflakeclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按使用计费',
  license: '商业闭源',
  focus: '数据仓库集成、数据 AI、企业场景',
  deployment: 'Snowflake 托管',
  modelSupport: ['Snowflake 模型', '自定义模型'],
  connectivity: ['Snowflake 服务', 'API 访问'],
  scenarios: ['数据 AI', '数据分析', '企业场景'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 84, avgDurationMin: 6.0, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业试点增长快' },
  rating: { security: 9.0, speed: 8.5, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};
