import type { ToolProfile } from '@/lib/tools/types';

export const sourcegraphCody: ToolProfile = {
  slug: 'sourcegraph-cody',
  name: 'Sourcegraph Cody',
  tagline: '企业级代码 AI 助手',
  summary: 'Cody 是 Sourcegraph 推出的企业级代码 AI 助手，基于代码图谱理解提供精准的代码生成、解释、修复能力，适合大型企业代码库。',
  vendor: 'Sourcegraph',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '企业流程', '商业软件', '代码理解', '开发工具'],
  homepageUrl: 'https://sourcegraph.com/cody',
  githubUrl: null,
  docsUrl: 'https://docs.sourcegraph.com/cody',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/企业付费',
  license: '商业许可',
  focus: '代码图谱、精准理解、企业集成',
  deployment: 'VS Code/JetBrains 插件 + 企业部署',
  modelSupport: ['GPT-4', 'Claude', '混合模型'],
  connectivity: ['Sourcegraph 后端', 'IDE 插件', '企业代码库'],
  scenarios: ['代码理解', '代码生成', '重构', '知识传承'],
  gfwStatus: '需要代理',
  pitfalls: ['企业部署成本高', '需 Sourcegraph 后端'],
  benchmark: { successRate: 87, avgDurationMin: 3.5, retries: 1.2 },
  community: { stars: null, release: '持续更新', trend: '企业市场增长' },
  rating: { security: 9.0, speed: 8.5, flexibility: 8.8, stability: 8.8, docs: 8.5 },
};
