import type { ToolProfile } from '@/lib/tools/types';

export const stackblitz: ToolProfile = {
  slug: 'stackblitz',
  name: 'StackBlitz',
  tagline: 'WebContainer AI 开发平台',
  summary: 'StackBlitz 是基于 WebContainer 技术的在线开发平台，提供 AI 辅助编程能力，支持在浏览器中运行 Node.js 应用。',
  vendor: 'StackBlitz',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', '云 IDE', '商业软件', '前端开发', 'Node.js'],
  homepageUrl: 'https://stackblitz.com',
  githubUrl: null,
  docsUrl: 'https://developer.stackblitz.com',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费订阅',
  license: '商业许可',
  focus: 'WebContainer、浏览器开发、AI 辅助',
  deployment: '云服务平台',
  modelSupport: ['AI 辅助', '多模型支持'],
  connectivity: ['Web IDE', 'npm 集成', 'GitHub 同步'],
  scenarios: ['原型开发', '前端开发', '教学演示', '快速分享'],
  gfwStatus: '需要代理',
  pitfalls: ['云端依赖', '大型项目性能受限'],
  benchmark: { successRate: 85, avgDurationMin: 3.5, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.5, speed: 8.0, flexibility: 8.8, stability: 8.5, docs: 8.2 },
};
