import type { ToolProfile } from '@/lib/tools/types';

export const stagehand: ToolProfile = {
  slug: 'stagehand',
  name: 'Stagehand',
  tagline: 'AI网页操作库，10.2k stars',
  summary: 'Stagehand 是一个AI网页操作库， 能够通过自然语言指令控制网页。支持多模型、 适合网页自动化、 测试自动化等场景。',
  vendor: 'Browserbase',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/Browserbase/stagehand',
  githubUrl: 'https://github.com/Browserbase/stagehand',
  docsUrl: 'https://docs.stagehand.dev',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: 'AI网页操作库',
  deployment: 'Node.js Runtime, Browser',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', '本地模型'],
  scenarios: ['网页自动化', '测试自动化', '数据采集'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限浏览器场景', '需要浏览器环境', '复杂操作支持有限'],
  benchmark: { successRate: 80, avgDurationMin: 3.5, retries: 2.2 },
  community: { stars: '10.2k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.0, speed: 8.5, flexibility: 8.0, stability: 7.5, docs: 8.5 },
};
