import type { ToolProfile } from '@/lib/tools/types';

export const starcoder: ToolProfile = {
  slug: 'starcoder',
  name: 'StarCoder',
  tagline: 'BigCode 代码模型，20.1k stars',
  summary: 'StarCoder 是 BigCode 项目开发的代码模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'BigCode',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://bigcode-project.github.io',
  githubUrl: 'https://github.com/bigcode-project/starcoder',
  docsUrl: 'https://bigcode-project.github.io/docs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'BigCode',
  focus: 'BigCode 代码模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['StarCoder', '本地模型'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '需要代理',
  pitfalls: ['许可证限制', '资源占用较高', '商业使用受限'],
  benchmark: { successRate: 82, avgDurationMin: 1.8, retries: 1.2 },
  community: { stars: '20.1k', release: 'v2.0.0', trend: '活跃' },
  rating: { security: 8.0, speed: 8.5, flexibility: 8.0, stability: 8.0, docs: 8.5 },
};
