import type { ToolProfile } from '@/lib/tools/types';

export const stepclaw: ToolProfile = {
  slug: 'stepclaw',
  name: 'StepClaw',
  tagline: '阶跃星辰多模态 Claw 服务',
  summary: '基于 Step 大模型的多模态 OpenClaw 云服务。',
  vendor: '阶跃星辰',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://stepclaw.stepfun.com',
  githubUrl: null,
  docsUrl: 'https://platform.stepfun.com/docs/stepclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: 'API 计费',
  license: '商业闭源',
  focus: 'Step 大模型、多模态能力、企业智能体',
  deployment: '阶跃云托管',
  modelSupport: ['Step 系列', 'Step 大模型'],
  connectivity: ['阶跃云服务', 'API 访问'],
  scenarios: ['多模态交互', '企业智能体', '知识问答'],
  gfwStatus: '直连可用',
  pitfalls: ['生态成熟度仍在完善', '复杂多 Agent 场景能力边界需验证', '跨平台可移植性较弱'],
  benchmark: { successRate: 82, avgDurationMin: 6.2, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '多模态场景采用增长' },
  rating: { security: 8.0, speed: 8.3, flexibility: 7.5, stability: 7.8, docs: 7.5 },
};
