import type { ToolProfile } from '@/lib/tools/types';

export const superagi: ToolProfile = {
  slug: 'superagi',
  name: 'SuperAGI',
  tagline: '企业级多 Agent 协作框架',
  summary: 'SuperAGI 是一款企业级的多 Agent 协作框架，支持 Agent 编排、资源管理、性能监控，适合构建复杂的企业自动化流程。',
  vendor: 'TransformerOptimus',
  sourceType: '开源',
  region: '全球',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '企业流程', '开源', '工作流自动化', '多模态'],
  homepageUrl: 'https://superagi.com',
  githubUrl: 'https://github.com/TransformerOptimus/SuperAGI',
  docsUrl: 'https://docs.superagi.com',
  lastReleaseDate: "2024-01-16T14:21:23Z",
  latestVersion: "v0.0.14",
  lastCommitDate: "2025-01-22T22:14:07Z",
  githubStars: 17294,
  primaryLanguage: "Python",
  pricing: '免费开源，企业版付费',
  license: 'MIT',
  focus: '多 Agent 编排、资源调度、性能监控',
  deployment: 'Docker 部署，支持 K8s',
  modelSupport: ['GPT-4', 'Claude', 'Llama', '支持自部署模型'],
  connectivity: ['REST API', 'gRPC', '数据库连接', '消息队列'],
  scenarios: ['企业流程自动化', '客户服务', '数据分析', '知识管理'],
  gfwStatus: '直连可用',
  pitfalls: ['配置复杂度较高', '需要一定技术门槛'],
  benchmark: { successRate: 76, avgDurationMin: 9.2, retries: 1.8 },
  community: { stars: '16.2k', release: 'v2.8.0', trend: '稳定增长' },
  rating: { security: 8.0, speed: 7.4, flexibility: 8.5, stability: 7.5, docs: 7.6 },
};
