import type { ToolProfile } from '@/lib/tools/types';

export const swarm: ToolProfile = {
  slug: 'swarm',
  name: 'Swarm',
  tagline: 'OpenAI 实验性多 Agent 框架',
  summary: 'Swarm 是 OpenAI 推出的实验性多 Agent 框架，提供简洁的 API 和轮转（handoff）机制，适合探索多 Agent 协作模式。',
  vendor: 'OpenAI',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '实验性', '开发工具'],
  homepageUrl: null,
  githubUrl: 'https://github.com/openai/swarm',
  docsUrl: 'https://github.com/openai/swarm',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: "2025-03-11T17:27:22Z",
  githubStars: 21210,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '多 Agent 轮转、简洁 API、实验性设计',
  deployment: 'Python 包，pip 安装',
  modelSupport: ['GPT-4', 'GPT-3.5', 'OpenAI 模型'],
  connectivity: ['OpenAI API', '本地调用'],
  scenarios: ['多 Agent 研究', '原型验证', '教学演示', '概念验证'],
  gfwStatus: '需要代理',
  pitfalls: ['实验性项目不推荐生产使用', '功能仍在迭代'],
  benchmark: { successRate: 72, avgDurationMin: 5.0, retries: 1.7 },
  community: { stars: '15.2k', release: 'v0.1.0', trend: '实验阶段' },
  rating: { security: 7.2, speed: 7.5, flexibility: 8.0, stability: 6.5, docs: 7.0 },
};
