import type { ToolProfile } from '@/lib/tools/types';

export const sweep: ToolProfile = {
  slug: 'sweep',
  name: 'Sweep',
  tagline: 'GitHub 自动修复，7.5k stars',
  summary: 'Sweep 是一个 GitHub 自动修复工具，能够自动检测和修复代码问题。支持多种模型，适合代码维护、Bug 修复等场景。',
  vendor: 'Sweep AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://sweep.dev',
  githubUrl: 'https://github.com/sweepai/sweep',
  docsUrl: 'https://sweep.dev/docs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: 'GitHub 自动修复',
  deployment: 'GitHub Actions, Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['OpenAI API', 'Anthropic API', 'GitHub API'],
  scenarios: ['代码维护', 'Bug 修复', '代码审查'],
  gfwStatus: '需要代理',
  pitfalls: ['依赖 GitHub', '复杂 Bug 修复有限', '需要配置'],
  benchmark: { successRate: 75, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '7.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 7.5, flexibility: 7.5, stability: 7.5, docs: 8.0 },
};
