import type { ToolProfile } from '@/lib/tools/types';

export const sweep: ToolProfile = {
  slug: 'sweep',
  name: 'Sweep',
  tagline: 'GitHub自动化助手，8k stars',
  summary: 'Sweep 是一个GitHub自动化助手，能够自动修复bug、 实现功能、 优化代码。适合代码生成、 代码审查、 GitHub自动化等场景。',
  vendor: 'Sweep AI',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://sweep.dev',
  githubUrl: 'https://github.com/sweepai/sweep',
  docsUrl: 'https://docs.sweep.dev',
  githubStars: 8000,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'MIT',
  focus: 'GitHub自动化助手',
  deployment: 'Cloud, Self-hosted',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1'],
  connectivity: ['OpenAI API', 'Anthropic API', 'GitHub API'],
  scenarios: ['代码生成', '代码审查', 'GitHub自动化'],
  gfwStatus: '需要代理',
  pitfalls: ['需要GitHub权限', '需要API密钥', '复杂任务支持有限'],
  benchmark: { successRate: 78, avgDurationMin: 3.5, retries: 2.0 },
  community: { stars: '8k', release: 'v1.0.0', trend: '活跃' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.0, stability: 7.5, docs: 8.0 },
};
