import type { ToolProfile } from '@/lib/tools/types';

export const tabby: ToolProfile = {
  slug: 'tabby',
  name: 'Tabby',
  tagline: '自托管代码助手，22.4k stars',
  summary: 'Tabby 是一个自托管的 AI 代码助手，提供代码补全、代码生成等功能。支持多种模型，可以本地部署，适合企业内部使用。',
  vendor: 'TabbyML',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '研发提效'],
  homepageUrl: 'https://tabbyml.com',
  githubUrl: 'https://github.com/TabbyML/tabby',
  docsUrl: 'https://tabbyml.com/docs',
  githubStars: 22400,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '自托管代码助手',
  deployment: 'Docker, 本地部署',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地模型'],
  connectivity: ['本地运行', 'OpenAI API', 'Anthropic API'],
  scenarios: ['代码补全', '代码生成', '企业内部使用'],
  gfwStatus: '直连可用',
  pitfalls: ['需要本地部署', '模型配置复杂', '资源占用较高'],
  benchmark: { successRate: 85, avgDurationMin: 1.5, retries: 1.0 },
  community: { stars: '22.4k', release: 'v0.10.0', trend: '活跃' },
  rating: { security: 8.5, speed: 8.5, flexibility: 8.0, stability: 8.5, docs: 8.5 },
};
