import type { ToolProfile } from '@/lib/tools/types';

export const tabby: ToolProfile = {
  slug: 'tabby',
  name: 'Tabby',
  tagline: '自托管代码补全，21k stars',
  summary: 'Tabby 是一个自托管代码补全工具，支持多种编程语言和IDE。适合代码补全、 代码生成、 开发辅助等场景。',
  vendor: 'TabbyML',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://tabby.tabbyml.com',
  githubUrl: 'https://github.com/TabbyML/tabby',
  docsUrl: 'https://tabby.tabbyml.com/docs',
  githubStars: 21000,
  primaryLanguage: 'Rust',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '自托管代码补全',
  deployment: 'Docker, Self-hosted',
  modelSupport: ['StarCoder', 'CodeLlama', 'DeepSeek Coder'],
  connectivity: ['本地模型', 'OpenAI API'],
  scenarios: ['代码补全', '代码生成', '开发辅助'],
  gfwStatus: '直连可用',
  pitfalls: ['需要GPU资源', '模型下载较慢', '配置较复杂'],
  benchmark: { successRate: 85, avgDurationMin: 0.1, retries: 1.0 },
  community: { stars: '21k', release: 'v0.11.0', trend: '活跃' },
  rating: { security: 9.0, speed: 8.5, flexibility: 9.0, stability: 8.5, docs: 8.5 },
};
