import type { ToolProfile } from '@/lib/tools/types';

export const tagui: ToolProfile = {
  slug: 'tagui',
  name: 'TagUI',
  tagline: '通用RPA工具，5.6k stars',
  summary: 'TagUI 是一个通用RPA工具，支持自然语言脚本自动化。适合RPA自动化、 测试自动化、 任务自动化等场景。',
  vendor: 'AI Singapore',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://tagui.readthedocs.io',
  githubUrl: 'https://github.com/aisingapore/TagUI',
  docsUrl: 'https://tagui.readthedocs.io/en/latest',
  lastReleaseDate: "2022-06-20T03:29:06Z",
  latestVersion: "v6.110.0",
  lastCommitDate: "2026-02-11T14:51:27Z",
  githubStars: 6242,
  primaryLanguage: "JavaScript",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '通用RPA工具',
  deployment: 'Node.js Runtime, Desktop',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['RPA自动化', '测试自动化', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要脚本知识', '跨平台兼容性有限'],
  benchmark: { successRate: 82, avgDurationMin: 1.2, retries: 1.8 },
  community: { stars: '5.6k', release: 'v6.120', trend: '稳定' },
  rating: { security: 7.5, speed: 7.5, flexibility: 8.5, stability: 7.5, docs: 8.0 },
};
