import type { ToolProfile } from '@/lib/tools/types';

export const taskweaver: ToolProfile = {
  slug: 'taskweaver',
  name: 'TaskWeaver',
  tagline: '微软代码驱动的任务编排框架',
  summary: 'TaskWeaver 是微软推出的代码驱动型任务编排框架，通过生成和执行代码来完成复杂任务，适合数据分析和自动化场景。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', '代码生成', '数据自动化', '企业流程'],
  homepageUrl: null,
  githubUrl: 'https://github.com/microsoft/TaskWeaver',
  docsUrl: 'https://microsoft.github.io/TaskWeaver',
  githubStars: 6131,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: '代码生成执行、任务编排、数据分析',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['GPT-4', 'GPT-3.5', '支持本地模型'],
  connectivity: ['本地文件系统', 'Jupyter 内核', 'REST API'],
  scenarios: ['数据分析', '可视化生成', '自动化报告', '研究任务'],
  gfwStatus: '需要代理',
  pitfalls: ['代码执行需安全控制', '复杂任务需多次迭代'],
  benchmark: { successRate: 79, avgDurationMin: 8.2, retries: 1.7 },
  community: { stars: '5.6k', release: 'v0.5.0', trend: '稳定增长' },
  rating: { security: 7.6, speed: 7.5, flexibility: 8.4, stability: 7.6, docs: 7.8 },
};
