import type { ToolProfile } from '@/lib/tools/types';

export const ticlaw: ToolProfile = {
  slug: 'ticlaw',
  name: 'TiClaw',
  tagline: '腾讯云 TI 平台 Claw 服务',
  summary: '基于 TI-ONE 平台、机器学习的 OpenClaw 云服务。',
  vendor: '腾讯云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://ticlaw.tencent.com',
  githubUrl: null,
  docsUrl: 'https://cloud.tencent.com/docs/ticlaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按量计费',
  license: '商业闭源',
  focus: 'TI-ONE 平台、机器学习、智能体平台',
  deployment: '腾讯云托管',
  modelSupport: ['混元系列', 'TI-ONE 模型'],
  connectivity: ['腾讯云服务', 'API 访问'],
  scenarios: ['机器学习', '智能体平台', 'AI 开发'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖腾讯生态', '跨平台支持有限', '企业功能待完善'],
  benchmark: { successRate: 83, avgDurationMin: 6.0, retries: 1.5 },
  community: { stars: '官方服务', release: '持续迭代', trend: '机器学习场景采用增长' },
  rating: { security: 8.0, speed: 8.3, flexibility: 7.5, stability: 8.0, docs: 7.5 },
};
