import type { ToolProfile } from '@/lib/tools/types';

export const tongyiclaw: ToolProfile = {
  slug: 'tongyiclaw',
  name: 'TongyiClaw',
  tagline: '阿里云通义千问 Claw 服务',
  summary: '基于通义千问、企业集成的 OpenClaw 云服务。',
  vendor: '阿里云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://tongyiclaw.aliyun.com',
  githubUrl: null,
  docsUrl: 'https://help.aliyun.com/tongyiclaw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '按调用量计费',
  license: '商业闭源',
  focus: '通义千问、企业集成、大模型平台',
  deployment: '阿里云托管',
  modelSupport: ['通义千问', 'Qwen 系列'],
  connectivity: ['阿里云服务', '钉钉集成', '支付宝集成'],
  scenarios: ['企业集成', '知识问答', '智能助手'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖阿里生态', '跨云迁移成本高', '深度定制受限'],
  benchmark: { successRate: 84, avgDurationMin: 5.5, retries: 1.3 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业客户增长稳定' },
  rating: { security: 8.0, speed: 8.3, flexibility: 7.5, stability: 8.2, docs: 8.0 },
};
