import type { ToolProfile } from '@/lib/tools/types';

export const tray: ToolProfile = {
  slug: 'tray',
  name: 'Tray.io',
  tagline: '通用自动化平台',
  summary: 'Tray.io 是一款通用自动化平台，提供可视化工作流设计和 AI 辅助构建能力，适合中大型企业构建复杂业务自动化流程。',
  vendor: 'Tray.io',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', '可视化编排', '商业软件', 'AI'],
  homepageUrl: 'https://tray.io',
  githubUrl: null,
  docsUrl: 'https://docs.tray.io',
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制，企业定价',
  license: '商业许可',
  focus: '可视化工作流、AI 辅助、企业集成',
  deployment: '云原生部署',
  modelSupport: ['自研 AI', '支持集成主流 LLM'],
  connectivity: ['600+ 预置 connector', 'REST API', 'Webhook'],
  scenarios: ['市场营销自动化', '销售流程', '客户数据平台', 'IT 运维'],
  gfwStatus: '需要代理',
  pitfalls: ['学习曲线陡峭', '定价不透明'],
  benchmark: { successRate: 86, avgDurationMin: 4.5, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 9.0, speed: 8.2, flexibility: 8.8, stability: 8.5, docs: 8.2 },
};
