import type { ToolProfile } from '@/lib/tools/types';

export const trustclaw: ToolProfile = {
  slug: 'trustclaw',
  name: 'TrustClaw',
  tagline: '在您睡眠时安全地执行任务的 AI',
  summary: 'TrustClaw 是一个 24/7 AI 助手，提供 1000+ OAuth 工具和沙盒执行功能。基于 OpenClaw 的理念构建，但为安全性从头重新设计。支持 Gmail、Notion、Slack、Google Drive、Discord、Dropbox 等多种应用集成。',
  vendor: 'Composio',
  sourceType: '闭源',
  region: '全球',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '安全', 'API 集成', '自动化', 'AI 平台', '企业流程'],
  homepageUrl: 'https://www.trustclaw.app/',
  githubUrl: null,
  docsUrl: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费 + 付费套餐',
  license: '专有',
  focus: '安全执行、OAuth 集成、1000+ 工具、沙盒环境',
  deployment: '云服务，秒级部署',
  modelSupport: ['多模型支持', 'AI 助手', '工具调用'],
  connectivity: ['OAuth 集成', 'Gmail', 'Notion', 'Slack', 'Google Drive', 'Discord', 'Dropbox'],
  scenarios: ['自动化任务', 'AI 助手', '应用集成', '安全执行'],
  gfwStatus: '需要代理',
  pitfalls: ['需要注册账户', '部分功能需付费'],
  benchmark: { successRate: 92, avgDurationMin: 2.0, retries: 1.0 },
  community: { stars: null, release: 'v1.0.0', trend: '商业运营' },
  rating: { security: 9.5, speed: 9.0, flexibility: 8.5, stability: 8.5, docs: 7.5 },
};
