import type { ToolProfile } from '@/lib/tools/types';

export const uagents: ToolProfile = {
  slug: 'uagents',
  name: 'uAgents',
  tagline: 'Fetch.ai 的轻量级 Agent 框架',
  summary: 'uAgents 是 Fetch.ai 推出的轻量级 Agent 框架，支持区块链集成和去中心化通信，适合构建 Web3 和 IoT 场景的 Agent 应用。',
  vendor: 'Fetch.ai',
  sourceType: '开源',
  region: '海外',
  primaryCategory: '多 Agent 协作框架',
  tags: ['Agent 协作', '开源', 'Web3', 'IoT', '去中心化'],
  homepageUrl: 'https://fetch.ai',
  githubUrl: 'https://github.com/fetchai/uAgents',
  docsUrl: 'https://docs.fetch.ai',
  githubStars: 1500,
  primaryLanguage: 'Python',
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '轻量级 Agent、区块链集成、去中心化通信',
  deployment: 'Python 包，支持 pip 安装',
  modelSupport: ['支持集成主流 LLM', '规则驱动'],
  connectivity: ['P2P 通信', '区块链节点', 'REST API'],
  scenarios: ['IoT 自动化', '供应链追踪', '去中心化交易', '传感器网络'],
  gfwStatus: '需要代理',
  pitfalls: ['区块链集成复杂度高', '学习曲线陡峭'],
  benchmark: { successRate: 70, avgDurationMin: 8.5, retries: 2.0 },
  community: { stars: '1.5k', release: 'v0.15.0', trend: '稳定维护' },
  rating: { security: 8.0, speed: 6.8, flexibility: 7.5, stability: 7.0, docs: 7.2 },
};
