import type { ToolProfile } from '@/lib/tools/types';

export const ufo: ToolProfile = {
  slug: 'ufo',
  name: 'UFO',
  tagline: '微软Windows UI Agent，3.5k stars',
  summary: 'UFO 是微软开发的Windows UI Agent，能够通过视觉理解自动操作Windows应用程序。支持多语言、多应用，适合Windows桌面自动化场景。',
  vendor: 'Microsoft',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面控制', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/microsoft/UFO',
  githubUrl: 'https://github.com/microsoft/UFO',
  docsUrl: 'https://github.com/microsoft/UFO#readme',
  githubStars: 8210,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'MIT',
  focus: 'Windows UI Agent',
  deployment: 'Windows, Python Runtime',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', 'Azure OpenAI'],
  connectivity: ['OpenAI API', 'Azure OpenAI', '本地模型'],
  scenarios: ['Windows桌面自动化', '应用程序操作', 'GUI测试', 'RPA'],
  gfwStatus: '需要代理',
  pitfalls: ['仅限Windows平台', '需要视觉模型', '复杂UI支持有限'],
  benchmark: { successRate: 80, avgDurationMin: 3.0, retries: 2.0 },
  community: { stars: '3.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 8.0, speed: 7.5, flexibility: 7.0, stability: 7.5, docs: 7.0 },
};
