import type { ToolProfile } from '@/lib/tools/types';

export const uipath: ToolProfile = {
  slug: 'uipath',
  name: 'UiPath',
  tagline: '企业级 RPA 自动化平台',
  summary: 'UiPath 是全球领先的企业级 RPA 平台，提供可视化流程设计、AI 集成、集中化管理能力，适合大型企业自动化转型。',
  vendor: 'UiPath Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', '可视化编排', '商业软件', '数据自动化'],
  homepageUrl: 'https://uipath.com',
  githubUrl: null,
  docsUrl: 'https://docs.uipath.com',
  githubStars: null,
  primaryLanguage: null,
  pricing: '企业定价，按需定制',
  license: '商业许可',
  focus: '企业 RPA、流程自动化、AI 集成',
  deployment: '企业级部署，支持私有云',
  modelSupport: ['自研 AI', '支持集成主流 LLM'],
  connectivity: ['企业系统 connector', 'API 集成', '桌面应用'],
  scenarios: ['财务自动化', 'HR 流程', '客户服务', '数据迁移'],
  gfwStatus: '需要代理',
  pitfalls: ['成本高', '学习曲线陡峭', '实施周期长'],
  benchmark: { successRate: 90, avgDurationMin: 3.5, retries: 1.0 },
  community: { stars: null, release: 'v2024.10', trend: '企业市场领导者' },
  rating: { security: 9.5, speed: 8.5, flexibility: 9.0, stability: 9.2, docs: 9.0 },
};
