import type { ToolProfile } from '@/lib/tools/types';

export const uivision: ToolProfile = {
  slug: 'uivision',
  name: 'UI.Vision',
  tagline: '浏览器RPA插件，1.5k stars',
  summary: 'UI.Vision 是一个浏览器RPA插件，支持网页自动化、 桌面自动化和OCR。适合RPA自动化、 测试自动化、 任务自动化等场景。',
  vendor: 'UI.Vision',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://ui.vision',
  githubUrl: 'https://github.com/A9T9/UI.Vision',
  docsUrl: 'https://ui.vision/docs',
  githubStars: 1500,
  primaryLanguage: 'JavaScript',
  pricing: '免费开源',
  license: 'GPL-3.0',
  focus: '浏览器RPA插件',
  deployment: 'Browser Extension',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['RPA自动化', '测试自动化', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '仅限浏览器场景', '功能有限'],
  benchmark: { successRate: 75, avgDurationMin: 1.5, retries: 2.5 },
  community: { stars: '1.5k', release: 'v7.0.0', trend: '稳定' },
  rating: { security: 7.0, speed: 7.0, flexibility: 7.0, stability: 7.0, docs: 7.5 },
};
