import type { ToolProfile } from '@/lib/tools/types';

export const uivision: ToolProfile = {
  slug: 'uivision',
  name: 'UIVision',
  tagline: '浏览器自动化 + 桌面 OCR 的开源 RPA 工具',
  summary: 'UIVision 是一款开源的自动化测试和 RPA 工具，结合了浏览器自动化和桌面 OCR 识别能力，适合需要跨桌面和 Web 场景的自动化需求。',
  vendor: 'A9T9',
  sourceType: '开源',
  region: '海外',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '计算机视觉', 'RPA', '开源', '浏览器自动化'],
  homepageUrl: 'https://uivision.com',
  githubUrl: 'https://github.com/A9T9/RPA',
  docsUrl: 'https://uivision.com/docs',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源，商业版本付费',
  license: 'MPL-2.0',
  focus: '浏览器自动化、OCR 识别、RPA 流程',
  deployment: '浏览器扩展 + 桌面应用',
  modelSupport: ['自研 OCR', '支持自定义模型集成'],
  connectivity: ['浏览器扩展', '本地桌面应用', 'API 调用'],
  scenarios: ['Web 自动化测试', '数据提取', '表单填写', '跨应用流程自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['OCR 精度依赖图像质量', '复杂桌面应用支持有限'],
  benchmark: { successRate: 78, avgDurationMin: 5.2, retries: 1.5 },
  community: { stars: '1.2k', release: 'v8.2.1', trend: '稳定维护' },
  rating: { security: 7.5, speed: 7.8, flexibility: 8.0, stability: 7.6, docs: 7.2 },
};
