import type { ToolProfile } from '@/lib/tools/types';

export const v0: ToolProfile = {
  slug: 'v0',
  name: 'v0',
  tagline: 'Vercel 的 AI UI 生成工具',
  summary: 'v0 是 Vercel 推出的 AI UI 生成工具，通过自然语言描述生成 React 组件和 Tailwind CSS 代码，适合快速构建前端界面。',
  vendor: 'Vercel',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', 'UI 生成', '商业软件', '前端开发', 'React'],
  homepageUrl: 'https://v0.dev',
  githubUrl: null,
  docsUrl: 'https://v0.dev/docs',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费 $20/月',
  license: '商业许可',
  focus: 'UI 生成、React 组件、Tailwind CSS',
  deployment: '云服务平台',
  modelSupport: ['GPT-4', 'Vercel 自研模型'],
  connectivity: ['Web 界面', 'CLI 工具', 'Vercel 集成'],
  scenarios: ['原型设计', 'UI 开发', '组件生成', '快速迭代'],
  gfwStatus: '需要代理',
  pitfalls: ['生成代码需人工优化', '复杂布局支持有限'],
  benchmark: { successRate: 85, avgDurationMin: 2.0, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '快速增长' },
  rating: { security: 8.0, speed: 9.0, flexibility: 8.5, stability: 8.2, docs: 8.5 },
};
