import type { ToolProfile } from '@/lib/tools/types';

export const vercelclaw: ToolProfile = {
  slug: 'vercelclaw',
  name: 'Vercel AI SDK Claw',
  tagline: 'Vercel 前端 AI Claw 服务',
  summary: '前端 AI、Next.js 集成的 OpenClaw 云服务。',
  vendor: 'Vercel',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://vercelclaw.vercel.com',
  githubUrl: null,
  docsUrl: 'https://vercel.com/docs/vercelclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费',
  license: '商业闭源',
  focus: '前端 AI、Next.js 集成、Vercel 生态',
  deployment: 'Vercel 托管',
  modelSupport: ['Vercel 模型', '自定义模型'],
  connectivity: ['Vercel 服务', 'API 访问'],
  scenarios: ['前端 AI', 'Next.js 集成', '开发场景'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 85, avgDurationMin: 5.5, retries: 1.3 },
  community: { stars: '官方服务', release: '持续更新', trend: '前端开发者采用增长' },
  rating: { security: 9.0, speed: 9.0, flexibility: 7.5, stability: 8.5, docs: 8.5 },
};
