import type { ToolProfile } from '@/lib/tools/types';

export const wenxinclaw: ToolProfile = {
  slug: 'wenxinclaw',
  name: 'WenxinClaw',
  tagline: '百度智能云文心 Claw 服务',
  summary: '基于文心一言、知识增强的 OpenClaw 云服务。',
  vendor: '百度智能云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://wenxinclaw.baidu.com',
  githubUrl: null,
  docsUrl: 'https://cloud.baidu.com/docs/wenxinclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按调用量',
  license: '商业闭源',
  focus: '文心一言、知识增强、千帆平台',
  deployment: '百度云托管',
  modelSupport: ['文心一言', 'ERNIE 系列', '千帆模型'],
  connectivity: ['百度云服务', 'API 访问'],
  scenarios: ['知识增强', '企业问答', '智能助手'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖百度生态', '跨云迁移成本高', '深度定制受限'],
  benchmark: { successRate: 83, avgDurationMin: 5.8, retries: 1.4 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业客户增长稳定' },
  rating: { security: 8.0, speed: 8.3, flexibility: 7.5, stability: 8.2, docs: 8.0 },
};
