import type { ToolProfile } from '@/lib/tools/types';

export const windsurf: ToolProfile = {
  slug: 'windsurf',
  name: 'Windsurf',
  tagline: 'Codeium 的 AI 原生 IDE',
  summary: 'Windsurf 是 Codeium 推出的 AI 原生 IDE，深度集成 AI 代码理解和生成能力，提供 Flow 模式的上下文感知编程体验。',
  vendor: 'Codeium',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['AI 编程', 'IDE', '商业软件', '开发工具', '代码补全'],
  homepageUrl: 'https://windsurf.ai',
  githubUrl: null,
  docsUrl: 'https://docs.windsurf.ai',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/Pro $15/月',
  license: '商业许可',
  focus: 'AI 代码理解、上下文感知、Flow 模式',
  deployment: '桌面 IDE',
  modelSupport: ['Codeium 自研模型', '多模型支持'],
  connectivity: ['IDE 插件', '本地项目', '云同步'],
  scenarios: ['日常开发', '代码审查', '重构', '调试'],
  gfwStatus: '需要代理',
  pitfalls: ['资源占用较高', '部分功能需联网'],
  benchmark: { successRate: 86, avgDurationMin: 3.5, retries: 1.3 },
  community: { stars: null, release: 'v1.0', trend: '快速增长' },
  rating: { security: 8.2, speed: 8.5, flexibility: 8.8, stability: 8.2, docs: 8.0 },
};
