import type { ToolProfile } from '@/lib/tools/types';

export const wizardcoder: ToolProfile = {
  slug: 'wizardcoder',
  name: 'WizardCoder',
  tagline: '代码生成模型，10.5k stars',
  summary: 'WizardCoder 是一个代码生成模型，提供代码补全、代码生成等功能。支持多种编程语言，适合本地部署。',
  vendor: 'NLPC',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Code Agent / 开发助手',
  tags: ['代码生成', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/nlpxucan/WizardLM',
  githubUrl: 'https://github.com/nlpxucan/WizardLM',
  docsUrl: 'https://github.com/nlpxucan/WizardLM#readme',
  githubStars: 9478,
  primaryLanguage: "Python",
  pricing: '免费开源',
  license: 'Apache-2.0',
  focus: '代码生成模型',
  deployment: 'Python Runtime, 本地部署',
  modelSupport: ['WizardCoder', '本地模型'],
  connectivity: ['本地运行'],
  scenarios: ['代码补全', '代码生成', '本地部署'],
  gfwStatus: '需要代理',
  pitfalls: ['资源占用较高', '复杂任务支持有限', '文档较少'],
  benchmark: { successRate: 78, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '10.5k', release: 'v1.0.0', trend: '稳定' },
  rating: { security: 7.5, speed: 8.0, flexibility: 7.5, stability: 7.5, docs: 7.5 },
};
