import type { ToolProfile } from '@/lib/tools/types';

export const workdayclaw: ToolProfile = {
  slug: 'workdayclaw',
  name: 'Workday AI Claw',
  tagline: 'Workday HR AI Claw 服务',
  summary: 'HCM 深度集成、HR 场景的 OpenClaw 云服务。',
  vendor: 'Workday',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '企业流程', '研发提效'],
  homepageUrl: 'https://workdayclaw.workday.com',
  githubUrl: null,
  docsUrl: 'https://docs.workday.com/workdayclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制',
  license: '商业闭源',
  focus: 'HCM 深度集成、HR 场景、人才管理',
  deployment: 'Workday Cloud 托管',
  modelSupport: ['Workday 模型', '自定义模型'],
  connectivity: ['Workday Cloud 服务', 'API 访问'],
  scenarios: ['HR 场景', 'HCM 集成', '人才管理'],
  gfwStatus: '强依赖海外服务',
  pitfalls: ['网络策略和成本控制是关键风险', '受服务区域与合规条件限制', '离线场景适配困难'],
  benchmark: { successRate: 83, avgDurationMin: 6.5, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '企业客户增长稳定' },
  rating: { security: 9.0, speed: 8.0, flexibility: 7.0, stability: 8.5, docs: 8.0 },
};
