import type { ToolProfile } from '@/lib/tools/types';

export const workato: ToolProfile = {
  slug: 'workato',
  name: 'Workato',
  tagline: '企业级 iPaaS 自动化平台',
  summary: 'Workato 是一款企业级 iPaaS 平台，结合 RPA 和 API 集成能力，提供预构建的 Business App，适合中大型企业复杂集成场景。',
  vendor: 'Workato Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', 'iPaaS', '商业软件', 'API 集成'],
  homepageUrl: 'https://workato.com',
  githubUrl: null,
  docsUrl: 'https://docs.workato.com',
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅制，按任务量计费',
  license: '商业许可',
  focus: 'API 集成、RPA、Business App',
  deployment: '云原生部署',
  modelSupport: ['自研 AI', '支持集成第三方模型'],
  connectivity: ['1000+ 预置 connector', 'REST API', '数据库连接'],
  scenarios: ['ERP 集成', 'CRM 自动化', 'HR 流程', 'IT 运维'],
  gfwStatus: '需要代理',
  pitfalls: ['定价较高', '需要专业实施团队'],
  benchmark: { successRate: 89, avgDurationMin: 3.8, retries: 1.1 },
  community: { stars: null, release: '持续更新', trend: '企业市场增长' },
  rating: { security: 9.2, speed: 8.5, flexibility: 9.0, stability: 9.0, docs: 8.5 },
};
