import type { ToolProfile } from '@/lib/tools/types';

export const xarm: ToolProfile = {
  slug: 'xarm',
  name: 'xArm',
  tagline: '机械臂自动化控制，1.2k stars',
  summary: 'xArm 是一个机械臂自动化控制库，支持多种机械臂型号。适合工业自动化、 机器人控制、 任务自动化等场景。',
  vendor: 'UFACTORY',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'Computer Use / 桌面自动化',
  tags: ['桌面自动化', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://www.ufactory.cc',
  githubUrl: 'https://github.com/xArm-Developer/xArm-CPLUS-SDK',
  docsUrl: 'https://github.com/xArm-Developer/xArm-CPLUS-SDK#readme',
  githubStars: 1200,
  primaryLanguage: 'C++',
  pricing: '免费开源',
  license: 'MIT',
  focus: '机械臂自动化控制',
  deployment: 'Desktop Application, Robot',
  modelSupport: ['无AI模型'],
  connectivity: ['无API依赖'],
  scenarios: ['工业自动化', '机器人控制', '任务自动化'],
  gfwStatus: '直连可用',
  pitfalls: ['无AI能力', '需要硬件设备', '专业领域知识'],
  benchmark: { successRate: 88, avgDurationMin: 2.0, retries: 1.5 },
  community: { stars: '1.2k', release: 'v1.12.0', trend: '稳定' },
  rating: { security: 8.0, speed: 8.0, flexibility: 7.5, stability: 8.5, docs: 7.5 },
};
