import type { ToolProfile } from '@/lib/tools/types';

export const xinghuoclaw: ToolProfile = {
  slug: 'xinghuoclaw',
  name: 'XinghuoClaw',
  tagline: '科大讯飞星火 AI 助手平台 Claw 服务',
  summary: '基于星火大模型、语音能力的 OpenClaw 云服务。',
  vendor: '科大讯飞',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://xinghuoclaw.xfyun.cn',
  githubUrl: null,
  docsUrl: 'https://xinghuo.xfyun.cn/docs/claw',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '订阅/按量',
  license: '商业闭源',
  focus: '星火大模型、语音能力、AI 助手平台',
  deployment: '讯飞云托管',
  modelSupport: ['星火系列', 'Spark 大模型'],
  connectivity: ['讯飞云服务', 'API 访问', 'WebSocket'],
  scenarios: ['语音交互', '教育场景', '智能助手'],
  gfwStatus: '直连可用',
  pitfalls: ['生态成熟度仍在完善', '复杂多 Agent 场景能力边界需验证', '跨平台可移植性较弱'],
  benchmark: { successRate: 81, avgDurationMin: 6.3, retries: 1.6 },
  community: { stars: '官方服务', release: '持续更新', trend: '教育场景采用增长' },
  rating: { security: 8.0, speed: 8.1, flexibility: 7.5, stability: 7.8, docs: 7.5 },
};
