import type { ToolProfile } from '@/lib/tools/types';

export const yanxiclaw: ToolProfile = {
  slug: 'yanxiclaw',
  name: 'YanxiClaw',
  tagline: '京东云言犀 Claw 服务',
  summary: '基于言犀大模型、电商场景的 OpenClaw 云服务。',
  vendor: '京东云',
  sourceType: '闭源',
  region: '国内',
  primaryCategory: 'OpenClaw 云服务',
  tags: ['云服务', '闭源', '个人助手', '研发提效'],
  homepageUrl: 'https://yanxiclaw.jdcloud.com',
  githubUrl: null,
  docsUrl: 'https://docs.jdcloud.com/yanxiclaw',
  githubStars: null,
  primaryLanguage: null,
  pricing: '按量计费',
  license: '商业闭源',
  focus: '言犀大模型、电商场景、对话 AI',
  deployment: '京东云托管',
  modelSupport: ['言犀系列', 'Yanxi 大模型'],
  connectivity: ['京东云服务', 'API 访问'],
  scenarios: ['电商场景', '对话 AI', '智能客服'],
  gfwStatus: '直连可用',
  pitfalls: ['依赖京东生态', '跨平台支持有限', '企业功能待完善'],
  benchmark: { successRate: 82, avgDurationMin: 6.0, retries: 1.5 },
  community: { stars: '官方服务', release: '持续更新', trend: '电商场景采用增长' },
  rating: { security: 8.0, speed: 8.2, flexibility: 7.0, stability: 7.8, docs: 7.5 },
};
