import type { ToolProfile } from '@/lib/tools/types';

export const youcom: ToolProfile = {
  slug: 'youcom',
  name: 'You.com',
  tagline: 'AI 搜索引擎平台',
  summary: 'You.com 是一款 AI 搜索引擎平台，提供可定制的搜索结果和 AI 对话能力，支持开发者构建自定义搜索应用。',
  vendor: 'You.com',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI 搜索', '信息搜集', '商业软件', '个人助手', '开发工具'],
  homepageUrl: 'https://you.com',
  githubUrl: null,
  docsUrl: 'https://documentation.you.com',
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费/付费订阅',
  license: '商业许可',
  focus: 'AI 搜索、可定制、API 开放',
  deployment: 'Web 应用 + API',
  modelSupport: ['自研模型', '多模型支持'],
  connectivity: ['Web 界面', 'REST API', '浏览器扩展'],
  scenarios: ['信息搜集', '开发搜索', 'API 集成', '研究'],
  gfwStatus: '需要代理',
  pitfalls: ['国内访问速度慢', 'API 调用有限额'],
  benchmark: { successRate: 85, avgDurationMin: 4.5, retries: 1.3 },
  community: { stars: null, release: '持续更新', trend: '稳定增长' },
  rating: { security: 8.2, speed: 8.5, flexibility: 8.8, stability: 8.5, docs: 8.2 },
};
