import type { ToolProfile } from '@/lib/tools/types';

export const zapierCentral: ToolProfile = {
  slug: 'zapier-central',
  name: 'Zapier Central',
  tagline: 'Zapier 的 AI Bot 自动化平台',
  summary: 'Zapier Central 是 Zapier 推出的 AI Bot 自动化平台，结合 5000+ 应用集成和 AI 决策能力，适合构建智能业务流程。',
  vendor: 'Zapier Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: '通用任务执行 Agent',
  tags: ['AI', '工作流自动化', '商业软件', '企业流程', '多模态'],
  homepageUrl: 'https://zapier.com/central',
  githubUrl: null,
  docsUrl: 'https://docs.zapier.com/central',
  githubStars: null,
  primaryLanguage: null,
  pricing: '$19.99 起/月',
  license: '商业许可',
  focus: 'AI Bot、工作流自动化、智能决策',
  deployment: '云服务平台',
  modelSupport: ['GPT-4', 'Claude', 'Zapier AI'],
  connectivity: ['5000+ 应用集成', 'REST API', 'Webhook'],
  scenarios: ['客户服务自动化', '数据处理', '业务流程', '智能通知'],
  gfwStatus: '需要代理',
  pitfalls: ['价格较高', '国内访问速度慢'],
  benchmark: { successRate: 88, avgDurationMin: 4.0, retries: 1.2 },
  community: { stars: null, release: '持续更新', trend: '新产品增长中' },
  rating: { security: 9.0, speed: 8.5, flexibility: 9.0, stability: 8.8, docs: 8.5 },
};
