import type { ToolProfile } from '@/lib/tools/types';

export const zapier: ToolProfile = {
  slug: 'zapier',
  name: 'Zapier',
  tagline: '全球领先的工作流自动化平台',
  summary: 'Zapier 是全球领先的工作流自动化平台，提供 5000+ 应用集成和 AI 辅助构建能力，适合个人和企业快速实现自动化。',
  vendor: 'Zapier Inc',
  sourceType: '闭源',
  region: '海外',
  primaryCategory: 'RPA 自动化',
  tags: ['RPA', '企业流程', '低代码', '商业软件', 'AI'],
  homepageUrl: 'https://zapier.com',
  githubUrl: null,
  docsUrl: 'https://docs.zapier.com',
  githubStars: null,
  primaryLanguage: null,
  pricing: '$19.99 起/月，按任务量计费',
  license: '商业许可',
  focus: '应用集成、工作流自动化、AI 辅助',
  deployment: '云服务平台',
  modelSupport: ['Zapier AI', '支持集成 LLM'],
  connectivity: ['5000+ 应用集成', 'REST API', 'Webhook'],
  scenarios: ['市场营销自动化', '销售流程', '客户支持', '项目管理'],
  gfwStatus: '需要代理',
  pitfalls: ['价格较高', '国内访问速度慢'],
  benchmark: { successRate: 90, avgDurationMin: 3.0, retries: 1.0 },
  community: { stars: null, release: '持续更新', trend: '市场领导者' },
  rating: { security: 9.0, speed: 8.5, flexibility: 9.5, stability: 9.2, docs: 9.0 },
};
