import type { ToolProfile } from '@/lib/tools/types';

export const zeroclaw: ToolProfile = {
  slug: 'zeroclaw',
  name: 'ZeroClaw',
  tagline: '零配置启动的轻量级桌面 Agent',
  summary: '适合快速验证和轻量自动化场景的 OpenClaw 精简版。',
  vendor: 'OpenClaw 社区',
  sourceType: '开源',
  region: '全球',
  primaryCategory: 'OpenClaw 生态',
  tags: ['桌面控制', 'Shell 执行', '开源', '自部署', '本地优先'],
  homepageUrl: 'https://github.com/zeroclaw-labs/zeroclaw',
  githubUrl: 'https://github.com/zeroclaw-labs/zeroclaw',
  docsUrl: 'https://github.com/zeroclaw-labs/zeroclaw#readme',
  lastReleaseDate: null,
  latestVersion: null,
  lastCommitDate: null,
  githubStars: null,
  primaryLanguage: null,
  pricing: '免费开源',
  license: 'MIT',
  focus: '零配置启动、轻量自动化、快速部署',
  deployment: '单二进制文件，无需依赖',
  modelSupport: ['GPT-4o', 'Claude 3.5', 'DeepSeek R1', '本地 LLM'],
  connectivity: ['本地运行', '可选云模型 API'],
  scenarios: ['快速原型', '轻量自动化', '开发测试'],
  gfwStatus: '直连可用',
  pitfalls: ['功能相对精简', '高级编排能力弱', '不支持分布式部署'],
  benchmark: { successRate: 82, avgDurationMin: 5.2, retries: 1.5 },
  community: { stars: '5.2k', release: 'v0.8.1', trend: '轻量化场景用户增长' },
  rating: { security: 8.0, speed: 9.2, flexibility: 7.5, stability: 8.3, docs: 7.5 },
};
